{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "omni-platform.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "omni-platform.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}

---

{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
    {{- include "omni-platform.labels" . | nindent 4 }}
{{- end }}
