from fastapi import APIRouter, Depends, Body
from typing import Optional, Dict, Any
from database import get_database
from authentication_service import get_current_user
from datetime import datetime, timezone, timedelta
from agent_auth import verify_agent_key
import logging

router = APIRouter(prefix="/api/agents", tags=["Agents"])
logger = logging.getLogger("agent_telemetry_endpoints")


@router.get("/{agent_id}/goals")
async def get_agent_goals(
    agent_id: str,
    _tenant: Dict[str, Any] = Depends(verify_agent_key)
):
    """Get current high-level goals for an agent, dynamically generated by AI."""
    from agent_logic_service import agent_logic_service
    db = get_database()
    agent = await db.agents.find_one({"id": agent_id}, {"_id": 0})
    if not agent:
        return [{"name": "Security Baseline", "target": 100.0, "current": 80.0, "status": "active"}]
    return await agent_logic_service.generate_goals(agent)


@router.get("/{agent_id}/metrics")
async def get_agent_metrics(agent_id: str, limit: int = 60, _user=Depends(get_current_user)):
    """Return the last N metric snapshots for an agent (CPU, memory, disk over time)."""
    db = get_database()
    snapshots = await db.agent_metrics_history.find(
        {"agent_id": agent_id},
        {"_id": 0, "cpu": 1, "memory": 1, "disk": 1, "timestamp": 1}
    ).sort("timestamp", -1).limit(limit).to_list(length=limit)
    snapshots.reverse()

    if not snapshots:
        agent = await db.agents.find_one({"id": agent_id}, {"_id": 0, "meta": 1})
        if agent:
            meta = agent.get("meta", {})
            if meta.get("current_cpu") is not None:
                snapshots = [{
                    "cpu": meta.get("current_cpu", 0),
                    "memory": meta.get("current_memory", 0),
                    "disk": meta.get("disk_usage", 0),
                    "timestamp": meta.get("last_seen", datetime.now(timezone.utc).isoformat()),
                }]

    return {"agent_id": agent_id, "snapshots": snapshots}


@router.post("/{agent_id}/software-inventory")
async def report_software_inventory(
    agent_id: str,
    payload: Dict[str, Any] = Body(...),
    _tenant: Dict[str, Any] = Depends(verify_agent_key)
):
    """Agent reports live software inventory result from 'run_software_scan'."""
    db = get_database()
    sw_list = payload.get("software_inventory", [])
    hostname = payload.get("hostname", agent_id)
    tenant_id = payload.get("tenantId", _tenant["id"] if _tenant else "default")

    await db.agents.update_one(
        {"id": agent_id},
        {"$set": {
            "meta.software_inventory": sw_list,
            "meta.os_patches": payload.get("os_patches", {}),
            "lastSeen": datetime.now(timezone.utc).isoformat()
        }}
    )

    processed = 0
    for sw in sw_list:
        await db.software_inventory.update_one(
            {"agent_id": agent_id, "name": sw.get("name")},
            {"$set": {
                "agent_id": agent_id, "agent_name": hostname, "tenant_id": tenant_id,
                "name": sw.get("name"), "current_version": sw.get("current_version"),
                "latest_version": sw.get("latest_version"), "pkg_type": sw.get("pkg_type", "unknown"),
                "is_outdated": sw.get("is_outdated", False),
                "last_scanned": datetime.now(timezone.utc).isoformat()
            }},
            upsert=True
        )
        processed += 1

    return {"success": True, "processed": processed}


@router.get("/{agent_id}/threat-intel")
async def get_threat_intel_broadcasts(
    agent_id: str,
    _tenant: Dict[str, Any] = Depends(verify_agent_key),
):
    """
    Agents poll this to receive IoC broadcasts from the correlation engine.
    Each broadcast is returned only once per agent (seen_agents dedup).
    """
    db = get_database()
    agent = await db.agents.find_one({"id": agent_id}, {"tenantId": 1})
    if not agent:
        return []
    tenant_id = agent.get("tenantId", "default")
    threshold = (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
    broadcasts = await db.threat_intel_broadcast.find(
        {"tenant_id": tenant_id, "timestamp": {"$gte": threshold}, "seen_agents": {"$ne": agent_id}},
        {"_id": 0},
    ).to_list(length=20)

    if broadcasts:
        await db.threat_intel_broadcast.update_many(
            {"tenant_id": tenant_id, "timestamp": {"$gte": threshold}},
            {"$addToSet": {"seen_agents": agent_id}},
        )
    return broadcasts


@router.post("/{agent_id}/logs/raw")
async def receive_raw_logs(
    agent_id: str,
    payload: Dict[str, Any] = Body(...),
    _tenant: Dict[str, Any] = Depends(verify_agent_key),
):
    """Receive raw OS logs shipped by the LogShipperCapability and ingest into SIEM."""
    db = get_database()
    logs = payload.get("logs", [])[:500]  # cap batch size to prevent DoS
    if logs:
        now = datetime.now(timezone.utc).isoformat()
        await db.raw_logs.insert_many([
            {
                "agent_id": agent_id, "source": log.get("source", "unknown"),
                "raw_message": log.get("raw_message", ""), "event_id": log.get("event_id"),
                "collected_at": log.get("collected_at", now), "ingested_at": now,
            }
            for log in logs
        ])
    return {"success": True, "ingested": len(logs)}


@router.post("/{agent_id}/threat-hunt-results")
async def receive_threat_hunt_results(
    agent_id: str,
    payload: Dict[str, Any] = Body(...),
    _tenant: Dict[str, Any] = Depends(verify_agent_key),
):
    """Store threat hunt results reported by an agent after run_threat_hunt dispatch."""
    db = get_database()
    await db.threat_hunt_results.insert_one({
        "agent_id": agent_id,
        "timestamp": payload.get("timestamp", datetime.now(timezone.utc).isoformat()),
        "results": payload.get("results", {}),
    })
    return {"success": True}
