"""OCI cloud security check definitions (CIS OCI Foundations-aligned). Used by cloud_checks_service.py."""
OCI_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "oci-iam-001", "name": "Tenancy administrators require MFA", "description": "OCI tenancy administrator accounts must have multi-factor authentication enabled", "provider": "oci", "service": "iam", "severity": "critical", "frameworks": ["CIS-OCI-1.7", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enable MFA for all users in the Administrators group via the OCI Console Identity settings."},
    {"id": "oci-iam-002", "name": "IAM password policy enforces minimum length", "description": "OCI IAM password policy must require at least 14 characters", "provider": "oci", "service": "iam", "severity": "medium", "frameworks": ["CIS-OCI-1.9", "NIST-IA-5"], "remediation": "Update the tenancy password policy to require a minimum length of 14 characters."},
    {"id": "oci-iam-003", "name": "API signing keys rotated within 90 days", "description": "OCI API signing keys must be rotated at least every 90 days", "provider": "oci", "service": "iam", "severity": "high", "frameworks": ["CIS-OCI-1.11", "NIST-IA-5", "PCI-8.3.9"], "remediation": "Rotate API signing keys older than 90 days and remove unused keys from user credentials."},
    {"id": "oci-iam-004", "name": "IAM policies not overly permissive", "description": "OCI IAM policies should not grant tenancy-wide manage access broadly via 'manage all-resources'", "provider": "oci", "service": "iam", "severity": "critical", "frameworks": ["CIS-OCI-1.14", "NIST-AC-6", "SOC2-CC6.3"], "remediation": "Replace broad 'manage all-resources' policy statements with scoped, least-privilege policies."},
    # ─── Storage ────────────────────────────────────────────────────────────
    {"id": "oci-storage-001", "name": "Object Storage buckets not publicly accessible", "description": "OCI Object Storage buckets must not have public visibility enabled", "provider": "oci", "service": "storage", "severity": "critical", "frameworks": ["CIS-OCI-2.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set bucket visibility to Private for all Object Storage buckets."},
    {"id": "oci-storage-002", "name": "Block Volume backups enabled", "description": "OCI Block Volumes should have an automated backup policy assigned", "provider": "oci", "service": "storage", "severity": "medium", "frameworks": ["CIS-OCI-2.4", "NIST-CP-9"], "remediation": "Assign a backup policy to all Block Volumes to enable automated backups."},
    # ─── Encryption ─────────────────────────────────────────────────────────
    {"id": "oci-encryption-001", "name": "Object Storage bucket encrypted with customer-managed key", "description": "OCI Object Storage buckets should use a customer-managed Vault key instead of Oracle-managed keys", "provider": "oci", "service": "encryption", "severity": "high", "frameworks": ["CIS-OCI-2.2", "NIST-SC-28", "PCI-3.4"], "remediation": "Configure Object Storage buckets to encrypt data using a customer-managed key from OCI Vault."},
    {"id": "oci-encryption-002", "name": "Block Volume encrypted with customer-managed key", "description": "OCI Block Volumes should use a customer-managed Vault key instead of Oracle-managed keys", "provider": "oci", "service": "encryption", "severity": "high", "frameworks": ["CIS-OCI-2.5", "NIST-SC-28", "PCI-3.4"], "remediation": "Configure Block Volumes to encrypt data using a customer-managed key from OCI Vault."},
    # ─── Logging ────────────────────────────────────────────────────────────
    {"id": "oci-logging-001", "name": "VCN flow logs enabled for all subnets", "description": "OCI Virtual Cloud Network subnets must have flow logs enabled", "provider": "oci", "service": "logging", "severity": "medium", "frameworks": ["CIS-OCI-3.14", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable flow logs on all VCN subnets and send them to OCI Logging."},
    {"id": "oci-logging-002", "name": "Audit log retention at least 365 days", "description": "OCI Audit service log retention period must be set to at least 365 days", "provider": "oci", "service": "logging", "severity": "high", "frameworks": ["CIS-OCI-3.1", "NIST-AU-11", "PCI-10.7"], "remediation": "Set the tenancy Audit log retention period to at least 365 days."},
]
