"""Alibaba Cloud security check definitions (Cloud Config / Security Center baseline-aligned). Used by cloud_checks_service.py."""
ALIBABA_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "alibaba-iam-001", "name": "RAM users require MFA", "description": "Alibaba Cloud RAM user accounts must have multi-factor authentication enabled", "provider": "alibaba", "service": "iam", "severity": "critical", "frameworks": ["CIS-Alibaba-1.1", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enable MFA for all RAM users via the RAM console security settings."},
    {"id": "alibaba-iam-002", "name": "RAM password policy enforces strength requirements", "description": "Alibaba Cloud RAM password policy must require minimum length and complexity", "provider": "alibaba", "service": "iam", "severity": "medium", "frameworks": ["CIS-Alibaba-1.3", "NIST-IA-5"], "remediation": "Configure the RAM account password policy to require at least 14 characters with mixed case, digits, and symbols."},
    {"id": "alibaba-iam-003", "name": "RAM AccessKey rotated within 90 days", "description": "Alibaba Cloud RAM user AccessKeys must be rotated at least every 90 days", "provider": "alibaba", "service": "iam", "severity": "high", "frameworks": ["ALIBABA-Config-ram-accesskey-rotation", "NIST-IA-5", "PCI-8.3.9"], "remediation": "Rotate RAM AccessKeys older than 90 days and remove unused keys."},
    # ─── Storage ────────────────────────────────────────────────────────────
    {"id": "alibaba-storage-001", "name": "OSS bucket ACL not public", "description": "Alibaba Cloud OSS bucket ACL must not be set to public-read or public-read-write", "provider": "alibaba", "service": "storage", "severity": "critical", "frameworks": ["ALIBABA-Config-oss-bucket-public-read-prohibited", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set OSS bucket ACL to private and review bucket policy statements for public grants."},
    {"id": "alibaba-storage-002", "name": "OSS bucket versioning enabled", "description": "Alibaba Cloud OSS buckets storing critical data should have versioning enabled", "provider": "alibaba", "service": "storage", "severity": "medium", "frameworks": ["ALIBABA-Config-oss-bucket-versioning", "NIST-CP-10"], "remediation": "Enable versioning on OSS buckets holding important data."},
    # ─── Encryption ─────────────────────────────────────────────────────────
    {"id": "alibaba-encryption-001", "name": "OSS bucket server-side encryption enabled", "description": "Alibaba Cloud OSS buckets must have default server-side encryption enabled", "provider": "alibaba", "service": "encryption", "severity": "high", "frameworks": ["ALIBABA-Config-oss-bucket-server-side-encryption", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable server-side encryption (KMS or AES256) as the default for all OSS buckets."},
    {"id": "alibaba-encryption-002", "name": "ECS disk encryption enabled", "description": "Alibaba Cloud ECS cloud disks must be encrypted at rest", "provider": "alibaba", "service": "encryption", "severity": "high", "frameworks": ["ALIBABA-Config-ecs-disk-encryption", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable disk encryption using a KMS key when creating or attaching ECS cloud disks."},
    # ─── Logging ────────────────────────────────────────────────────────────
    {"id": "alibaba-logging-001", "name": "ActionTrail enabled across all regions", "description": "Alibaba Cloud ActionTrail must be enabled and logging across all regions", "provider": "alibaba", "service": "logging", "severity": "critical", "frameworks": ["ALIBABA-Config-actiontrail-enabled-all-regions", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Create a multi-region ActionTrail trail covering all regions and enable it."},
    {"id": "alibaba-logging-002", "name": "Security Center baseline checks passing", "description": "Alibaba Cloud Security Center baseline checks should be passing with no open critical findings", "provider": "alibaba", "service": "logging", "severity": "medium", "frameworks": ["ALIBABA-SAS-baseline-check", "NIST-CA-7", "SOC2-CC7.2"], "remediation": "Review and remediate open Security Center baseline check findings."},
]
