"""Cloudflare cloud security check definitions (Security Center taxonomy-aligned). Used by cloud_checks_service.py."""
CLOUDFLARE_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "cf-iam-001", "name": "Cloudflare Access application requires identity provider auth", "description": "Cloudflare Access applications must require authentication through a configured identity provider", "provider": "cloudflare", "service": "iam", "severity": "critical", "frameworks": ["CF-SecurityCenter-Access", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Configure a Cloudflare Access policy requiring identity provider authentication for every protected application."},
    {"id": "cf-iam-002", "name": "API tokens scoped with least privilege", "description": "Cloudflare API tokens should use scoped permissions instead of the account-wide Global API Key", "provider": "cloudflare", "service": "iam", "severity": "high", "frameworks": ["CF-SecurityCenter-APIToken", "NIST-AC-6", "SOC2-CC6.3"], "remediation": "Replace the Global API Key with scoped API tokens limited to the minimum required permissions."},
    # ─── Storage ────────────────────────────────────────────────────────────
    {"id": "cf-storage-001", "name": "R2 bucket public access disabled", "description": "Cloudflare R2 buckets must not allow public read access", "provider": "cloudflare", "service": "storage", "severity": "critical", "frameworks": ["CF-SecurityCenter-R2", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Disable public access and remove public development URLs on R2 buckets."},
    {"id": "cf-storage-002", "name": "R2 bucket versioning enabled", "description": "Cloudflare R2 buckets storing critical data should have object versioning enabled", "provider": "cloudflare", "service": "storage", "severity": "medium", "frameworks": ["CF-SecurityCenter-R2", "NIST-CP-10"], "remediation": "Enable versioning on R2 buckets holding important data."},
    # ─── Encryption ─────────────────────────────────────────────────────────
    {"id": "cf-encryption-001", "name": "SSL/TLS encryption mode set to Full (strict)", "description": "Zone SSL/TLS encryption mode should be set to Full (strict) to validate the origin certificate", "provider": "cloudflare", "service": "encryption", "severity": "critical", "frameworks": ["CF-SecurityCenter-TLS", "NIST-SC-8", "PCI-4.1"], "remediation": "Set the zone SSL/TLS encryption mode to Full (strict) in the SSL/TLS app."},
    {"id": "cf-encryption-002", "name": "Minimum TLS version set to 1.2 or higher", "description": "Zone minimum TLS version should be 1.2 or higher", "provider": "cloudflare", "service": "encryption", "severity": "high", "frameworks": ["CF-SecurityCenter-TLS", "NIST-SC-8", "PCI-4.1"], "remediation": "Set the zone Minimum TLS Version to 1.2 in the SSL/TLS Edge Certificates settings."},
    {"id": "cf-encryption-003", "name": "Always Use HTTPS enabled", "description": "Zone should redirect all HTTP requests to HTTPS", "provider": "cloudflare", "service": "encryption", "severity": "high", "frameworks": ["CF-SecurityCenter-TLS", "NIST-SC-8"], "remediation": "Enable the Always Use HTTPS setting in the zone's SSL/TLS Edge Certificates settings."},
    {"id": "cf-encryption-004", "name": "HSTS enabled", "description": "Zone should enable HTTP Strict Transport Security", "provider": "cloudflare", "service": "encryption", "severity": "medium", "frameworks": ["CF-SecurityCenter-TLS", "NIST-SC-8"], "remediation": "Enable HSTS with a suitable max-age in the SSL/TLS Edge Certificates settings."},
    # ─── Logging ────────────────────────────────────────────────────────────
    {"id": "cf-logging-001", "name": "Logpush job configured for HTTP requests", "description": "A Logpush job should be configured to export HTTP request logs", "provider": "cloudflare", "service": "logging", "severity": "medium", "frameworks": ["CF-SecurityCenter-Logpush", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Create a Logpush job to continuously export HTTP request logs to a storage destination."},
    {"id": "cf-logging-002", "name": "Audit logs enabled and retained", "description": "Cloudflare account audit logs should be enabled and retained for review", "provider": "cloudflare", "service": "logging", "severity": "medium", "frameworks": ["CF-SecurityCenter-AuditLog", "NIST-AU-11", "PCI-10.7"], "remediation": "Ensure audit logging is enabled at the account level and export logs for long-term retention."},
]
