"""Feature catalog — master registry of every platform feature and its metadata."""
from __future__ import annotations
from typing import Dict

# Each entry: key → {name, description, category, minTier, permission}
FEATURE_CATALOG: Dict[str, dict] = {
    # ── Core (always on Free) ────────────────────────────────────────────────
    "dashboard": {
        "name": "Overview Dashboard",
        "description": "Main platform overview with KPIs and quick-access widgets.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:dashboard",
    },
    "tickets": {
        "name": "Internal Ticketing",
        "description": "Issue tracker and internal support ticket management.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:tickets",
    },
    "agents": {
        "name": "Agent Management",
        "description": "Deploy, monitor, and manage endpoint agents.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:agents",
    },
    "assets": {
        "name": "Asset Inventory",
        "description": "Discover and track all hardware and software assets.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:assets",
    },
    "users": {
        "name": "User Management",
        "description": "Manage platform users, roles, and permissions.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:users",
    },
    "settings": {
        "name": "Platform Settings",
        "description": "Configure integrations, data sources, and platform preferences.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:settings",
    },
    "audit_log": {
        "name": "Audit Log",
        "description": "Immutable log of all platform actions for compliance and forensics.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:audit_log",
    },
    "knowledge_base": {
        "name": "Knowledge Base",
        "description": "Internal documentation, runbooks, and playbook library.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:knowledge_base",
    },
    "support_chat": {
        "name": "Support Chat",
        "description": "Real-time support messaging with the platform team.",
        "category": "core",
        "minTier": "Free",
        "permission": "view:support_chat",
    },

    # ── Observability Bundle ─────────────────────────────────────────────────
    "observability": {
        "name": "Observability",
        "description": "Full-stack observability — metrics, traces, and logs in one view.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:observability",
    },
    "apm": {
        "name": "Application Performance Monitoring",
        "description": "Latency, error rate, and throughput tracking for services.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:apm",
    },
    "tracing": {
        "name": "Distributed Tracing",
        "description": "End-to-end request tracing across microservices.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:tracing",
    },
    "logs": {
        "name": "Log Explorer",
        "description": "Structured log search, filtering, and anomaly detection.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:logs",
    },
    "network": {
        "name": "Network Monitoring",
        "description": "Traffic analysis, topology mapping, and anomaly detection.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:network",
    },
    "web_monitoring": {
        "name": "Web Monitoring",
        "description": "Uptime, performance, and real-user monitoring for web apps.",
        "category": "observability",
        "minTier": "Pro",
        "permission": "view:web_monitoring",
    },

    # ── Security Bundle ──────────────────────────────────────────────────────
    "vulnerabilities": {
        "name": "Vulnerability Management",
        "description": "CVE tracking, risk scoring, and remediation workflows.",
        "category": "security",
        "minTier": "Free",
        "permission": "view:vulnerabilities",
    },
    "edr": {
        "name": "Endpoint Detection & Response",
        "description": "Real-time threat detection and response on endpoints.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:edr",
    },
    "mdr": {
        "name": "Managed Detection & Response",
        "description": "24/7 managed threat monitoring with expert-guided response.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:mdr",
    },
    "xdr": {
        "name": "Extended Detection & Response",
        "description": "Cross-layer detection across endpoints, network, and cloud.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:xdr",
    },
    "threat_hunting": {
        "name": "Threat Hunting",
        "description": "Proactive search for hidden threats across telemetry.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:threat_hunting",
    },
    "threat_intel": {
        "name": "Threat Intelligence",
        "description": "IOC feeds, MITRE ATT&CK mapping, and threat actor tracking.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:threat_intel",
    },
    "ueba": {
        "name": "User & Entity Behavior Analytics",
        "description": "Anomaly detection on user and entity behavioral patterns.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:ueba",
    },
    "dlp": {
        "name": "Data Loss Prevention",
        "description": "Detect and prevent unauthorized data exfiltration.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:dlp",
    },
    "siem": {
        "name": "SIEM",
        "description": "Security event correlation, alerting, and case management.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:siem",
    },
    "incident_response": {
        "name": "Incident Response",
        "description": "Structured incident workflows, war room, and post-mortems.",
        "category": "security",
        "minTier": "Pro",
        "permission": "view:incident_response",
    },
    "attack_path": {
        "name": "Attack Path Analysis",
        "description": "Graph-based analysis of exploitable paths through your environment.",
        "category": "security",
        "minTier": "Enterprise",
        "permission": "view:attack_path",
    },

    # ── Compliance Bundle ────────────────────────────────────────────────────
    "compliance": {
        "name": "Compliance Frameworks",
        "description": "Map controls to SOC 2, ISO 27001, PCI DSS, HIPAA, and more.",
        "category": "compliance",
        "minTier": "Pro",
        "permission": "view:compliance",
    },
    "risk_register": {
        "name": "Risk Register",
        "description": "Track, score, and manage enterprise risks.",
        "category": "compliance",
        "minTier": "Pro",
        "permission": "view:risk_register",
    },
    "vendor_management": {
        "name": "Vendor Management",
        "description": "Third-party risk assessments and vendor lifecycle tracking.",
        "category": "compliance",
        "minTier": "Pro",
        "permission": "view:vendor_management",
    },
    "custom_frameworks": {
        "name": "Custom Compliance Frameworks",
        "description": "Build bespoke compliance frameworks for internal policies.",
        "category": "compliance",
        "minTier": "Enterprise",
        "permission": "view:custom_frameworks",
    },
    "cissp_oracle": {
        "name": "CISSP Oracle",
        "description": "AI-guided CISSP knowledge base and exam preparation.",
        "category": "compliance",
        "minTier": "Enterprise",
        "permission": "view:cissp_oracle",
    },

    # ── Patching & Software Bundle ───────────────────────────────────────────
    "patching": {
        "name": "Patch Management",
        "description": "Automated OS and application patch deployment and tracking.",
        "category": "patching",
        "minTier": "Pro",
        "permission": "view:patching",
    },
    "software_updates": {
        "name": "Software Updates",
        "description": "Manage software versions and update policies across the fleet.",
        "category": "patching",
        "minTier": "Pro",
        "permission": "view:software_updates",
    },
    "software_deployment": {
        "name": "Software Deployment",
        "description": "Push, rollback, and track software deployments at scale.",
        "category": "patching",
        "minTier": "Pro",
        "permission": "view:software_deployment",
    },

    # ── DevSecOps Bundle ─────────────────────────────────────────────────────
    "devsecops": {
        "name": "DevSecOps",
        "description": "Integrate security into CI/CD pipelines and development workflows.",
        "category": "devsecops",
        "minTier": "Pro",
        "permission": "view:devsecops",
    },
    "supply_chain": {
        "name": "Supply Chain Security",
        "description": "Monitor and secure software supply chain dependencies.",
        "category": "devsecops",
        "minTier": "Pro",
        "permission": "view:supply_chain",
    },
    "sbom": {
        "name": "SBOM Management",
        "description": "Generate and manage software bills of materials.",
        "category": "devsecops",
        "minTier": "Pro",
        "permission": "view:sbom",
    },
    "sast": {
        "name": "Static Application Security Testing",
        "description": "Scan source code for vulnerabilities before deployment.",
        "category": "devsecops",
        "minTier": "Pro",
        "permission": "view:sast",
    },
    "dast": {
        "name": "Dynamic Application Security Testing",
        "description": "Test running applications for exploitable vulnerabilities.",
        "category": "devsecops",
        "minTier": "Pro",
        "permission": "view:dast",
    },

    # ── Operations Bundle ────────────────────────────────────────────────────
    "playbooks": {
        "name": "Playbooks & Automation",
        "description": "Build and run automated response playbooks.",
        "category": "operations",
        "minTier": "Pro",
        "permission": "view:playbooks",
    },
    "automation": {
        "name": "Automation Policies",
        "description": "Policy-as-code engine for automated enforcement actions.",
        "category": "operations",
        "minTier": "Pro",
        "permission": "view:automation",
    },
    "remote_access": {
        "name": "Remote Access",
        "description": "Secure remote terminal and desktop access to managed endpoints.",
        "category": "operations",
        "minTier": "Pro",
        "permission": "view:remote_access",
    },
    "swarm": {
        "name": "Agent Swarm",
        "description": "Orchestrate multi-agent swarms for parallel task execution.",
        "category": "operations",
        "minTier": "Pro",
        "permission": "view:swarm",
    },
    "reporting": {
        "name": "Reporting",
        "description": "Scheduled and on-demand reports with export to PDF/Excel.",
        "category": "operations",
        "minTier": "Pro",
        "permission": "view:reporting",
    },

    # ── AI / ML Bundle ───────────────────────────────────────────────────────
    "ai_governance": {
        "name": "AI Governance",
        "description": "Track, audit, and govern AI/ML models in production.",
        "category": "ai_ml",
        "minTier": "Enterprise",
        "permission": "view:ai_governance",
    },
    "ai_remediation": {
        "name": "AI-Powered Remediation",
        "description": "Autonomous remediation suggestions powered by LLMs.",
        "category": "ai_ml",
        "minTier": "Pro",
        "permission": "view:ai_remediation",
    },
    "mlops": {
        "name": "MLOps",
        "description": "Model lifecycle management, versioning, and deployment.",
        "category": "ai_ml",
        "minTier": "Enterprise",
        "permission": "view:mlops",
    },
    "llmops": {
        "name": "LLMOps",
        "description": "Manage and monitor large language model deployments.",
        "category": "ai_ml",
        "minTier": "Enterprise",
        "permission": "view:llmops",
    },
    "automl": {
        "name": "AutoML",
        "description": "Automated machine learning pipeline construction and training.",
        "category": "ai_ml",
        "minTier": "Enterprise",
        "permission": "view:automl",
    },

    # ── Enterprise Bundle ────────────────────────────────────────────────────
    "finops": {
        "name": "FinOps",
        "description": "Cloud cost visibility, budgeting, and optimisation.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:finops",
    },
    "hadr": {
        "name": "High Availability & Disaster Recovery",
        "description": "Backup, failover, and recovery orchestration.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:hadr",
    },
    "chaos_engineering": {
        "name": "Chaos Engineering",
        "description": "Controlled fault injection to test system resilience.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:chaos_engineering",
    },
    "cxo_dashboard": {
        "name": "CXO Dashboard",
        "description": "Executive-level KPI board with business-aligned metrics.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:cxo_dashboard",
    },
    "digital_twin": {
        "name": "Digital Twin",
        "description": "Virtual replica of your infrastructure for simulation and analysis.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:digital_twin",
    },
    "zero_trust": {
        "name": "Zero Trust",
        "description": "Enforce zero-trust network access and identity verification.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:zero_trust",
    },
    "data_lake": {
        "name": "Data Lake & Warehouse",
        "description": "Centralised data lake with ETL pipelines and warehouse connectors.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:data_lake",
    },
    "advanced_bi": {
        "name": "Advanced BI",
        "description": "Custom dashboards and multi-dimensional analytics.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:advanced_bi",
    },
    "sustainability": {
        "name": "Sustainability",
        "description": "Track and report on carbon footprint and energy usage.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:sustainability",
    },
    "goal_system": {
        "name": "Goal System",
        "description": "OKR and strategic goal tracking aligned to security posture.",
        "category": "enterprise",
        "minTier": "Enterprise",
        "permission": "view:goal_system",
    },
}
