"""Compliance control definitions: PCI DSS, NIST, HIPAA, GDPR, FedRAMP, HITRUST, CMMC, CSA."""

from seed_compliance_controls_a import ctrl


# ── PCI DSS v4.0 – full 12 requirements ──────────────────────────────────────
PCI_CONTROLS = [
    ctrl("PCI-1.1","Firewall Configuration Standards","Establish and implement firewall configuration standards including formal review every six months.","Network Security","Implemented"),
    ctrl("PCI-1.2","Restrict Inbound/Outbound Traffic","Restrict connections to systems in the cardholder data environment.","Network Security","Implemented"),
    ctrl("PCI-1.3","Network Access Controls","Prohibit direct public access between the Internet and any component in the CDE.","Network Security","Implemented"),
    ctrl("PCI-2.1","Vendor-Supplied Defaults","Always change vendor-supplied defaults and remove or disable unnecessary default accounts before installing a system on the network.","System Configuration","Implemented"),
    ctrl("PCI-2.2","Configuration Standards","Develop configuration standards for all system components that address all known security vulnerabilities.","System Configuration","In Progress"),
    ctrl("PCI-2.3","Encrypt Non-Console Admin Access","Encrypt all non-console administrative access using strong cryptography.","System Configuration","Implemented"),
    ctrl("PCI-3.1","Cardholder Data Retention Policy","Keep cardholder data storage to a minimum by implementing a data retention and disposal policy.","Cardholder Data Protection","Implemented"),
    ctrl("PCI-3.2","Sensitive Authentication Data","Do not store sensitive authentication data after authorisation.","Cardholder Data Protection","Implemented"),
    ctrl("PCI-3.4","Render PAN Unreadable","Render PAN unreadable anywhere it is stored using strong cryptography.","Cardholder Data Protection","Implemented"),
    ctrl("PCI-3.5","Cryptographic Key Management","Document and implement procedures to protect keys used to secure stored cardholder data.","Cardholder Data Protection","Implemented"),
    ctrl("PCI-4.1","Encrypt Transmission over Open Networks","Use strong cryptography and security protocols to safeguard sensitive cardholder data during transmission over open, public networks.","Transmission Protection","Implemented"),
    ctrl("PCI-4.2","Never Send Unprotected PANs","Never send unprotected PANs by end-user messaging technologies.","Transmission Protection","Implemented"),
    ctrl("PCI-5.1","Anti-Malware Deployment","Deploy anti-malware software on all systems commonly affected by malicious software.","Malware Protection","Implemented"),
    ctrl("PCI-5.2","Anti-Malware Updates","Ensure that all anti-malware mechanisms are maintained and capable of generating audit logs.","Malware Protection","Implemented"),
    ctrl("PCI-5.3","Anti-Malware Actively Running","Ensure that anti-malware mechanisms are actively running and cannot be disabled or altered by users.","Malware Protection","Implemented"),
    ctrl("PCI-6.1","Vulnerability Identification Process","Establish a process to identify security vulnerabilities using reputable outside sources for security vulnerability information.","Vulnerability Management","Implemented"),
    ctrl("PCI-6.2","System Protection from Known Vulnerabilities","Protect all system components from known vulnerabilities by installing applicable security patches.","Vulnerability Management","In Progress"),
    ctrl("PCI-6.3","Secure Software Development","Develop internal and external software applications securely including training for developers.","Secure Development","Implemented"),
    ctrl("PCI-6.4","Address Common Vulnerabilities","Address common coding vulnerabilities in software development processes.","Secure Development","Implemented"),
    ctrl("PCI-6.5","Web Application Firewall","For public-facing web applications, address new threats and vulnerabilities on an ongoing basis.","Secure Development","In Progress"),
    ctrl("PCI-7.1","Restrict Access by Need to Know","Limit access to system components and cardholder data to only those individuals whose job requires such access.","Access Control","Implemented"),
    ctrl("PCI-7.2","Access Control System","Establish an access control system for systems components that restricts access based on a user's need to know.","Access Control","Implemented"),
    ctrl("PCI-8.1","User Identification Management","Define and implement policies and procedures to ensure proper user identification management.","Identity and Authentication","Implemented"),
    ctrl("PCI-8.2","Authentication Management","In addition to assigning a unique ID, ensure proper user-authentication management by employing strong authentication.","Identity and Authentication","Implemented"),
    ctrl("PCI-8.3","Secure Individual Non-Consumer User Authentication","Secure individual non-consumer users and administrators on all system components.","Identity and Authentication","Implemented"),
    ctrl("PCI-8.4","MFA for Remote Access","Implement multi-factor authentication for all remote network access originating from outside the entity's network.","Identity and Authentication","Implemented"),
    ctrl("PCI-9.1","Physical Access Controls","Use appropriate facility entry controls to limit and monitor physical access to systems in the cardholder data environment.","Physical Security","In Progress"),
    ctrl("PCI-9.2","Visitor Access","Develop procedures to distinguish between onsite personnel and visitors.","Physical Security","Implemented"),
    ctrl("PCI-9.5","Media Protection","Physically secure all media.","Physical Security","Implemented"),
    ctrl("PCI-9.6","Media Distribution Controls","Maintain strict control over the internal or external distribution of any kind of media.","Physical Security","Implemented"),
    ctrl("PCI-10.1","Implement Audit Trails","Implement audit trails to link all access to system components to each individual user.","Logging and Monitoring","Implemented"),
    ctrl("PCI-10.2","Automated Audit Trails","Implement automated audit trails for all system components.","Logging and Monitoring","Implemented"),
    ctrl("PCI-10.3","Protect Audit Trails","Protect audit trails from destruction and unauthorised modifications.","Logging and Monitoring","Implemented"),
    ctrl("PCI-10.5","Retain Audit Trail History","Retain audit trail history for at least one year.","Logging and Monitoring","Implemented"),
    ctrl("PCI-11.1","Wireless Access Points","Test for the presence of wireless access points and detect and identify all authorized and unauthorized wireless access points on a quarterly basis.","Security Testing","Implemented"),
    ctrl("PCI-11.2","Vulnerability Scanning","Run internal and external network vulnerability scans at least quarterly and after any significant change.","Security Testing","At Risk"),
    ctrl("PCI-11.3","Penetration Testing","Implement a methodology for penetration testing including network-layer and application-layer penetration tests.","Security Testing","Not Implemented"),
    ctrl("PCI-11.4","IDS/IPS","Use intrusion-detection and/or intrusion-prevention techniques to detect and/or prevent intrusions into the network.","Security Testing","Implemented"),
    ctrl("PCI-12.1","Information Security Policy","Establish, publish, maintain, and disseminate a security policy.","Security Policy","Implemented"),
    ctrl("PCI-12.3","Risk Assessment","Perform a formal risk assessment at least annually.","Security Policy","In Progress"),
    ctrl("PCI-12.4","Security Responsibilities","Ensure that the security policy and procedures clearly define information security responsibilities for all personnel.","Security Policy","Implemented"),
    ctrl("PCI-12.8","Third-Party Service Providers","Maintain and implement policies and procedures to manage service providers with whom cardholder data is shared.","Third Party","In Progress"),
    ctrl("PCI-12.10","Incident Response Plan","Implement an incident response plan and be prepared to respond immediately to a system breach.","Incident Response","Implemented"),
]

# ── NIST CSF v2.0 ─────────────────────────────────────────────────────────────
NIST_CONTROLS = [
    # Govern
    ctrl("GV.OC-01","Organizational Mission","The organisational mission is understood and informs cybersecurity risk management.","Govern","Implemented"),
    ctrl("GV.OC-02","Internal and External Stakeholders","Internal and external stakeholders are understood, and their needs are reflected in cybersecurity risk management.","Govern","Implemented"),
    ctrl("GV.OC-03","Legal and Regulatory Requirements","Legal, regulatory, and contractual requirements regarding cybersecurity are understood and managed.","Govern","Implemented"),
    ctrl("GV.RM-01","Risk Management Strategy","Risk management objectives are established and agreed to by organizational stakeholders.","Govern","Implemented"),
    ctrl("GV.RM-02","Risk Appetite and Tolerance","Risk appetite and risk tolerance statements are established, communicated, and maintained.","Govern","In Progress"),
    ctrl("GV.SC-01","Cybersecurity Supply Chain Risk Management","A cybersecurity supply chain risk management program, strategy, objectives, policies, and processes are established and agreed to by organizational stakeholders.","Govern","In Progress"),
    ctrl("GV.PO-01","Policy","Organizational cybersecurity policy is established, communicated, and enforced.","Govern","Implemented"),
    ctrl("GV.RR-01","Roles and Responsibilities","Organizational leadership is responsible and accountable for cybersecurity risk and fosters a culture that is risk-aware, ethical, and continually improving.","Govern","Implemented"),
    # Identify
    ctrl("ID.AM-01","Asset Inventory – Physical","Inventories of hardware managed by the organisation are maintained.","Identify","Implemented"),
    ctrl("ID.AM-02","Asset Inventory – Software","Inventories of software, services, and systems managed by the organisation are maintained.","Identify","Implemented"),
    ctrl("ID.AM-03","Network Representation","Representations of the organisation's authorised network communication and internal and external network data flows are maintained.","Identify","In Progress"),
    ctrl("ID.AM-07","Data Classification","Inventories of data and corresponding metadata for designated data types are maintained.","Identify","In Progress"),
    ctrl("ID.RA-01","Vulnerability Identification","Vulnerabilities in assets are identified, validated, and recorded.","Identify","At Risk"),
    ctrl("ID.RA-02","Threat Intelligence","Cyber threat intelligence is received from information sharing forums and sources.","Identify","Implemented"),
    ctrl("ID.RA-03","Threats Identified","Internal and external threats to the organisation are identified and recorded.","Identify","Implemented"),
    ctrl("ID.RA-05","Threats, Vulnerabilities, Likelihoods, and Impacts","Threats, vulnerabilities, likelihoods, and impacts are used to understand inherent risk and inform prioritisation.","Identify","In Progress"),
    ctrl("ID.IM-01","Improvements Identified","Improvements are identified from evaluations.","Identify","In Progress"),
    # Protect
    ctrl("PR.AA-01","Identity and Credential Management","Identities and credentials for authorised users, services, and hardware are managed by the organisation.","Protect","Implemented"),
    ctrl("PR.AA-02","Least Privilege","Identities are proofed and bound to credentials based on the context of interactions.","Protect","Implemented"),
    ctrl("PR.AA-03","User Authentication","Users, services, and hardware are authenticated.","Protect","Implemented"),
    ctrl("PR.AA-04","MFA","Identity assertions are protected, conveyed, and verified.","Protect","Implemented"),
    ctrl("PR.AA-05","Access Permissions and Authorizations","Access permissions, entitlements, and authorizations are defined in a policy, managed, enforced, and reviewed.","Protect","Implemented"),
    ctrl("PR.AT-01","Security Awareness Training","Personnel are provided with awareness and training so that they possess the knowledge and skills to perform general tasks with cybersecurity risks in mind.","Protect","Implemented"),
    ctrl("PR.DS-01","Data at Rest","The confidentiality, integrity, and availability of data-at-rest are protected.","Protect","Implemented"),
    ctrl("PR.DS-02","Data in Transit","The confidentiality, integrity, and availability of data-in-transit are protected.","Protect","Implemented"),
    ctrl("PR.DS-10","Data in Use","The confidentiality, integrity, and availability of data-in-use are protected.","Protect","In Progress"),
    ctrl("PR.IR-01","Network Integrity","Networks and environments are protected from unauthorised logical access and usage.","Protect","Implemented"),
    ctrl("PR.PS-01","Configuration Management","Configuration management practices are established and applied.","Protect","In Progress"),
    ctrl("PR.PS-02","Software Management","Software is maintained, replaced, and removed commensurate with risk.","Protect","Implemented"),
    # Detect
    ctrl("DE.AE-02","Anomalies and Events","Potentially adverse events are analysed to better understand associated activities.","Detect","Implemented"),
    ctrl("DE.AE-03","Event Correlation","Information is correlated from multiple sources.","Detect","Implemented"),
    ctrl("DE.AE-06","Information Sharing","Information on adverse events is provided to authorised staff and tools.","Detect","In Progress"),
    ctrl("DE.AE-07","Cyber Intelligence","Cyber threat intelligence and other contextual information are integrated into the analysis.","Detect","Implemented"),
    ctrl("DE.CM-01","Networks Monitored","Networks and network services are monitored to find potentially adverse events.","Detect","Implemented"),
    ctrl("DE.CM-02","Physical Environment Monitored","The physical environment is monitored to find potentially adverse events.","Detect","In Progress"),
    ctrl("DE.CM-03","Personnel Activity Monitored","Personnel activity and technology usage are monitored to find potentially adverse events.","Detect","Implemented"),
    ctrl("DE.CM-06","External Service Provider Activity","External service provider activities and services are monitored to find potentially adverse events.","Detect","In Progress"),
    # Respond
    ctrl("RS.MA-01","Incident Management","The incident response plan is executed in coordination with relevant third parties once an incident is declared.","Respond","Implemented"),
    ctrl("RS.AN-03","Analysis","Analysis is performed to establish what has taken place during an incident and the root cause of the incident.","Respond","In Progress"),
    ctrl("RS.AN-06","Actions Documented","Actions performed during an investigation are recorded.","Respond","Implemented"),
    ctrl("RS.CO-02","Internal Reporting","Internal stakeholders are notified of incidents.","Respond","Implemented"),
    ctrl("RS.CO-03","Information Sharing","Information is shared with designated internal and external stakeholders.","Respond","In Progress"),
    ctrl("RS.MI-01","Incidents Contained","Incidents are contained.","Respond","Implemented"),
    ctrl("RS.MI-02","Incidents Eradicated","Incidents are eradicated.","Respond","Implemented"),
    # Recover
    ctrl("RC.RP-01","Recovery Plan Executed","The recovery portion of the incident response plan is executed once initiated from the incident response process.","Recover","Implemented"),
    ctrl("RC.RP-03","Recovery Verified","The integrity of backups and other restoration assets is verified before using them for restoration.","Recover","In Progress"),
    ctrl("RC.CO-03","Recovery Communication","Recovery activities and progress in restoring operational capabilities are communicated to designated stakeholders.","Recover","In Progress"),
    ctrl("RC.IM-01","Recovery Improvements","Recovery plans incorporate lessons learned.","Recover","Not Implemented"),
]

# ── HIPAA Security Rule – complete safeguards ─────────────────────────────────
HIPAA_CONTROLS = [
    ctrl("164.308(a)(1)(i)","Security Management Process","Implement policies and procedures to prevent, detect, contain, and correct security violations.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(1)(ii)(A)","Risk Analysis","Conduct an accurate and thorough assessment of potential risks and vulnerabilities.","Administrative Safeguard","At Risk"),
    ctrl("164.308(a)(1)(ii)(B)","Risk Management","Implement security measures sufficient to reduce risks and vulnerabilities to a reasonable and appropriate level.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(1)(ii)(C)","Sanction Policy","Apply appropriate sanctions against workforce members who fail to comply with security policies.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(1)(ii)(D)","Information System Activity Review","Implement procedures to regularly review records of information system activity.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(2)","Assigned Security Responsibility","Identify the security official responsible for development and implementation of policies.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(3)(i)","Workforce Security","Implement policies to ensure all workforce members have appropriate access to ePHI.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(3)(ii)(A)","Authorisation and/or Supervision","Implement procedures for the authorisation and/or supervision of workforce members.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(3)(ii)(B)","Workforce Clearance Procedure","Implement procedures to determine that the access of a workforce member to ePHI is appropriate.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(3)(ii)(C)","Termination Procedures","Implement procedures for terminating access to ePHI when employment ends.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(4)(i)","Information Access Management","Implement policies for authorising access to ePHI.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(4)(ii)(A)","Isolating Health Care Clearinghouse Functions","Create appropriate barriers between clearinghouse and other business units.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(4)(ii)(B)","Access Authorisation","Implement policies for granting access to ePHI.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(4)(ii)(C)","Access Establishment and Modification","Implement policies for establishing, documenting, reviewing, and modifying user access rights.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(5)(i)","Security Awareness and Training","Implement a security awareness and training program for all workforce members.","Administrative Safeguard","In Progress"),
    ctrl("164.308(a)(5)(ii)(A)","Security Reminders","Send periodic security updates.","Administrative Safeguard","In Progress"),
    ctrl("164.308(a)(5)(ii)(B)","Protection from Malicious Software","Procedures for guarding against, detecting, and reporting malicious software.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(5)(ii)(C)","Log-In Monitoring","Procedures for monitoring log-in attempts and reporting discrepancies.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(5)(ii)(D)","Password Management","Procedures for creating, changing, and safeguarding passwords.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(6)(i)","Security Incident Procedures","Implement policies for addressing security incidents.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(6)(ii)","Response and Reporting","Identify and respond to suspected security incidents; mitigate effects; document incidents and outcomes.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(7)(i)","Contingency Plan","Establish policies for responding to an emergency.","Administrative Safeguard","Not Implemented"),
    ctrl("164.308(a)(7)(ii)(A)","Data Backup Plan","Establish and implement procedures to create and maintain retrievable exact copies of ePHI.","Administrative Safeguard","Implemented"),
    ctrl("164.308(a)(7)(ii)(B)","Disaster Recovery Plan","Establish procedures to restore any loss of data.","Administrative Safeguard","In Progress"),
    ctrl("164.308(a)(7)(ii)(C)","Emergency Mode Operation Plan","Establish procedures to enable continuation of critical business processes during emergencies.","Administrative Safeguard","Not Implemented"),
    ctrl("164.308(a)(7)(ii)(D)","Testing and Revision Procedures","Implement procedures for periodic testing and revision of contingency plans.","Administrative Safeguard","Not Implemented"),
    ctrl("164.308(a)(8)","Evaluation","Perform a periodic technical and nontechnical evaluation.","Administrative Safeguard","Not Implemented"),
    ctrl("164.308(b)(1)","Business Associate Contracts","A covered entity may permit a business associate to create, receive, maintain, or transmit ePHI only with satisfactory assurances.","Administrative Safeguard","Implemented"),
    ctrl("164.310(a)(1)","Facility Access Controls","Limit physical access to electronic information systems and the facility.","Physical Safeguard","Implemented"),
    ctrl("164.310(a)(2)(i)","Contingency Operations","Establish physical safeguards for all workstations that access ePHI during a disaster recovery.","Physical Safeguard","In Progress"),
    ctrl("164.310(a)(2)(ii)","Facility Security Plan","Implement policies and procedures to safeguard the facility and equipment from unauthorized physical access.","Physical Safeguard","Implemented"),
    ctrl("164.310(a)(2)(iii)","Access Control and Validation Procedures","Implement procedures to control and validate access to facilities.","Physical Safeguard","Implemented"),
    ctrl("164.310(b)","Workstation Use","Implement policies specifying the proper functions to be performed on workstations.","Physical Safeguard","Implemented"),
    ctrl("164.310(c)","Workstation Security","Implement physical safeguards for all workstations that access ePHI.","Physical Safeguard","Implemented"),
    ctrl("164.310(d)(1)","Device and Media Controls","Implement policies governing receipt and removal of hardware and electronic media.","Physical Safeguard","Implemented"),
    ctrl("164.310(d)(2)(i)","Disposal","Implement policies for the final disposal of ePHI and/or hardware/electronic media.","Physical Safeguard","Implemented"),
    ctrl("164.310(d)(2)(ii)","Media Re-Use","Implement procedures for removal of ePHI from electronic media before re-use.","Physical Safeguard","Implemented"),
    ctrl("164.312(a)(1)","Access Control","Implement technical policies for electronic information systems to allow only authorised persons.","Technical Safeguard","Implemented"),
    ctrl("164.312(a)(2)(i)","Unique User Identification","Assign unique names/numbers for identifying and tracking user identity.","Technical Safeguard","Implemented"),
    ctrl("164.312(a)(2)(ii)","Emergency Access Procedure","Establish procedures for obtaining necessary ePHI during an emergency.","Technical Safeguard","Implemented"),
    ctrl("164.312(a)(2)(iii)","Automatic Logoff","Implement electronic procedures that terminate an electronic session after a period of inactivity.","Technical Safeguard","Implemented"),
    ctrl("164.312(a)(2)(iv)","Encryption and Decryption","Implement a mechanism to encrypt and decrypt ePHI.","Technical Safeguard","Implemented"),
    ctrl("164.312(b)","Audit Controls","Implement hardware, software, and/or procedural mechanisms to record and examine ePHI activity.","Technical Safeguard","Implemented"),
    ctrl("164.312(c)(1)","Integrity","Implement policies to protect ePHI from improper alteration or destruction.","Technical Safeguard","Implemented"),
    ctrl("164.312(c)(2)","Mechanism to Authenticate ePHI","Implement electronic mechanisms to corroborate that ePHI has not been altered or destroyed.","Technical Safeguard","Implemented"),
    ctrl("164.312(d)","Person or Entity Authentication","Implement procedures to verify identity of persons seeking access.","Technical Safeguard","Implemented"),
    ctrl("164.312(e)(1)","Transmission Security","Implement technical security measures to guard against unauthorised access to ePHI being transmitted.","Technical Safeguard","Implemented"),
    ctrl("164.312(e)(2)(i)","Integrity Controls","Implement security measures to ensure electronically transmitted ePHI is not improperly modified.","Technical Safeguard","Implemented"),
    ctrl("164.312(e)(2)(ii)","Encryption","Implement a mechanism to encrypt ePHI in transit.","Technical Safeguard","Implemented"),
]

# ── GDPR – complete articles ───────────────────────────────────────────────────
GDPR_CONTROLS = [
    ctrl("Art.5(1)(a)","Lawfulness, Fairness and Transparency","Personal data shall be processed lawfully, fairly and in a transparent manner in relation to the data subject.","Principles","In Progress"),
    ctrl("Art.5(1)(b)","Purpose Limitation","Personal data shall be collected for specified, explicit and legitimate purposes and not further processed in a manner incompatible with those purposes.","Principles","In Progress"),
    ctrl("Art.5(1)(c)","Data Minimisation","Personal data shall be adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed.","Principles","Not Implemented"),
    ctrl("Art.5(1)(d)","Accuracy","Personal data shall be accurate and, where necessary, kept up to date.","Principles","In Progress"),
    ctrl("Art.5(1)(e)","Storage Limitation","Personal data shall be kept in a form which permits identification of data subjects for no longer than is necessary.","Principles","Not Implemented"),
    ctrl("Art.5(1)(f)","Integrity and Confidentiality","Personal data shall be processed in a manner that ensures appropriate security.","Principles","Implemented"),
    ctrl("Art.6","Lawful Basis for Processing","Processing shall be lawful only if at least one of the lawful bases applies.","Lawful Basis","Implemented"),
    ctrl("Art.7","Conditions for Consent","Where processing is based on consent, the controller shall be able to demonstrate that the data subject has consented.","Consent","In Progress"),
    ctrl("Art.9","Processing of Special Categories","Processing of special categories of personal data shall be prohibited unless specific conditions are met.","Special Categories","Not Implemented"),
    ctrl("Art.12","Transparent Information to Data Subject","The controller shall take appropriate measures to provide information to the data subject in a concise, transparent, intelligible and easily accessible form.","Data Subject Rights","Implemented"),
    ctrl("Art.13","Information to be Provided where Data Collected from Data Subject","Where personal data are collected from the data subject, the controller shall provide information at time of collection.","Data Subject Rights","Implemented"),
    ctrl("Art.14","Information where Data Not Obtained from Data Subject","Where personal data have not been obtained from the data subject, the controller shall provide information within one month.","Data Subject Rights","In Progress"),
    ctrl("Art.15","Right of Access","The data subject shall have the right to obtain confirmation as to whether personal data are being processed.","Data Subject Rights","Implemented"),
    ctrl("Art.16","Right to Rectification","The data subject shall have the right to obtain without undue delay the rectification of inaccurate personal data.","Data Subject Rights","Implemented"),
    ctrl("Art.17","Right to Erasure","The data subject shall have the right to obtain the erasure of personal data without undue delay.","Data Subject Rights","In Progress"),
    ctrl("Art.18","Right to Restriction of Processing","The data subject shall have the right to obtain from the controller restriction of processing.","Data Subject Rights","In Progress"),
    ctrl("Art.19","Notification Obligation","The controller shall communicate any rectification or erasure of personal data or restriction of processing to each recipient.","Data Subject Rights","In Progress"),
    ctrl("Art.20","Right to Data Portability","The data subject shall have the right to receive personal data in a structured, commonly used and machine-readable format.","Data Subject Rights","Not Implemented"),
    ctrl("Art.21","Right to Object","The data subject shall have the right to object to processing of personal data.","Data Subject Rights","In Progress"),
    ctrl("Art.22","Automated Individual Decision-Making","The data subject shall have the right not to be subject to a decision based solely on automated processing.","Data Subject Rights","Not Implemented"),
    ctrl("Art.24","Responsibility of the Controller","The controller shall implement appropriate technical and organisational measures to ensure processing is performed in accordance with this Regulation.","Controller Obligations","Implemented"),
    ctrl("Art.25","Data Protection by Design and by Default","The controller shall implement appropriate technical and organisational measures for ensuring that only necessary personal data is processed.","Controller Obligations","In Progress"),
    ctrl("Art.26","Joint Controllers","Where two or more controllers jointly determine the purposes and means of processing, they shall be joint controllers.","Controller Obligations","Not Implemented"),
    ctrl("Art.28","Processor","The controller shall use only processors providing sufficient guarantees to implement appropriate technical and organisational measures.","Processor Obligations","In Progress"),
    ctrl("Art.29","Processing under Controller or Processor Authority","The processor and any person acting under the authority of the controller or the processor shall process only on instructions from the controller.","Processor Obligations","Implemented"),
    ctrl("Art.30","Records of Processing Activities","Each controller and each processor shall maintain a record of processing activities.","Controller Obligations","In Progress"),
    ctrl("Art.32(1)(a)","Encryption of Personal Data","Implement pseudonymisation and encryption of personal data.","Security Measures","Implemented"),
    ctrl("Art.32(1)(b)","Ongoing Confidentiality, Integrity, Availability","Ensure the ongoing confidentiality, integrity, availability and resilience of processing systems.","Security Measures","Implemented"),
    ctrl("Art.32(1)(c)","Restore Availability and Access","Implement ability to restore availability and access to personal data in a timely manner.","Security Measures","In Progress"),
    ctrl("Art.32(1)(d)","Regular Testing and Evaluation","Implement a process for regularly testing, assessing and evaluating the effectiveness of technical measures.","Security Measures","At Risk"),
    ctrl("Art.33","Notification of a Personal Data Breach to Supervisory Authority","In the case of a personal data breach, the controller shall without undue delay notify the supervisory authority.","Breach Notification","Implemented"),
    ctrl("Art.34","Communication of a Personal Data Breach to the Data Subject","Where a personal data breach is likely to result in a high risk, the controller shall communicate the breach to the data subject without undue delay.","Breach Notification","Implemented"),
    ctrl("Art.35","Data Protection Impact Assessment","Where processing is likely to result in a high risk to rights and freedoms of natural persons, the controller shall carry out a DPIA.","Risk Management","Not Implemented"),
    ctrl("Art.37","Designation of the Data Protection Officer","The controller and processor shall designate a DPO where required.","Governance","In Progress"),
    ctrl("Art.44","General Principle for Transfers to Third Countries","Any transfer of personal data to a third country shall take place only if conditions are complied with.","International Transfers","Implemented"),
    ctrl("Art.46","Transfers Subject to Appropriate Safeguards","In the absence of an adequacy decision, transfer may take place only if the controller has provided appropriate safeguards.","International Transfers","In Progress"),
]

# ── FedRAMP Moderate – expanded ────────────────────────────────────────────────
FEDRAMP_CONTROLS = [
    ctrl("fedramp-AC-2","Account Management","Manage information system accounts including establishing, activating, modifying, reviewing, disabling, and removing accounts.","Access Control","Implemented"),
    ctrl("fedramp-AC-3","Access Enforcement","Enforce approved authorizations for logical access to the information system.","Access Control","At Risk"),
    ctrl("fedramp-AC-6","Least Privilege","Employ the principle of least privilege, allowing only authorized accesses required for accomplishment of assigned tasks.","Access Control","In Progress"),
    ctrl("fedramp-AC-17","Remote Access","Establish and document usage restrictions, configuration/connection requirements, and implement controls for remote access.","Access Control","Implemented"),
    ctrl("fedramp-AU-2","Audit Events","Determine the events the information system must be capable of auditing.","Audit and Accountability","Implemented"),
    ctrl("fedramp-AU-3","Content of Audit Records","Produce audit records containing information that establishes what type of event occurred.","Audit and Accountability","Implemented"),
    ctrl("fedramp-AU-6","Audit Review, Analysis, and Reporting","Review and analyze information system audit records for indications of inappropriate activity.","Audit and Accountability","Implemented"),
    ctrl("fedramp-AU-12","Audit Generation","Provide audit record generation capability for the auditable events defined in AU-2 and allow designated organizational personnel to select which events are to be audited.","Audit and Accountability","Implemented"),
    ctrl("fedramp-CA-7","Continuous Monitoring","Develop a continuous monitoring strategy and implement a continuous monitoring program.","Assessment, Authorisation and Monitoring","In Progress"),
    ctrl("fedramp-CM-6","Configuration Settings","Establish and document configuration settings for information technology products employed within the information system.","Configuration Management","In Progress"),
    ctrl("fedramp-CM-7","Least Functionality","Configure the information system to provide only essential capabilities.","Configuration Management","Implemented"),
    ctrl("fedramp-CM-8","Information System Component Inventory","Develop and document an inventory of information system components.","Configuration Management","Implemented"),
    ctrl("fedramp-IA-2","Identification and Authentication (Organisational Users)","Uniquely identify and authenticate organizational users.","Identification and Authentication","Implemented"),
    ctrl("fedramp-IA-5","Authenticator Management","Manage information system authenticators including establishing initial authenticator content.","Identification and Authentication","Implemented"),
    ctrl("fedramp-IR-4","Incident Handling","Implement an incident handling capability for security incidents.","Incident Response","Implemented"),
    ctrl("fedramp-IR-6","Incident Reporting","Require personnel to report suspected security incidents to the organizational incident response capability.","Incident Response","Implemented"),
    ctrl("fedramp-RA-3","Risk Assessment","Conduct risk assessments of the information system and its operating environment.","Risk Assessment","In Progress"),
    ctrl("fedramp-RA-5","Vulnerability Monitoring and Scanning","Monitor and scan for vulnerabilities in the information system.","Risk Assessment","At Risk"),
    ctrl("fedramp-SC-7","Boundary Protection","Monitor and control communications at the external boundary of the information system.","System and Communications Protection","Implemented"),
    ctrl("fedramp-SC-28","Protection of Information at Rest","Protect the confidentiality and integrity of information at rest.","System and Communications Protection","Implemented"),
    ctrl("fedramp-SI-2","Flaw Remediation","Identify, report, and correct information system flaws.","System and Information Integrity","In Progress"),
    ctrl("fedramp-SI-3","Malicious Code Protection","Implement malicious code protection at information system entry and exit points.","System and Information Integrity","Implemented"),
    ctrl("fedramp-SI-4","Information System Monitoring","Monitor the information system to detect attacks and indicators of potential attacks.","System and Information Integrity","Implemented"),
    ctrl("fedramp-SA-9","External Information System Services","Require that providers of external information system services comply with organizational information security requirements.","System and Services Acquisition","In Progress"),
]

# ── HITRUST CSF v11 – expanded ─────────────────────────────────────────────────
HITRUST_CONTROLS = [
    ctrl("hitrust-01.a","Access Control Policy","An access control policy is established, documented and reviewed based on business and information security requirements.","Access Control","Implemented"),
    ctrl("hitrust-01.b","User Registration","A formal user registration and de-registration procedure is implemented.","Access Control","Implemented"),
    ctrl("hitrust-01.c","Privilege Management","Allocation and use of privileges is restricted and controlled.","Access Control","In Progress"),
    ctrl("hitrust-01.d","User Password Management","Passwords are controlled through a formal management process.","Access Control","Implemented"),
    ctrl("hitrust-01.e","Review of User Access Rights","Management reviews users' access rights at regular intervals.","Access Control","In Progress"),
    ctrl("hitrust-06.a","Anti-Malware Controls","Controls against malicious code are implemented.","Endpoint Protection","Implemented"),
    ctrl("hitrust-06.b","Patch Management","Technical vulnerabilities are managed by evaluating and patching systems.","Endpoint Protection","In Progress"),
    ctrl("hitrust-06.c","Network Controls","Networks are managed and controlled to protect information in systems and applications.","Network Security","Implemented"),
    ctrl("hitrust-06.d","Security of Network Services","Security features, service levels, and management requirements of network services are identified.","Network Security","Implemented"),
    ctrl("hitrust-07.a","Information Classification","Information is classified according to legal requirements, value, criticality and sensitivity.","Information Management","Implemented"),
    ctrl("hitrust-07.b","Information Labelling","An appropriate set of procedures is developed and implemented for information labelling.","Information Management","In Progress"),
    ctrl("hitrust-08.a","Documented Operating Procedures","Security operating procedures are documented, maintained, and made available to all users.","Operations Security","Implemented"),
    ctrl("hitrust-08.b","Change Management","Changes to the organisation, business processes, information processing facilities and systems are controlled.","Operations Security","Implemented"),
    ctrl("hitrust-08.c","Segregation of Duties","Duties and areas of responsibility are segregated to reduce opportunities for unauthorised modification.","Operations Security","Implemented"),
    ctrl("hitrust-09.a","Transmission Integrity","Integrity of information passed over public communication networks is protected.","Transmission Protection","Implemented"),
    ctrl("hitrust-09.b","Encryption in Transit","Personal health information is encrypted in transit.","Transmission Protection","Implemented"),
    ctrl("hitrust-10.a","Security Requirements Analysis","Statements of business requirements for new information systems or enhancements include information security requirements.","Application Security","In Progress"),
    ctrl("hitrust-10.b","Secure Coding","Software development standards are implemented to ensure security.","Application Security","In Progress"),
    ctrl("hitrust-11.a","Reporting Information Security Events","Information security events are reported through appropriate management channels.","Incident Management","Implemented"),
    ctrl("hitrust-11.b","Incident Management Procedures","Responsibilities and procedures are established to handle information security events.","Incident Management","Implemented"),
    ctrl("hitrust-12.a","Business Continuity Management","A managed process for business continuity throughout the organisation is implemented.","Business Continuity","In Progress"),
    ctrl("hitrust-12.b","Testing and Evaluation","Business continuity plans are tested and updated regularly.","Business Continuity","Not Implemented"),
]

# ── CMMC 2.0 Level 2 – expanded ───────────────────────────────────────────────
CMMC_CONTROLS = [
    ctrl("cmmc-AC.L2-3.1.1","Authorised Access Control","Limit information system access to authorised users, processes acting on behalf of authorised users, and devices.","Access Control","Implemented"),
    ctrl("cmmc-AC.L2-3.1.2","Transaction and Function Control","Limit information system access to the types of transactions and functions that authorised users are permitted to execute.","Access Control","Implemented"),
    ctrl("cmmc-AC.L2-3.1.3","Control CUI Flow","Control the flow of CUI in accordance with approved authorisations.","Access Control","In Progress"),
    ctrl("cmmc-AC.L2-3.1.4","Separation of Duties","Separate the duties of individuals to reduce the risk of malevolent activity.","Access Control","Implemented"),
    ctrl("cmmc-AC.L2-3.1.5","Least Privilege","Employ the principle of least privilege, including for specific security functions.","Access Control","In Progress"),
    ctrl("cmmc-AC.L2-3.1.6","Non-Privileged Account Use","Use non-privileged accounts or roles when accessing non-security functions.","Access Control","Implemented"),
    ctrl("cmmc-AC.L2-3.1.7","Privileged Functions","Prevent non-privileged users from executing privileged functions.","Access Control","Implemented"),
    ctrl("cmmc-AC.L2-3.1.12","Remote Access Control","Monitor and control remote access sessions.","Access Control","Implemented"),
    ctrl("cmmc-AU.L2-3.3.1","System Auditing","Create and retain system audit logs to enable monitoring, analysis, investigation, and reporting.","Audit and Accountability","Implemented"),
    ctrl("cmmc-AU.L2-3.3.2","User Accountability","Ensure that the actions of individual system users can be traced to those users.","Audit and Accountability","Implemented"),
    ctrl("cmmc-CM.L2-3.4.1","System Baseline","Establish and maintain baseline configurations and inventories of organisational systems.","Configuration Management","In Progress"),
    ctrl("cmmc-CM.L2-3.4.2","Security Configuration Enforcement","Establish and enforce security configuration settings for information technology products.","Configuration Management","Implemented"),
    ctrl("cmmc-IA.L2-3.5.1","User Identification","Identify information system users, processes acting on behalf of users, and devices.","Identification and Authentication","Implemented"),
    ctrl("cmmc-IA.L2-3.5.2","User Authentication","Authenticate the identities of those users, processes, or devices as a prerequisite to allowing access.","Identification and Authentication","Implemented"),
    ctrl("cmmc-IA.L2-3.5.3","MFA for Local and Network Access","Use multifactor authentication for local and network access to privileged accounts.","Identification and Authentication","Implemented"),
    ctrl("cmmc-IR.L2-3.6.1","Incident Handling","Establish an operational incident-handling capability that includes preparation, detection, analysis, containment, recovery, and user response activities.","Incident Response","Implemented"),
    ctrl("cmmc-IR.L2-3.6.2","Incident Reporting","Track, document, and report incidents to designated officials and/or authorities.","Incident Response","Implemented"),
    ctrl("cmmc-MA.L2-3.7.1","Perform Maintenance","Perform maintenance on organisational information systems.","Maintenance","Implemented"),
    ctrl("cmmc-MP.L2-3.8.1","Media Protection","Protect system media containing CUI, both paper and digital.","Media Protection","Implemented"),
    ctrl("cmmc-PS.L2-3.9.1","Screen Individuals","Screen individuals prior to authorising access to organisational systems.","Personnel Security","Implemented"),
    ctrl("cmmc-RA.L2-3.11.1","Risk Assessment","Periodically assess the risk to organisational operations, assets, and individuals.","Risk Assessment","In Progress"),
    ctrl("cmmc-RA.L2-3.11.2","Vulnerability Scan","Periodically scan for vulnerabilities in organisational information systems.","Risk Assessment","At Risk"),
    ctrl("cmmc-SA.L2-3.12.1","Security Assessment","Periodically assess the security controls to determine if the controls are effective.","Security Assessment","Not Implemented"),
    ctrl("cmmc-SC.L2-3.13.1","Boundary Protection","Monitor, control, and protect communications at the external boundaries and key internal boundaries.","System and Communications Protection","Implemented"),
    ctrl("cmmc-SC.L2-3.13.8","Protect CUI in Transit","Implement cryptographic mechanisms to prevent unauthorised disclosure of CUI during transmission.","System and Communications Protection","Implemented"),
    ctrl("cmmc-SC.L2-3.13.11","FIPS-Validated Cryptography","Employ FIPS-validated cryptography when used to protect the confidentiality of CUI.","System and Communications Protection","Not Implemented"),
    ctrl("cmmc-SI.L2-3.14.1","Flaw Remediation","Identify, report, and correct information system flaws in a timely manner.","System and Information Integrity","In Progress"),
    ctrl("cmmc-SI.L2-3.14.2","Malicious Code Protection","Provide protection from malicious code at appropriate locations within organisational information systems.","System and Information Integrity","Implemented"),
    ctrl("cmmc-SI.L2-3.14.6","Monitor Systems","Monitor the information system to detect attacks and indicators of potential attacks.","System and Information Integrity","Implemented"),
]

# ── CSA STAR CCM v4 – expanded ─────────────────────────────────────────────────
CSA_CONTROLS = [
    ctrl("csa-AIS-01","Application and Interface Security Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for application security.","Application and Interface Security","Implemented"),
    ctrl("csa-AIS-02","Application Security Baseline","Establish, document and maintain baseline requirements for securing different categories of applications.","Application and Interface Security","In Progress"),
    ctrl("csa-AIS-03","Automated Secure Application Deployment","Automate application security testing as part of the CI/CD process.","Application and Interface Security","Not Implemented"),
    ctrl("csa-AIS-04","Application Security Metrics","Define and implement all relevant application security requirements for each interface and API.","Application and Interface Security","Not Implemented"),
    ctrl("csa-BCR-01","Business Continuity Planning","Establish, document, approve, communicate, apply, evaluate and maintain a business continuity plan.","Business Continuity Management","In Progress"),
    ctrl("csa-BCR-02","Business Continuity Testing","Test the business continuity plan at planned intervals or upon significant changes to the organisation.","Business Continuity Management","Not Implemented"),
    ctrl("csa-CEK-01","Encryption and Key Management Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for encryption and key management.","Cryptography, Encryption and Key Management","Implemented"),
    ctrl("csa-CEK-02","CEK Roles and Responsibilities","Define and implement cryptography, encryption and key management roles and responsibilities.","Cryptography, Encryption and Key Management","In Progress"),
    ctrl("csa-DCS-01","Data Centre Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for data centres.","Datacentre Security","Implemented"),
    ctrl("csa-DCS-06","Physical Access Restriction","Restrict physical access to information assets and functions by users and support personnel.","Datacentre Security","Implemented"),
    ctrl("csa-DSP-01","Data Security Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for data security.","Data Security and Privacy Lifecycle Management","Implemented"),
    ctrl("csa-DSP-07","Personal Data Protection","Personal data must be processed in accordance with applicable legislation.","Data Security and Privacy Lifecycle Management","In Progress"),
    ctrl("csa-GRC-01","Governance Program Policy","Establish and maintain a security, risk, and compliance governance program.","Governance, Risk and Compliance","Implemented"),
    ctrl("csa-GRC-05","Intellectual Property","Establish, document, apply, evaluate and maintain policies for intellectual property.","Governance, Risk and Compliance","Implemented"),
    ctrl("csa-HRS-01","HR Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for human resources security.","Human Resources","Implemented"),
    ctrl("csa-IAM-01","Identity and Access Management Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for identity and access management.","Identity and Access Management","Implemented"),
    ctrl("csa-IAM-02","Strong Password Policy","Require users to follow a strong password policy.","Identity and Access Management","Implemented"),
    ctrl("csa-IAM-03","Identity Inventory","Maintain an inventory of all service accounts, system accounts, and user accounts.","Identity and Access Management","In Progress"),
    ctrl("csa-IAM-08","Privileged Access Management","Restrict, log and monitor access to any resource granted privileged access.","Identity and Access Management","In Progress"),
    ctrl("csa-IVS-01","Network Security Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for network security.","Infrastructure and Virtualisation Security","Implemented"),
    ctrl("csa-IVS-06","Network Architecture","Design and implement security controls for network architecture.","Infrastructure and Virtualisation Security","Implemented"),
    ctrl("csa-LOG-01","Logging and Monitoring Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for logging and monitoring.","Logging and Monitoring","Implemented"),
    ctrl("csa-LOG-05","Audit Logs Protection","Protect audit logs against tampering.","Logging and Monitoring","Implemented"),
    ctrl("csa-SEF-01","Security Incident Management Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for security incident management.","Security Incident Management, E-Discovery and Cloud Forensics","Implemented"),
    ctrl("csa-SEF-05","Incident Response Testing","Perform testing of the incident management plan at planned intervals.","Security Incident Management, E-Discovery and Cloud Forensics","Not Implemented"),
    ctrl("csa-STA-01","Supply Chain Management Policy","Establish, document, approve, communicate, apply, evaluate and maintain a supply chain management policy.","Supply Chain Management, Transparency and Accountability","In Progress"),
    ctrl("csa-TVM-01","Threat and Vulnerability Management Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for threat and vulnerability management.","Threat and Vulnerability Management","Implemented"),
    ctrl("csa-TVM-02","Vulnerability Management","Establish and maintain processes to detect, remediate and report vulnerabilities in systems.","Threat and Vulnerability Management","At Risk"),
    ctrl("csa-UEM-01","Endpoint Device Policy","Establish, document, approve, communicate, apply, evaluate and maintain policies for all endpoint devices.","Universal Endpoint Management","Implemented"),
    ctrl("csa-UEM-06","Endpoint Device Encryption","Implement cryptographic protections at the data level for endpoint devices.","Universal Endpoint Management","Implemented"),
]

