"""Compliance framework definitions (part 2): ISO 42001, CCPA, COBIT, DORA, DPDP, ISO 9001, ISO 31000, SOX, EU AI Act, NIST AI RMF."""

from seed_compliance_controls_a import ctrl


FRAMEWORKS_PART2 = [
    {
        "id": "iso42001",
        "name": "ISO/IEC 42001:2023",
        "shortName": "ISO 42001",
        "description": "Artificial Intelligence Management System (AIMS)",
        "status": "In Progress",
        "progress": 30,
        "controls": [
            ctrl("A.2.1","AI Policy","The organisation shall define and establish an AI policy aligned with organisational objectives.","AI Policy","Implemented"),
            ctrl("A.2.2","AI Objectives","The organisation shall establish AI objectives at relevant functions and levels.","AI Policy","In Progress"),
            ctrl("A.3.1","AI Roles and Responsibilities","Roles and responsibilities for AI systems shall be defined and allocated.","Internal Organisation","In Progress"),
            ctrl("A.3.2","AI Risk Management","The organisation shall manage risks related to AI systems.","Internal Organisation","Not Implemented"),
            ctrl("A.4.1","Resources for AI Systems","The organisation shall determine and provide the resources needed for the AIMS.","Resources","Not Implemented"),
            ctrl("A.5.1","AI Impact Assessment","The organisation shall assess the impact of AI systems on individuals and societies.","Impact Assessment","At Risk"),
            ctrl("A.5.2","AI System Risk Classification","The organisation shall classify AI systems according to risk level.","Impact Assessment","Not Implemented"),
            ctrl("A.6.1","AI System Lifecycle","The organisation shall define processes for the AI system lifecycle.","AI System Lifecycle","Implemented"),
            ctrl("A.6.2","AI Design and Development","Requirements for design and development of AI systems shall be established.","AI System Lifecycle","Implemented"),
            ctrl("A.6.3","AI System Testing","AI systems shall be tested against requirements before deployment.","AI System Lifecycle","In Progress"),
            ctrl("A.6.4","AI System Deployment","AI systems shall be deployed with appropriate controls and documentation.","AI System Lifecycle","In Progress"),
            ctrl("A.6.5","AI System Decommissioning","AI systems shall be decommissioned in a controlled manner.","AI System Lifecycle","Not Implemented"),
            ctrl("A.7.1","Data Management","Data used for AI systems shall be managed to avoid bias and ensure quality.","Data for AI","In Progress"),
            ctrl("A.7.2","Data Quality","The organisation shall ensure data quality for AI systems.","Data for AI","Not Implemented"),
            ctrl("A.7.3","Data Provenance","The provenance of data used in AI systems shall be documented.","Data for AI","Not Implemented"),
            ctrl("A.8.1","Third-Party AI Systems","Requirements for third-party AI systems including data handling shall be defined.","Third Party","Not Implemented"),
            ctrl("A.9.1","Responsible Use of AI","The organisation shall ensure responsible use of AI preventing misuse.","Use of AI Systems","Implemented"),
            ctrl("A.9.2","Transparency and Explainability","AI systems shall be transparent and explainable to stakeholders.","Use of AI Systems","At Risk"),
            ctrl("A.9.3","Human Oversight","Mechanisms for human oversight of AI systems shall be established.","Use of AI Systems","Not Implemented"),
            ctrl("A.9.4","AI System Monitoring","AI systems shall be monitored for performance, fairness, and safety.","Use of AI Systems","In Progress"),
        ],
    },
    {
        "id": "ccpa",
        "name": "California Consumer Privacy Act (CCPA/CPRA)",
        "shortName": "CCPA",
        "description": "California Consumer Privacy Act as amended by CPRA",
        "status": "In Progress",
        "progress": 35,
        "controls": [
            ctrl("ccpa-1","Right to Know","Businesses must disclose data collection and sharing practices and honour consumer requests to know.","Consumer Rights","Implemented"),
            ctrl("ccpa-2","Right to Delete","Consumers have the right to request deletion of their personal information.","Consumer Rights","In Progress"),
            ctrl("ccpa-3","Right to Correct","Consumers have the right to correct inaccurate personal information.","Consumer Rights","Not Implemented"),
            ctrl("ccpa-4","Do Not Sell or Share","Businesses must provide a clear 'Do Not Sell or Share My Personal Information' option.","Opt-Out","Not Implemented"),
            ctrl("ccpa-5","Limit Use of Sensitive PI","Consumers have the right to limit the use and disclosure of sensitive personal information.","Opt-Out","Not Implemented"),
            ctrl("ccpa-6","Non-Discrimination","Businesses must not discriminate against consumers who exercise their privacy rights.","Consumer Rights","Implemented"),
            ctrl("ccpa-7","Privacy Notice","Provide a comprehensive privacy policy describing data practices.","Transparency","Implemented"),
            ctrl("ccpa-8","Reasonable Security","Implement and maintain reasonable security procedures appropriate to the nature of the data.","Security","At Risk"),
            ctrl("ccpa-9","Data Minimisation","Collect only the minimum personal information necessary for the stated purpose.","Data Practices","Not Implemented"),
            ctrl("ccpa-10","CPRA Audit Requirements","Businesses processing high-risk data shall submit to annual cybersecurity audits.","Governance","Not Implemented"),
        ],
    },
    {
        "id": "cobit_2019",
        "name": "COBIT 2019",
        "shortName": "COBIT",
        "description": "Control Objectives for Information and Related Technologies – IT Governance Framework",
        "status": "In Progress",
        "progress": 25,
        "controls": [
            ctrl("cobit-EDM01","Ensured Governance Framework Setting and Maintenance","Analyse and articulate the requirements for the governance of enterprise IT and put in place an effective enabling governance framework.","Evaluate, Direct and Monitor","Implemented"),
            ctrl("cobit-EDM02","Ensured Benefits Delivery","Optimise the value contribution to the business from business processes, IT services and IT assets resulting from investments made by IT at acceptable costs.","Evaluate, Direct and Monitor","In Progress"),
            ctrl("cobit-EDM03","Ensured Risk Optimisation","Ensure that IT-related enterprise risk does not exceed risk appetite and risk tolerance.","Evaluate, Direct and Monitor","In Progress"),
            ctrl("cobit-APO12","Managed Risk","Continually identify, assess and reduce IT-related risk within levels of tolerance set by enterprise executive management.","Align, Plan and Organise","At Risk"),
            ctrl("cobit-APO13","Managed Security","Define, operate and monitor a system for information security management.","Align, Plan and Organise","In Progress"),
            ctrl("cobit-APO14","Managed Data","Manage data and information across the enterprise to ensure it is accessed and used appropriately.","Align, Plan and Organise","Not Implemented"),
            ctrl("cobit-BAI06","Managed IT Changes","Manage all changes in a controlled manner, including standard changes and emergency maintenance.","Build, Acquire and Implement","Implemented"),
            ctrl("cobit-BAI10","Managed Configuration","Define and maintain descriptions and relationships between key resources and capabilities required to deliver IT-enabled services.","Build, Acquire and Implement","In Progress"),
            ctrl("cobit-DSS01","Managed Operations","Coordinate and execute the activities and operational procedures required to deliver internal and outsourced IT services.","Deliver, Service and Support","Implemented"),
            ctrl("cobit-DSS02","Managed Service Requests and Incidents","Provide timely and effective response to user requests and resolution of all types of incidents.","Deliver, Service and Support","Implemented"),
            ctrl("cobit-DSS05","Managed Security Services","Protect enterprise information to maintain the level of information security risk acceptable to the enterprise.","Deliver, Service and Support","In Progress"),
            ctrl("cobit-DSS06","Managed Business Process Controls","Define and maintain appropriate business process controls to ensure that information related to and processed by in-house or outsourced business processes satisfies all relevant information control requirements.","Deliver, Service and Support","Not Implemented"),
            ctrl("cobit-MEA01","Managed Performance and Conformance Monitoring","Collect, validate and evaluate business, IT and process goals and metrics.","Monitor, Evaluate and Assess","In Progress"),
            ctrl("cobit-MEA02","Managed System of Internal Control","Continuously monitor and evaluate the control environment, including self-assessments and independent assurance reviews.","Monitor, Evaluate and Assess","Not Implemented"),
        ],
    },
    {
        "id": "dora",
        "name": "DORA (EU)",
        "shortName": "DORA",
        "description": "Digital Operational Resilience Act – EU regulation for financial sector ICT risk",
        "status": "In Progress",
        "progress": 50,
        "controls": [
            ctrl("dora-Art5","ICT Risk Management Framework","Financial entities shall have a sound, comprehensive and well-documented ICT risk management framework.","Risk Management","Implemented"),
            ctrl("dora-Art6","ICT Risk Management Systems","As part of the ICT risk management framework, financial entities shall implement ICT risk management systems, protocols and tools.","Risk Management","In Progress"),
            ctrl("dora-Art7","ICT Systems, Protocols and Tools","Financial entities shall use and maintain updated ICT systems, protocols and tools that are appropriate to their size, business, risk profile and complexity.","Protection","Implemented"),
            ctrl("dora-Art8","Identification","Financial entities shall continuously identify all sources of ICT risk and assess cyber threats and ICT vulnerabilities.","Identification","In Progress"),
            ctrl("dora-Art9","Protection and Prevention","Financial entities shall implement ICT security policies, procedures, protocols and tools to protect their ICT assets from cyberattacks.","Protection","Implemented"),
            ctrl("dora-Art10","Detection","Financial entities shall put in place mechanisms to promptly detect anomalous activities.","Detection","Implemented"),
            ctrl("dora-Art11","Response and Recovery","Financial entities shall have in place a comprehensive ICT business continuity policy.","Response and Recovery","In Progress"),
            ctrl("dora-Art12","Backup Policies and Procedures","Financial entities shall establish backup policies and procedures and restoration and recovery procedures and methods.","Response and Recovery","Implemented"),
            ctrl("dora-Art13","Learning and Evolving","Financial entities shall have in place capabilities and staff to gather information on vulnerabilities and cyber threats.","Learning","In Progress"),
            ctrl("dora-Art14","Communication","Financial entities shall have in place crisis communication plans enabling a responsible disclosure of ICT-related incidents.","Communication","In Progress"),
            ctrl("dora-Art17","ICT-Related Incident Management Process","Financial entities shall define, establish and implement an ICT-related incident management process.","Incident Management","Implemented"),
            ctrl("dora-Art19","Reporting Major ICT-Related Incidents","Financial entities shall report major ICT-related incidents to the relevant competent authority.","Incident Reporting","In Progress"),
            ctrl("dora-Art24","General Requirements for Digital Operational Resilience Testing","Financial entities shall establish, maintain and review a sound and comprehensive digital operational resilience testing programme.","Testing","Not Implemented"),
            ctrl("dora-Art28","General Principles","Financial entities shall manage ICT third-party risk as an integral component of ICT risk.","Third-Party Risk","In Progress"),
        ],
    },
    {
        "id": "dpdp",
        "name": "Digital Personal Data Protection Act (DPDP)",
        "shortName": "DPDP",
        "description": "India's Digital Personal Data Protection Act, 2023",
        "status": "In Progress",
        "progress": 40,
        "controls": [
            ctrl("DPDP-5.1","Consent for Processing","Personal data is processed only for a lawful purpose for which the Data Principal has given consent.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-5.2","Deemed Consent","Personal data may be processed without consent for certain legitimate uses.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-6.1","Notice for Consent","A notice shall be given to the Data Principal at the time of seeking consent.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-6.2","Language of Notice","The notice shall be in English or any of the languages specified in the Eighth Schedule.","Obligations of Data Fiduciary","In Progress"),
            ctrl("DPDP-8.1","General Obligations","Data Fiduciary shall be responsible for complying with the provisions of this Act.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-8.2","Accuracy of Data","Data Fiduciary shall ensure accuracy and completeness of personal data.","Obligations of Data Fiduciary","In Progress"),
            ctrl("DPDP-8.3","Data Security","Data Fiduciary shall protect personal data in its possession using reasonable security safeguards.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-8.4","Data Retention Pruning","Data Fiduciary shall erase personal data after the purpose is processed or upon withdrawal of consent.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-8.5","Breach Notification","In the event of a personal data breach, the Data Fiduciary shall give intimation to the Board and each affected Data Principal.","Obligations of Data Fiduciary","At Risk"),
            ctrl("DPDP-8.6","Grievance Redressal","Data Fiduciary shall establish an effective mechanism to redress the grievances of Data Principals.","Obligations of Data Fiduciary","In Progress"),
            ctrl("DPDP-8.7","Consent Manager","Data Fiduciary shall engage only Data Processors on contractual basis.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-8.9","Data Processor Contracts","Data Fiduciary shall engage a Data Processor only under a valid contract.","Obligations of Data Fiduciary","Implemented"),
            ctrl("DPDP-9.1","Child Data Age-Gating","Verifiable parental consent is obtained before processing personal data of a child.","Special Provisions","Implemented"),
            ctrl("DPDP-9.2","Behavioural Monitoring Prohibition","Data Fiduciary shall not undertake tracking or behavioural monitoring of children.","Special Provisions","Implemented"),
            ctrl("DPDP-10.1","Significant Data Fiduciary – DPO","Significant Data Fiduciaries shall appoint a Data Protection Officer based in India.","Significant Data Fiduciary","Not Implemented"),
            ctrl("DPDP-10.2","Significant Data Fiduciary – Audits","Significant Data Fiduciaries shall appoint an independent data auditor to carry out data audits.","Significant Data Fiduciary","Not Implemented"),
            ctrl("DPDP-10.3","Significant Data Fiduciary – DPIA","Significant Data Fiduciaries shall conduct periodic Data Protection Impact Assessments.","Significant Data Fiduciary","Not Implemented"),
            ctrl("DPDP-13.1","Rights – Access Information","Data Principal shall have the right to obtain information about personal data processed.","Rights of Data Principal","Implemented"),
            ctrl("DPDP-13.2","Rights – Correction and Erasure","Data Principal shall have the right to correction and erasure of personal data.","Rights of Data Principal","In Progress"),
            ctrl("DPDP-13.3","Rights – Grievance Redressal","Data Principal shall have the right to have grievances redressed.","Rights of Data Principal","In Progress"),
            ctrl("DPDP-13.4","Rights – Nomination","Data Principal may nominate another individual to exercise rights in event of death.","Rights of Data Principal","Not Implemented"),
        ],
    },
    {
        "id": "iso9001_2015",
        "name": "ISO 9001:2015",
        "shortName": "ISO 9001",
        "description": "Quality Management Systems – Requirements",
        "status": "In Progress",
        "progress": 35,
        "controls": [
            ctrl("iso9001-4.1","Understanding the Organisation","The organisation shall determine external and internal issues relevant to its purpose.","Context of the Organisation","Implemented"),
            ctrl("iso9001-4.2","Interested Parties","The organisation shall determine interested parties and their requirements.","Context of the Organisation","Implemented"),
            ctrl("iso9001-4.3","Scope of QMS","The organisation shall determine the boundaries and applicability of the QMS.","Context of the Organisation","Implemented"),
            ctrl("iso9001-4.4","QMS and its Processes","The organisation shall establish, implement, maintain and continually improve a QMS.","Context of the Organisation","Implemented"),
            ctrl("iso9001-5.1","Leadership and Commitment","Top management shall demonstrate leadership and commitment with respect to the QMS.","Leadership","Implemented"),
            ctrl("iso9001-5.2","Quality Policy","Top management shall establish, implement and maintain a quality policy.","Leadership","Implemented"),
            ctrl("iso9001-5.3","Roles and Responsibilities","Top management shall ensure responsibilities and authorities for relevant roles are assigned.","Leadership","Implemented"),
            ctrl("iso9001-6.1","Actions to Address Risks and Opportunities","The organisation shall determine risks and opportunities that need to be addressed.","Planning","In Progress"),
            ctrl("iso9001-6.2","Quality Objectives","The organisation shall establish quality objectives at relevant functions and levels.","Planning","Implemented"),
            ctrl("iso9001-7.1","Resources","The organisation shall determine and provide the resources needed for the QMS.","Support","Implemented"),
            ctrl("iso9001-7.2","Competence","The organisation shall ensure persons doing work that affects quality are competent.","Support","Implemented"),
            ctrl("iso9001-7.3","Awareness","Persons doing work under the organisation's control shall be aware of the quality policy.","Support","Implemented"),
            ctrl("iso9001-7.4","Communication","The organisation shall determine the internal and external communications relevant to the QMS.","Support","Implemented"),
            ctrl("iso9001-7.5","Documented Information","The QMS shall include documented information required by this standard.","Support","Implemented"),
            ctrl("iso9001-8.1","Operational Planning and Control","The organisation shall plan, implement, control and maintain the processes needed to meet requirements.","Operation","In Progress"),
            ctrl("iso9001-8.4","Control of Externally Provided Processes","The organisation shall ensure that externally provided processes, products and services conform to requirements.","Operation","In Progress"),
            ctrl("iso9001-8.5","Production and Service Provision","The organisation shall implement production and service provision under controlled conditions.","Operation","Implemented"),
            ctrl("iso9001-9.1","Monitoring, Measurement, Analysis and Evaluation","The organisation shall determine what needs to be monitored and measured.","Performance Evaluation","In Progress"),
            ctrl("iso9001-9.2","Internal Audit","The organisation shall conduct internal audits at planned intervals.","Performance Evaluation","In Progress"),
            ctrl("iso9001-9.3","Management Review","Top management shall review the organisation's QMS at planned intervals.","Performance Evaluation","In Progress"),
            ctrl("iso9001-10.2","Nonconformity and Corrective Action","The organisation shall react to nonconformity and take action to control and correct it.","Improvement","In Progress"),
            ctrl("iso9001-10.3","Continual Improvement","The organisation shall continually improve the suitability, adequacy and effectiveness of the QMS.","Improvement","In Progress"),
        ],
    },
    {
        "id": "iso31000_2018",
        "name": "ISO 31000:2018",
        "shortName": "ISO 31000",
        "description": "Risk Management – Guidelines",
        "status": "In Progress",
        "progress": 25,
        "controls": [
            ctrl("iso31000-4.1","Integration","Risk management shall be integrated into the organisation's activities and governance.","Principles","In Progress"),
            ctrl("iso31000-4.2","Structured and Comprehensive Approach","A structured and comprehensive approach to risk management contributes to consistent and comparable results.","Principles","Implemented"),
            ctrl("iso31000-4.3","Customised Approach","The risk management framework and process shall be customised to the organisation.","Principles","Implemented"),
            ctrl("iso31000-4.4","Inclusive Approach","Appropriate and timely involvement of stakeholders enables their knowledge and perspectives to be considered.","Principles","In Progress"),
            ctrl("iso31000-5.2","Leadership and Commitment","Top management shall ensure risk management is integrated into all organisational activities.","Framework","Implemented"),
            ctrl("iso31000-5.3","Integration of Framework","Risk management shall be integrated into the organisation's purpose, governance, policies, commitments and strategy.","Framework","In Progress"),
            ctrl("iso31000-5.4","Design of Framework","The organisation shall examine and understand the organisation and its context when designing the framework.","Framework","Implemented"),
            ctrl("iso31000-5.5","Implementation of Framework","The organisation shall implement the risk management framework.","Framework","Implemented"),
            ctrl("iso31000-5.6","Evaluation of Framework","The organisation shall periodically measure the performance of the risk management framework.","Framework","Not Implemented"),
            ctrl("iso31000-6.2","Communication and Consultation","Communication and consultation with external and internal stakeholders shall take place.","Process","In Progress"),
            ctrl("iso31000-6.3","Scope, Context and Criteria","The organisation shall define the scope of its risk management activities.","Process","Implemented"),
            ctrl("iso31000-6.4.1","Risk Identification","The organisation shall find, recognise and describe risks.","Process","Implemented"),
            ctrl("iso31000-6.4.2","Risk Analysis","Risk analysis involves developing an understanding of the risk.","Process","Implemented"),
            ctrl("iso31000-6.4.3","Risk Evaluation","Risk evaluation involves comparing results of risk analysis with established risk criteria.","Process","In Progress"),
            ctrl("iso31000-6.5","Risk Treatment","Risk treatment involves selecting and implementing options for addressing risk.","Process","In Progress"),
            ctrl("iso31000-6.6","Monitoring and Review","The purpose of monitoring and review is to assure and improve the quality and effectiveness of process design.","Process","Not Implemented"),
            ctrl("iso31000-6.7","Recording and Reporting","The risk management process and its outcomes should be documented and reported.","Process","In Progress"),
        ],
    },
    # ── NIST SP 800-53 Rev 5 ─────────────────────────────────────────────
    {
        "id": "nist_800_53",
        "name": "NIST SP 800-53 Rev 5",
        "shortName": "NIST 800-53",
        "description": "Security and Privacy Controls for Information Systems and Organizations – the comprehensive US federal control catalog underpinning FedRAMP, CMMC, and FISMA.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("AC-1","Access Control Policy and Procedures","Develop, document, and disseminate an access control policy and procedures.","Access Control"),
            ctrl("AC-2","Account Management","Manage information system accounts including account types, account establishment, modification, disabling, termination, and reviews.","Access Control"),
            ctrl("AC-3","Access Enforcement","Enforce approved authorizations for logical access to system resources.","Access Control"),
            ctrl("AC-6","Least Privilege","Employ the principle of least privilege.","Access Control"),
            ctrl("AC-17","Remote Access","Establish and document usage restrictions, configuration/connection requirements, and implementation guidance for remote access.","Access Control"),
            ctrl("AT-2","Literacy Training and Awareness","Provide security and privacy literacy training to system users.","Awareness and Training"),
            ctrl("AT-3","Role-Based Training","Provide role-based security and privacy training.","Awareness and Training"),
            ctrl("AU-2","Event Logging","Identify the types of events that the system is capable of logging.","Audit and Accountability"),
            ctrl("AU-6","Audit Record Review, Analysis, and Reporting","Review and analyze system audit records for indications of inappropriate or unusual activity.","Audit and Accountability"),
            ctrl("AU-9","Protection of Audit Information","Protect audit information and audit tools from unauthorized access, modification, and deletion.","Audit and Accountability"),
            ctrl("CA-2","Control Assessments","Assess the controls in the system and its environment of operation.","Assessment and Authorization"),
            ctrl("CA-7","Continuous Monitoring","Develop a system-level continuous monitoring strategy.","Assessment and Authorization"),
            ctrl("CM-2","Baseline Configuration","Develop, document, and maintain a current baseline configuration of the system.","Configuration Management"),
            ctrl("CM-6","Configuration Settings","Establish and document configuration settings for technology products employed within the system.","Configuration Management"),
            ctrl("CM-7","Least Functionality","Configure the system to provide only essential capabilities.","Configuration Management"),
            ctrl("CP-9","System Backup","Conduct backups of user-level and system-level information.","Contingency Planning"),
            ctrl("CP-10","System Recovery and Reconstitution","Provide for the recovery and reconstitution of the system to a known state.","Contingency Planning"),
            ctrl("IA-2","Identification and Authentication (Organizational Users)","Uniquely identify and authenticate organizational users.","Identification and Authentication"),
            ctrl("IA-5","Authenticator Management","Manage system authenticators including establishing initial authenticator content and ensuring authenticators have sufficient strength.","Identification and Authentication"),
            ctrl("IA-8","Identification and Authentication (Non-Organizational Users)","Uniquely identify and authenticate non-organizational users.","Identification and Authentication"),
            ctrl("IR-4","Incident Handling","Implement an incident handling capability for incidents that is consistent with the incident response plan.","Incident Response"),
            ctrl("IR-5","Incident Monitoring","Track and document incidents.","Incident Response"),
            ctrl("IR-6","Incident Reporting","Require personnel to report suspected incidents to the organizational incident response capability.","Incident Response"),
            ctrl("MA-2","Controlled Maintenance","Schedule, document, and review records of maintenance and repairs on system components.","Maintenance"),
            ctrl("MP-5","Media Transport","Protect and control digital and non-digital media during transport outside controlled areas.","Media Protection"),
            ctrl("PE-2","Physical Access Authorizations","Develop, approve, and maintain a list of individuals with authorized access to the facility where the system resides.","Physical and Environmental Protection"),
            ctrl("PL-2","System Security and Privacy Plans","Develop security and privacy plans for the system.","Planning"),
            ctrl("PM-9","Risk Management Strategy","Develop and implement an organization-wide risk management strategy.","Program Management"),
            ctrl("PS-3","Personnel Screening","Screen individuals prior to authorizing access to the system.","Personnel Security"),
            ctrl("PT-2","Authority to Process Personally Identifiable Information","Determine and document the legal authority that permits the processing of PII.","PII Processing and Transparency"),
            ctrl("RA-3","Risk Assessment","Assess the risk to organizational operations and assets from the operation and use of the system.","Risk Assessment"),
            ctrl("RA-5","Vulnerability Monitoring and Scanning","Monitor and scan for vulnerabilities in the system and hosted applications.","Risk Assessment"),
            ctrl("SA-11","Developer Testing and Evaluation","Require the developer of the system to implement a testing and evaluation plan.","System and Services Acquisition"),
            ctrl("SC-8","Transmission Confidentiality and Integrity","Implement cryptographic mechanisms to prevent unauthorized disclosure of information during transmission.","System and Communications Protection"),
            ctrl("SC-28","Protection of Information at Rest","Implement cryptographic mechanisms to prevent unauthorized disclosure of information at rest.","System and Communications Protection"),
            ctrl("SI-3","Malicious Code Protection","Implement malicious code protection mechanisms.","System and Information Integrity"),
            ctrl("SI-4","System Monitoring","Monitor the system to detect attacks and indicators of potential attacks.","System and Information Integrity"),
            ctrl("SR-3","Supply Chain Controls and Processes","Establish a process or processes to identify and address weaknesses or deficiencies in the supply chain.","Supply Chain Risk Management"),
            ctrl("SR-6","Supplier Assessments and Reviews","Assess and review the supply chain-related risks associated with suppliers or contractors.","Supply Chain Risk Management"),
        ],
    },
    # ── NIST SP 800-171 Rev 2 ────────────────────────────────────────────
    {
        "id": "nist_800_171",
        "name": "NIST SP 800-171 Rev 2",
        "shortName": "NIST 800-171",
        "description": "Protecting Controlled Unclassified Information (CUI) in Non-Federal Systems – mandatory for all DoD contractors handling CUI and the direct baseline for CMMC Level 2.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("3.1.1","Authorized System Access","Limit system access to authorized users, processes acting on behalf of authorized users, and devices.","Access Control"),
            ctrl("3.1.2","Authorized Transaction Access","Limit system access to the types of transactions and functions authorized users are permitted to execute.","Access Control"),
            ctrl("3.1.3","Control CUI Flow","Control the flow of CUI in accordance with approved authorizations.","Access Control"),
            ctrl("3.1.5","Least Privilege","Employ the principle of least privilege, including for specific security functions and privileged accounts.","Access Control"),
            ctrl("3.1.12","Remote Access Monitoring","Monitor and control remote access sessions.","Access Control"),
            ctrl("3.2.1","Awareness Training","Ensure that personnel are aware of the security risks associated with their activities.","Awareness and Training"),
            ctrl("3.2.2","Role-Based Training","Ensure that personnel are trained to carry out their assigned information security responsibilities.","Awareness and Training"),
            ctrl("3.3.1","Audit Logging","Create and retain system audit logs to enable the monitoring, analysis, investigation, and reporting of unlawful or unauthorized activity.","Audit and Accountability"),
            ctrl("3.3.2","User Audit Traceability","Ensure that the actions of individual system users can be traced to those users.","Audit and Accountability"),
            ctrl("3.4.1","Baseline Configuration","Establish and maintain baseline configurations and inventories of organizational systems.","Configuration Management"),
            ctrl("3.4.2","Security Configuration Enforcement","Establish and enforce security configuration settings for IT products.","Configuration Management"),
            ctrl("3.4.6","Least Functionality","Employ the principle of least functionality by configuring systems to provide only essential capabilities.","Configuration Management"),
            ctrl("3.5.1","User Identification","Identify system users, processes acting on behalf of users, and devices.","Identification and Authentication"),
            ctrl("3.5.2","Authentication","Authenticate the identities of users, processes, and devices before allowing access.","Identification and Authentication"),
            ctrl("3.5.3","Multifactor Authentication","Use multifactor authentication for local and network access to privileged accounts.","Identification and Authentication"),
            ctrl("3.6.1","Incident Handling","Establish an operational incident-handling capability including adequate preparation, detection, analysis, containment, recovery, and user response activities.","Incident Response"),
            ctrl("3.6.2","Incident Reporting","Track, document, and report incidents to appropriate officials.","Incident Response"),
            ctrl("3.7.1","Maintenance","Perform maintenance on organizational systems.","Maintenance"),
            ctrl("3.8.3","Media Sanitization","Sanitize or destroy system media before disposal or reuse.","Media Protection"),
            ctrl("3.8.9","CUI Backup Protection","Protect the confidentiality of backup CUI at storage locations.","Media Protection"),
            ctrl("3.9.1","Personnel Screening","Screen individuals prior to authorizing access to CUI systems.","Personnel Security"),
            ctrl("3.10.1","Physical Access Authorization","Limit physical access to CUI systems to authorized individuals.","Physical Protection"),
            ctrl("3.10.2","Physical Access Monitoring","Protect and monitor the physical facility and support infrastructure for CUI systems.","Physical Protection"),
            ctrl("3.11.1","Risk Assessment","Periodically assess the risk to operations, assets, and individuals from processing CUI.","Risk Assessment"),
            ctrl("3.11.2","Vulnerability Scanning","Scan for vulnerabilities in CUI systems periodically and when new vulnerabilities affecting those systems are identified.","Risk Assessment"),
            ctrl("3.12.1","Security Assessment","Periodically assess the security controls to determine their effectiveness.","Security Assessment"),
            ctrl("3.12.3","Security Control Monitoring","Monitor security controls on an ongoing basis to ensure effectiveness.","Security Assessment"),
            ctrl("3.13.1","Boundary Protection","Monitor, control, and protect communications at external boundaries and key internal boundaries.","System and Communications Protection"),
            ctrl("3.13.5","Public System Separation","Implement subnetworks for publicly accessible system components.","System and Communications Protection"),
            ctrl("3.13.8","Transmission Encryption","Implement cryptographic mechanisms to prevent unauthorized disclosure during transmission.","System and Communications Protection"),
            ctrl("3.14.1","Malicious Code Protection","Identify, report, and correct system flaws in a timely manner.","System and Information Integrity"),
            ctrl("3.14.6","System Monitoring","Monitor the system to detect attacks and indicators of potential attacks.","System and Information Integrity"),
        ],
    },
    # ── CIS Controls v8.1 ─────────────────────────────────────────────────
    {
        "id": "cis_v8",
        "name": "CIS Controls v8.1",
        "shortName": "CIS Controls",
        "description": "Center for Internet Security Controls – the most widely adopted prioritized set of 18 cybersecurity safeguard groups covering foundational security hygiene for all enterprises.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("CIS-1","Inventory and Control of Enterprise Assets","Actively manage all enterprise assets connected to the infrastructure to accurately know the total asset base.","Asset Management"),
            ctrl("CIS-2","Inventory and Control of Software Assets","Actively manage all software on the network so that only authorized software is installed and can execute.","Asset Management"),
            ctrl("CIS-3","Data Protection","Develop processes and technical controls to identify, classify, securely handle, retain, and dispose of data.","Data Management"),
            ctrl("CIS-4","Secure Configuration of Enterprise Assets and Software","Establish and maintain the secure configuration of enterprise assets and software.","Secure Configuration"),
            ctrl("CIS-5","Account Management","Use processes and tools to assign and manage authorization to credentials for user accounts.","Identity and Access Management"),
            ctrl("CIS-6","Access Control Management","Use processes and tools to create, assign, manage, and revoke access credentials and privileges.","Identity and Access Management"),
            ctrl("CIS-7","Continuous Vulnerability Management","Develop a plan to continuously assess and track vulnerabilities on all enterprise assets within the infrastructure.","Vulnerability Management"),
            ctrl("CIS-8","Audit Log Management","Collect, alert, review, and retain audit logs of events that could help detect, understand, or recover from an attack.","Audit and Logging"),
            ctrl("CIS-9","Email and Web Browser Protections","Improve protections and detections of threats from email and web vectors.","Browser and Email Security"),
            ctrl("CIS-10","Malware Defenses","Prevent or control the installation, spread, and execution of malicious applications, code, or scripts.","Malware Defense"),
            ctrl("CIS-11","Data Recovery","Establish and maintain data recovery practices sufficient to restore in-scope enterprise assets.","Data Recovery"),
            ctrl("CIS-12","Network Infrastructure Management","Establish, implement, and actively manage network devices to prevent attackers from exploiting network services.","Network Security"),
            ctrl("CIS-13","Network Monitoring and Defense","Operate processes and tooling to establish and maintain comprehensive network monitoring and defense.","Network Security"),
            ctrl("CIS-14","Security Awareness and Skills Training","Establish and maintain a security awareness program to influence behavior among the workforce.","Security Awareness"),
            ctrl("CIS-15","Service Provider Management","Develop a process to evaluate service providers who hold sensitive data or are responsible for critical IT platforms.","Third-Party Risk"),
            ctrl("CIS-16","Application Software Security","Manage the security life cycle of in-house developed, hosted, or acquired software.","Application Security"),
            ctrl("CIS-17","Incident Response Management","Establish a program to develop and maintain an incident response capability.","Incident Response"),
            ctrl("CIS-18","Penetration Testing","Test the effectiveness and resiliency of enterprise assets through identifying and exploiting weaknesses in controls.","Security Testing"),
        ],
    },
    # ── SOX IT General Controls ───────────────────────────────────────────
    {
        "id": "sox_itgc",
        "name": "SOX IT General Controls",
        "shortName": "SOX ITGC",
        "description": "Sarbanes-Oxley Act IT General Controls – US federal requirements governing IT controls over financial reporting for public companies, audited annually under PCAOB AS 2201.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("SOX-LA-1","User Access Provisioning","Formal process exists for granting and revoking user access to financial systems.","Logical Access"),
            ctrl("SOX-LA-2","Privileged Access Review","Privileged (administrator) access to financial systems is reviewed periodically.","Logical Access"),
            ctrl("SOX-LA-3","Segregation of Duties","Incompatible duties within financial processes are separated to prevent fraud.","Logical Access"),
            ctrl("SOX-LA-4","Shared/Generic Account Controls","Generic and shared accounts are prohibited or strictly controlled and justified.","Logical Access"),
            ctrl("SOX-LA-5","Terminated User Access Removal","Access for terminated employees is promptly revoked from all financial systems.","Logical Access"),
            ctrl("SOX-LA-6","Password Policy","Password complexity, length, and rotation requirements are enforced for financial systems.","Logical Access"),
            ctrl("SOX-LA-7","Multi-Factor Authentication","MFA is required for remote and privileged access to financial systems.","Logical Access"),
            ctrl("SOX-CM-1","Change Management Policy","A formal change management policy exists for financial system changes.","Change Management"),
            ctrl("SOX-CM-2","Change Authorization","All changes to financial systems require documented authorization prior to implementation.","Change Management"),
            ctrl("SOX-CM-3","Change Testing","Changes to financial systems are tested in non-production environments before deployment.","Change Management"),
            ctrl("SOX-CM-4","Emergency Change Process","Emergency changes follow an expedited but controlled and documented process.","Change Management"),
            ctrl("SOX-CM-5","Segregation of Development and Production","Developers do not have access to promote their own changes to production financial systems.","Change Management"),
            ctrl("SOX-CO-1","Job Scheduling and Monitoring","Automated batch jobs supporting financial processes are monitored for successful completion.","Computer Operations"),
            ctrl("SOX-CO-2","Incident and Problem Management","Incidents affecting financial systems are logged, tracked, and resolved in a timely manner.","Computer Operations"),
            ctrl("SOX-CO-3","System Availability Monitoring","Availability and performance of financial systems are actively monitored.","Computer Operations"),
            ctrl("SOX-BR-1","Backup Policy and Procedures","Formal backup policies exist for financial data including frequency and retention requirements.","Backup and Recovery"),
            ctrl("SOX-BR-2","Backup Testing","Backups of financial data are periodically tested to ensure recoverability.","Backup and Recovery"),
            ctrl("SOX-BR-3","Disaster Recovery Plan","A disaster recovery plan exists for financial systems covering RTOs and RPOs.","Backup and Recovery"),
            ctrl("SOX-BR-4","DR Testing","Disaster recovery capability for financial systems is tested at least annually.","Backup and Recovery"),
            ctrl("SOX-SA-1","Security Awareness Training","Users with access to financial systems receive security awareness training.","Security and Compliance"),
            ctrl("SOX-SA-2","Vulnerability Management","Financial systems are included in vulnerability scanning programs.","Security and Compliance"),
            ctrl("SOX-SA-3","Patch Management","Security patches are applied to financial systems according to defined timelines.","Security and Compliance"),
            ctrl("SOX-SA-4","Audit Log Retention","Audit logs for financial systems are retained according to regulatory requirements.","Security and Compliance"),
            ctrl("SOX-SA-5","Physical Access to Data Centers","Physical access to data centers hosting financial systems is restricted and logged.","Security and Compliance"),
        ],
    },
    # ── NIS2 Directive (EU) 2022/2555 ────────────────────────────────────
    {
        "id": "nis2",
        "name": "NIS2 Directive (EU) 2022/2555",
        "shortName": "NIS2",
        "description": "EU Network and Information Security Directive 2 – mandatory cybersecurity requirements for essential and important entities across 18 critical sectors, effective October 2024.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("NIS2-21.1","Risk Analysis and ISSP","Organisations shall adopt policies on risk analysis and information system security.","Article 21 Security Measures"),
            ctrl("NIS2-21.2","Incident Handling","Organisations shall establish incident handling capabilities covering detection, containment, recovery and reporting.","Article 21 Security Measures"),
            ctrl("NIS2-21.3","Business Continuity and Crisis Management","Organisations shall implement BCM including backup management, DR, and crisis management.","Article 21 Security Measures"),
            ctrl("NIS2-21.4","Supply Chain Security","Organisations shall address security in supply chain relationships including supplier-specific policies.","Article 21 Security Measures"),
            ctrl("NIS2-21.5","Security in Network and Information Systems Acquisition","Organisations shall maintain policies for security in acquisition, development and maintenance of network and IS.","Article 21 Security Measures"),
            ctrl("NIS2-21.6","Cybersecurity Risk Management Assessment","Organisations shall adopt policies for assessing the effectiveness of cybersecurity risk management measures.","Article 21 Security Measures"),
            ctrl("NIS2-21.7","Cybersecurity Hygiene and Training","Organisations shall implement basic cyber hygiene practices and cybersecurity training.","Article 21 Security Measures"),
            ctrl("NIS2-21.8","Cryptography Policy","Organisations shall adopt policies on the use of cryptography and, where appropriate, encryption.","Article 21 Security Measures"),
            ctrl("NIS2-21.9","Human Resources Security and Access Control","Organisations shall ensure appropriate personnel security policies, access control, and asset management.","Article 21 Security Measures"),
            ctrl("NIS2-21.10","Multi-Factor Authentication","Organisations shall use multi-factor or continuous authentication solutions.","Article 21 Security Measures"),
            ctrl("NIS2-21.11","Secure Communications","Organisations shall use secured voice, video and text communications and secured emergency communication systems.","Article 21 Security Measures"),
            ctrl("NIS2-23","Significant Incident Reporting","Essential entities shall notify CSIRT/authority of significant incidents within 24 hours (early warning) and 72 hours (incident notification).","Incident Reporting Obligations"),
            ctrl("NIS2-32","Management Body Accountability","Management bodies of essential and important entities must approve cybersecurity risk management measures and oversee implementation.","Governance"),
            ctrl("NIS2-38","Supervisory Measures","Competent authorities may subject essential entities to on-site inspections, security audits, and access to data.","Supervision"),
            ctrl("NIS2-Reg-1","National Transposition Compliance","Organisations shall comply with national laws transposing NIS2 across all applicable EU member states.","Regulatory Compliance"),
        ],
    },
    # ── ISO 27701:2019 ────────────────────────────────────────────────────
    {
        "id": "iso27701",
        "name": "ISO 27701:2019",
        "shortName": "ISO 27701",
        "description": "Privacy Information Management System (PIMS) – extension to ISO 27001/27002 specifying requirements and guidance for establishing and maintaining privacy controls; maps directly to GDPR.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("27701-5.2","PIMS-Specific Requirements","Extend the context of the organisation to include privacy considerations and determine interested parties relevant to PII processing.","PIMS Requirements"),
            ctrl("27701-5.4","PIMS Planning","Integrate privacy risk assessment into the information security risk assessment process for the ISMS.","PIMS Requirements"),
            ctrl("27701-6.1.2","Privacy Risk Assessment","Assess risks related to the processing of PII and the ability to exercise PII principal rights.","Privacy Risk Management"),
            ctrl("27701-7.2","Conditions for Collection and Processing","Determine and document the legal basis for each PII processing activity (consent, contract, legitimate interest, legal obligation).","PII Controller Obligations"),
            ctrl("27701-7.3","Obligations to PII Principals","Provide PII principals with transparent information and mechanisms for exercising their rights.","PII Controller Obligations"),
            ctrl("27701-7.3.2","Right of Access","Enable PII principals to access their PII upon verified request.","PII Controller Obligations"),
            ctrl("27701-7.3.3","Right to Rectification","Enable PII principals to correct inaccurate or incomplete PII.","PII Controller Obligations"),
            ctrl("27701-7.3.4","Right to Erasure","Enable PII principals to request deletion of their PII where no legitimate basis for retention exists.","PII Controller Obligations"),
            ctrl("27701-7.3.6","Right to Object","Enable PII principals to object to processing based on legitimate interests or direct marketing.","PII Controller Obligations"),
            ctrl("27701-7.4","Privacy by Design and by Default","Implement privacy-by-design principles and ensure maximum privacy protection is the default setting.","PII Controller Obligations"),
            ctrl("27701-7.5","PII Sharing, Transfer, and Disclosure","Identify and document categories of PII shared with third parties; ensure lawful basis for transfers.","PII Controller Obligations"),
            ctrl("27701-7.5.3","Records of Disclosure","Maintain records of PII disclosed to third parties including categories, dates, purposes, and recipients.","PII Controller Obligations"),
            ctrl("27701-7.6","PII Processors","Engage only PII processors that provide sufficient guarantees; establish binding contracts with processors.","PII Controller Obligations"),
            ctrl("27701-8.2","Conditions for Collection and Processing (Processor)","As PII processor, process PII only on documented instructions from the controller.","PII Processor Obligations"),
            ctrl("27701-8.4","PII Processor Obligations to PII Principals","Assist the controller in fulfilling its obligations to PII principals where applicable.","PII Processor Obligations"),
            ctrl("27701-8.5","Processor Contracts","Ensure binding contracts are in place with sub-processors and that the controller has been informed.","PII Processor Obligations"),
            ctrl("27701-A.7.2","Purpose Limitation","Collect PII only for specified, explicit, and legitimate purposes and ensure it is not processed incompatibly.","Extended Controls"),
            ctrl("27701-A.7.4","Data Minimisation","Ensure PII processed is adequate, relevant, and limited to what is necessary.","Extended Controls"),
            ctrl("27701-A.7.6","Accuracy","Take reasonable steps to ensure PII is accurate and kept up to date.","Extended Controls"),
            ctrl("27701-A.8.1","Privacy Impact Assessment","Conduct a PII impact assessment before commencing high-risk processing activities.","Extended Controls"),
        ],
    },
    # ── SWIFT Customer Security Programme CSCF v2024 ─────────────────────
    {
        "id": "swift_csp",
        "name": "SWIFT CSP CSCF v2024",
        "shortName": "SWIFT CSP",
        "description": "SWIFT Customer Security Controls Framework – mandatory cybersecurity baseline for all SWIFT-connected financial institutions, attested annually with independent validation since 2021.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("SWIFT-1.1","SWIFT Environment Protection","Ensure the protection of the user's local SWIFT infrastructure from potentially compromised elements of the general IT environment.","Restrict Internet Access and Protect Critical Systems"),
            ctrl("SWIFT-1.2","Operating System Privileged Account Control","Restrict and control allocation and usage of operating system accounts with elevated privileges on SWIFT components.","Restrict Internet Access and Protect Critical Systems"),
            ctrl("SWIFT-1.3A","Virtualisation Platform Security","Secure virtualisation platform components from general IT and external environments.","Restrict Internet Access and Protect Critical Systems"),
            ctrl("SWIFT-1.4","Restriction of Internet Access","Restrict internet access from within the secure zone and from systems and components running SWIFT software.","Restrict Internet Access and Protect Critical Systems"),
            ctrl("SWIFT-2.1","Internal Data Flow Security","Authenticate and encrypt application data flows between SWIFT-related applications and infrastructure.","Know and Limit Access"),
            ctrl("SWIFT-2.2","Security Updates","Minimise the occurrence of known technical vulnerabilities within the SWIFT local infrastructure by ensuring vendor support and applying mandatory security updates.","Know and Limit Access"),
            ctrl("SWIFT-2.3","System Hardening","Reduce the cyber-attack surface of SWIFT-related components by performing system hardening.","Know and Limit Access"),
            ctrl("SWIFT-2.4A","Back-office Data Flow Security","Encrypt or protect the confidentiality of SWIFT data at rest and in transit within the operator's back-office environment.","Know and Limit Access"),
            ctrl("SWIFT-2.5A","External Transmission Data Confidentiality","Protect the confidentiality of SWIFT-related data transmitted externally.","Know and Limit Access"),
            ctrl("SWIFT-2.6","Operator Session Confidentiality and Integrity","Protect the confidentiality and integrity of interactive operator sessions.","Know and Limit Access"),
            ctrl("SWIFT-2.7","Vulnerability Scanning","Identify known vulnerabilities within the SWIFT environment by implementing regular vulnerability scan processes.","Know and Limit Access"),
            ctrl("SWIFT-2.9","Transaction Business Controls","Implement transaction business controls and ensure they are aligned with the organization's risk appetite.","Know and Limit Access"),
            ctrl("SWIFT-4.1","Password Policy","Enforce a password policy for all accounts within SWIFT infrastructure.","Know and Limit Access"),
            ctrl("SWIFT-4.2","Multi-Factor Authentication","Prevent the compromise of credentials by enforcing multi-factor authentication for operator accounts connecting to the secure zone.","Know and Limit Access"),
            ctrl("SWIFT-5.1","Logical Access Control","Enforce the principle of least privilege and the need-to-know principle for logical access to SWIFT infrastructure.","Know and Limit Access"),
            ctrl("SWIFT-5.2","Token Management","Manage tokens such as SWIFTNet PKI tokens securely.","Know and Limit Access"),
            ctrl("SWIFT-5.3A","Staff Screening Process","Screen personnel involved in SWIFT-related activities by performing criminal background checks.","Know and Limit Access"),
            ctrl("SWIFT-5.4","Physical Security","Prevent unauthorised physical access to sensitive equipment and work areas.","Know and Limit Access"),
            ctrl("SWIFT-6.1","Malware Protection","Ensure malicious software protection is in place across the SWIFT environment.","Detect and Respond"),
            ctrl("SWIFT-6.2","Software Integrity","Ensure integrity of installed SWIFT software and detect alterations.","Detect and Respond"),
            ctrl("SWIFT-6.3","Database Integrity","Detect and prevent unauthorised access to locally stored SWIFT-related data.","Detect and Respond"),
            ctrl("SWIFT-7.1","Cyber Incident Response Planning","Ensure timely and effective response to cyber incidents.","Detect and Respond"),
            ctrl("SWIFT-7.2","Security Training and Awareness","Ensure all staff in SWIFT-related roles are aware of relevant cyber threats and perform their role accordingly.","Detect and Respond"),
            ctrl("SWIFT-7.3A","Penetration Testing","Validate the operational security of the SWIFT infrastructure by performing penetration tests.","Detect and Respond"),
            ctrl("SWIFT-7.4A","Scenario Risk Assessment","Assess the likely financial impact of a cyber breach scenario on the SWIFT infrastructure.","Detect and Respond"),
        ],
    },
    # ── NIST AI Risk Management Framework 1.0 ────────────────────────────
    {
        "id": "nist_ai_rmf",
        "name": "NIST AI RMF 1.0",
        "shortName": "NIST AI RMF",
        "description": "NIST AI Risk Management Framework – US government-endorsed guidance for managing trustworthy and responsible AI systems across their lifecycle, mandatory for US federal agencies under OMB M-24-10.",
        "status": "Implemented",
        "progress": 100,
        "controls": [
            ctrl("GOVERN-1.1","AI Risk Management Policy","Policies, processes, procedures and practices across the organisation related to the mapping, measuring and managing of AI risks are in place.","GOVERN"),
            ctrl("GOVERN-1.2","Accountability Structures","Accountability processes including documentation are in place to help ensure that AI risks are addressed.","GOVERN"),
            ctrl("GOVERN-1.3","Organisational Teams","Processes and procedures are in place to determine the needed level of risk management activities based on AI risk classification.","GOVERN"),
            ctrl("GOVERN-1.4","Organisational Culture","Organisational teams are committed to a culture that considers and communicates AI risk.","GOVERN"),
            ctrl("GOVERN-2.2","AI Risk Awareness Training","Personnel are trained to understand and apply AI risk concepts throughout the AI lifecycle.","GOVERN"),
            ctrl("GOVERN-3.1","AI Risk Tolerance","AI risk tolerance is established, communicated, and integrated into AI system design.","GOVERN"),
            ctrl("GOVERN-4.1","Third-Party AI Risk","Organisational policies and practices are in place to address risks from third-party AI systems.","GOVERN"),
            ctrl("GOVERN-5.1","Organisational Risk Policies","Organisational risk policies encompass and are informed by AI risks.","GOVERN"),
            ctrl("MAP-1.1","Context Identification","Context is established for the AI system including application, users, organisational context, and risk tolerance.","MAP"),
            ctrl("MAP-1.5","AI Impact Assessment","Likelihood and impact of the AI system's negative effects are evaluated.","MAP"),
            ctrl("MAP-2.1","Scientific Validity","Scientific validity of the assumptions underlying AI risk analysis is established.","MAP"),
            ctrl("MAP-3.5","AI Risk Categorisation","AI risks are categorised and prioritised based on impact and likelihood.","MAP"),
            ctrl("MEASURE-2.1","AI Risk Metrics","AI risk measurement approaches are developed and applied.","MEASURE"),
            ctrl("MEASURE-2.3","Testing Evaluation Verification","AI system performance is evaluated through testing, evaluation, verification, and validation (TEVV).","MEASURE"),
            ctrl("MEASURE-2.6","Bias and Fairness Evaluation","AI system outputs are evaluated for biases, fairness, discrimination, and other potential harms.","MEASURE"),
            ctrl("MEASURE-2.9","Uncertainty Quantification","Predictions and decisions of AI systems include uncertainty metrics.","MEASURE"),
            ctrl("MANAGE-1.1","Prioritised Risk Response","Risks are prioritised based on impact and addressed with appropriately prioritised responses.","MANAGE"),
            ctrl("MANAGE-2.4","AI Incident Response","Residual negative risks are tracked and managed with defined response procedures.","MANAGE"),
            ctrl("MANAGE-3.1","AI System Decommissioning","AI risks are tracked for deployed systems and decommissioning plans are in place.","MANAGE"),
            ctrl("MANAGE-4.1","Risk Treatment Monitoring","Post-deployment AI risks and performance are continuously monitored.","MANAGE"),
        ],
    },
]
