"""Compliance control definitions: ctrl helper, ISO 27001:2022, SOC 2."""

TODAY = "2024-01-15"


def ctrl(cid, name, desc, cat, status="Implemented"):
    return {"id": cid, "name": name, "description": desc, "category": cat,
            "status": "Implemented", "lastReviewed": TODAY, "evidence": []}


ISO27001_CONTROLS = [
    # A.5 Organizational (37)
    ctrl("A.5.1",  "Policies for Information Security",
         "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated and acknowledged by relevant personnel.",
         "Organizational", "Implemented"),
    ctrl("A.5.2",  "Information Security Roles and Responsibilities",
         "Information security roles and responsibilities shall be defined and allocated according to organisation needs.",
         "Organizational", "Implemented"),
    ctrl("A.5.3",  "Segregation of Duties",
         "Conflicting duties and conflicting areas of responsibility shall be segregated.",
         "Organizational", "Implemented"),
    ctrl("A.5.4",  "Management Responsibilities",
         "Management shall require all personnel to apply information security in accordance with established policy.",
         "Organizational", "Implemented"),
    ctrl("A.5.5",  "Contact with Authorities",
         "The organisation shall establish and maintain contact with relevant authorities.",
         "Organizational", "Implemented"),
    ctrl("A.5.6",  "Contact with Special Interest Groups",
         "The organisation shall establish and maintain contact with special interest groups or forums and professional associations.",
         "Organizational", "In Progress"),
    ctrl("A.5.7",  "Threat Intelligence",
         "Information relating to information security threats shall be collected and analysed to produce threat intelligence.",
         "Organizational", "At Risk"),
    ctrl("A.5.8",  "Information Security in Project Management",
         "Information security shall be integrated into project management.",
         "Organizational", "In Progress"),
    ctrl("A.5.9",  "Inventory of Information and Other Associated Assets",
         "An inventory of information and other associated assets, including owners, shall be developed and maintained.",
         "Organizational", "Implemented"),
    ctrl("A.5.10", "Acceptable Use of Information and Other Associated Assets",
         "Rules for the acceptable use and procedures for handling information and other associated assets shall be identified, documented and implemented.",
         "Organizational", "Implemented"),
    ctrl("A.5.11", "Return of Assets",
         "Personnel and other interested party users shall return all the organisation's assets in their possession upon change or termination of their employment.",
         "Organizational", "Implemented"),
    ctrl("A.5.12", "Classification of Information",
         "Information shall be classified according to the information security needs of the organisation.",
         "Organizational", "Implemented"),
    ctrl("A.5.13", "Labelling of Information",
         "An appropriate set of procedures for information labelling shall be developed and implemented.",
         "Organizational", "In Progress"),
    ctrl("A.5.14", "Information Transfer",
         "Information transfer rules, procedures, or agreements shall be in place for all types of transfer facilities.",
         "Organizational", "Implemented"),
    ctrl("A.5.15", "Access Control",
         "Rules to control physical and logical access to information and other associated assets shall be established and implemented based on business and information security requirements.",
         "Organizational", "Implemented"),
    ctrl("A.5.16", "Identity Management",
         "The full life cycle of identities shall be managed.",
         "Organizational", "Implemented"),
    ctrl("A.5.17", "Authentication Information",
         "Allocation and management of authentication information shall be controlled by a management process.",
         "Organizational", "Implemented"),
    ctrl("A.5.18", "Access Rights",
         "Access rights to information and other associated assets shall be provisioned, reviewed, modified and removed in accordance with the organisation's topic-specific policy on access control.",
         "Organizational", "Implemented"),
    ctrl("A.5.19", "Information Security in Supplier Relationships",
         "Processes and procedures shall be defined and implemented to manage the information security risks associated with the use of supplier's products or services.",
         "Organizational", "In Progress"),
    ctrl("A.5.20", "Addressing Information Security within Supplier Agreements",
         "Relevant information security requirements shall be established and agreed with each supplier based on the type of supplier relationship.",
         "Organizational", "In Progress"),
    ctrl("A.5.21", "Managing Information Security in the ICT Supply Chain",
         "Processes and procedures shall be defined and implemented to manage the information security risks associated with the ICT products and services supply chain.",
         "Organizational", "Not Implemented"),
    ctrl("A.5.22", "Monitoring, Review and Change Management of Supplier Services",
         "The organisation shall regularly monitor, review, evaluate and manage change in supplier information security practices and service delivery.",
         "Organizational", "In Progress"),
    ctrl("A.5.23", "Information Security for Use of Cloud Services",
         "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organisation's information security requirements.",
         "Organizational", "In Progress"),
    ctrl("A.5.24", "Information Security Incident Management Planning and Preparation",
         "The organisation shall plan and prepare for managing information security incidents by defining, establishing and communicating information security incident management processes, roles and responsibilities.",
         "Organizational", "Implemented"),
    ctrl("A.5.25", "Assessment and Decision on Information Security Events",
         "The organisation shall assess information security events and decide if they are to be categorised as information security incidents.",
         "Organizational", "Implemented"),
    ctrl("A.5.26", "Response to Information Security Incidents",
         "Information security incidents shall be responded to in accordance with the documented procedures.",
         "Organizational", "Implemented"),
    ctrl("A.5.27", "Learning from Information Security Incidents",
         "Knowledge gained from information security incidents shall be used to strengthen and improve the information security controls.",
         "Organizational", "In Progress"),
    ctrl("A.5.28", "Collection of Evidence",
         "The organisation shall establish and implement procedures for the identification, collection, acquisition and preservation of evidence related to information security events.",
         "Organizational", "Not Implemented"),
    ctrl("A.5.29", "Information Security During Disruption",
         "The organisation shall plan how to maintain information security at an appropriate level during disruption.",
         "Organizational", "In Progress"),
    ctrl("A.5.30", "ICT Readiness for Business Continuity",
         "ICT readiness shall be planned, implemented, maintained and tested based on business continuity objectives and ICT continuity requirements.",
         "Organizational", "Not Implemented"),
    ctrl("A.5.31", "Legal, Statutory, Regulatory and Contractual Requirements",
         "Legal, statutory, regulatory and contractual requirements relevant to information security and the organisation's approach to meet these requirements shall be identified, documented and kept up to date.",
         "Organizational", "Implemented"),
    ctrl("A.5.32", "Intellectual Property Rights",
         "The organisation shall implement appropriate procedures to protect intellectual property rights.",
         "Organizational", "Implemented"),
    ctrl("A.5.33", "Protection of Records",
         "Records shall be protected from loss, destruction, falsification, unauthorised access and unauthorised release.",
         "Organizational", "Implemented"),
    ctrl("A.5.34", "Privacy and Protection of PII",
         "The organisation shall identify and meet the requirements regarding the preservation of privacy and protection of PII according to applicable laws and regulations.",
         "Organizational", "In Progress"),
    ctrl("A.5.35", "Independent Review of Information Security",
         "The organisation's approach to managing information security and its implementation including people, processes and technologies shall be reviewed independently at planned intervals.",
         "Organizational", "Not Implemented"),
    ctrl("A.5.36", "Compliance with Policies, Rules and Standards for Information Security",
         "Compliance with the organisation's information security policy, topic-specific policies, rules and standards shall be regularly reviewed.",
         "Organizational", "Implemented"),
    ctrl("A.5.37", "Documented Operating Procedures",
         "Operating procedures for information processing facilities shall be documented and made available to personnel who need them.",
         "Organizational", "Implemented"),
    # A.6 People (8)
    ctrl("A.6.1",  "Screening",
         "Background verification checks on all candidates for employment shall be carried out prior to joining the organisation.",
         "People", "Implemented"),
    ctrl("A.6.2",  "Terms and Conditions of Employment",
         "Employment contractual agreements shall state the personnel's and the organisation's responsibilities for information security.",
         "People", "Implemented"),
    ctrl("A.6.3",  "Information Security Awareness, Education and Training",
         "Personnel of the organisation and relevant interested parties shall receive appropriate information security awareness, education and training.",
         "People", "Implemented"),
    ctrl("A.6.4",  "Disciplinary Process",
         "A disciplinary process shall be formalised and communicated to take actions against personnel and other relevant interested parties who have committed an information security policy violation.",
         "People", "Implemented"),
    ctrl("A.6.5",  "Responsibilities After Termination or Change of Employment",
         "Information security responsibilities and duties that remain valid after termination or change of employment shall be defined, enforced and communicated to relevant personnel.",
         "People", "Implemented"),
    ctrl("A.6.6",  "Confidentiality or Non-Disclosure Agreements",
         "Confidentiality or non-disclosure agreements reflecting the organisation's needs for the protection of information shall be identified, documented, regularly reviewed and signed by personnel and other relevant interested parties.",
         "People", "Implemented"),
    ctrl("A.6.7",  "Remote Working",
         "Security measures shall be implemented when personnel are working remotely to protect information accessed, processed or stored outside the organisation's premises.",
         "People", "Implemented"),
    ctrl("A.6.8",  "Information Security Event Reporting",
         "The organisation shall provide a mechanism for personnel to report observed or suspected information security events through appropriate channels in a timely manner.",
         "People", "Implemented"),
    # A.7 Physical (14)
    ctrl("A.7.1",  "Physical Security Perimeters",
         "Security perimeters shall be defined and used to protect areas that contain information and other associated assets.",
         "Physical", "Implemented"),
    ctrl("A.7.2",  "Physical Entry",
         "Secure areas shall be protected by appropriate entry controls and access points.",
         "Physical", "Implemented"),
    ctrl("A.7.3",  "Securing Offices, Rooms and Facilities",
         "Physical security for offices, rooms and facilities shall be designed and implemented.",
         "Physical", "Implemented"),
    ctrl("A.7.4",  "Physical Security Monitoring",
         "Premises shall be continuously monitored for unauthorized physical access.",
         "Physical", "In Progress"),
    ctrl("A.7.5",  "Protecting Against Physical and Environmental Threats",
         "Protection against physical and environmental threats, such as natural disasters and other intentional or unintentional physical threats to infrastructure shall be designed and implemented.",
         "Physical", "Implemented"),
    ctrl("A.7.6",  "Working in Secure Areas",
         "Security measures for working in secure areas shall be designed and implemented.",
         "Physical", "Implemented"),
    ctrl("A.7.7",  "Clear Desk and Clear Screen",
         "Clear desk rules for papers and removable storage media and clear screen rules for information processing facilities shall be defined and appropriately enforced.",
         "Physical", "Implemented"),
    ctrl("A.7.8",  "Equipment Siting and Protection",
         "Equipment shall be sited securely and protected.",
         "Physical", "Implemented"),
    ctrl("A.7.9",  "Security of Assets Off-Premises",
         "Off-site assets shall be protected.",
         "Physical", "In Progress"),
    ctrl("A.7.10", "Storage Media",
         "Storage media shall be managed through their life cycle of acquisition, use, transportation and disposal in accordance with the organisation's classification scheme and handling requirements.",
         "Physical", "Implemented"),
    ctrl("A.7.11", "Supporting Utilities",
         "Information processing facilities shall be protected from power failures and other disruptions caused by failures in supporting utilities.",
         "Physical", "Implemented"),
    ctrl("A.7.12", "Cabling Security",
         "Cables carrying power, data or supporting information services shall be protected from interception, interference or damage.",
         "Physical", "Not Implemented"),
    ctrl("A.7.13", "Equipment Maintenance",
         "Equipment shall be maintained correctly to ensure availability, integrity and confidentiality of information.",
         "Physical", "Implemented"),
    ctrl("A.7.14", "Secure Disposal or Re-Use of Equipment",
         "Items of equipment containing storage media shall be verified to ensure that any sensitive data and licensed software has been removed or securely overwritten prior to disposal or re-use.",
         "Physical", "Implemented"),
    # A.8 Technological (34)
    ctrl("A.8.1",  "User Endpoint Devices",
         "Information stored on, processed by or accessible via user endpoint devices shall be protected.",
         "Technological", "Implemented"),
    ctrl("A.8.2",  "Privileged Access Rights",
         "The allocation and use of privileged access rights shall be restricted and managed.",
         "Technological", "In Progress"),
    ctrl("A.8.3",  "Information Access Restriction",
         "Access to information and other associated assets shall be restricted in accordance with the established topic-specific policy on access control.",
         "Technological", "Implemented"),
    ctrl("A.8.4",  "Access to Source Code",
         "Read and write access to source code, development tools and software libraries shall be appropriately managed.",
         "Technological", "Implemented"),
    ctrl("A.8.5",  "Secure Authentication",
         "Secure authentication technologies and procedures shall be implemented based on information access restrictions and the topic-specific policy on access control.",
         "Technological", "Implemented"),
    ctrl("A.8.6",  "Capacity Management",
         "The use of resources shall be monitored and adjusted in line with current and expected capacity requirements.",
         "Technological", "In Progress"),
    ctrl("A.8.7",  "Protection Against Malware",
         "Protection against malware shall be implemented and supported by appropriate user awareness.",
         "Technological", "Implemented"),
    ctrl("A.8.8",  "Management of Technical Vulnerabilities",
         "Information about technical vulnerabilities of information systems in use shall be obtained in a timely fashion.",
         "Technological", "At Risk"),
    ctrl("A.8.9",  "Configuration Management",
         "Configurations, including security configurations, of hardware, software, services and networks shall be established, documented, implemented, monitored and reviewed.",
         "Technological", "In Progress"),
    ctrl("A.8.10", "Information Deletion",
         "Information stored in information systems, devices or in any other storage media shall be deleted when no longer required.",
         "Technological", "Not Implemented"),
    ctrl("A.8.11", "Data Masking",
         "Data masking shall be used in accordance with the organisation's topic-specific policy on access control and other related topic-specific policies, and business requirements, taking applicable legislation into consideration.",
         "Technological", "Not Implemented"),
    ctrl("A.8.12", "Data Leakage Prevention",
         "Data leakage prevention measures shall be applied to systems, networks and any other devices that process, store or transmit sensitive information.",
         "Technological", "Not Implemented"),
    ctrl("A.8.13", "Information Backup",
         "Backup copies of information, software and systems shall be maintained and regularly tested in accordance with the agreed topic-specific policy on backup.",
         "Technological", "Implemented"),
    ctrl("A.8.14", "Redundancy of Information Processing Facilities",
         "Information processing facilities shall be implemented with redundancy sufficient to meet availability requirements.",
         "Technological", "Implemented"),
    ctrl("A.8.15", "Logging",
         "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analysed.",
         "Technological", "Implemented"),
    ctrl("A.8.16", "Monitoring Activities",
         "Networks, systems and applications shall be monitored for anomalous behaviour and appropriate actions taken to evaluate potential information security incidents.",
         "Technological", "Implemented"),
    ctrl("A.8.17", "Clock Synchronisation",
         "The clocks of information processing systems used by the organisation shall be synchronised to approved time sources.",
         "Technological", "Implemented"),
    ctrl("A.8.18", "Use of Privileged Utility Programs",
         "The use of utility programs that might be capable of overriding system and application controls shall be restricted and tightly controlled.",
         "Technological", "In Progress"),
    ctrl("A.8.19", "Installation of Software on Operational Systems",
         "Procedures and measures shall be implemented to securely manage software installation on operational systems.",
         "Technological", "Implemented"),
    ctrl("A.8.20", "Networks Security",
         "Networks and network devices shall be secured, managed and controlled to protect information in systems and applications.",
         "Technological", "Implemented"),
    ctrl("A.8.21", "Security of Network Services",
         "Security mechanisms, service levels and service requirements of network services shall be identified, implemented and monitored.",
         "Technological", "Implemented"),
    ctrl("A.8.22", "Segregation of Networks",
         "Groups of information services, users and information systems shall be segregated in the organisation's networks.",
         "Technological", "Implemented"),
    ctrl("A.8.23", "Web Filtering",
         "Access to external websites shall be managed to reduce exposure to malicious content.",
         "Technological", "Implemented"),
    ctrl("A.8.24", "Use of Cryptography",
         "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
         "Technological", "Implemented"),
    ctrl("A.8.25", "Secure Development Life Cycle",
         "Rules for the secure development of software and systems shall be established and applied.",
         "Technological", "In Progress"),
    ctrl("A.8.26", "Application Security Requirements",
         "Information security requirements shall be identified, specified and approved when developing or acquiring applications.",
         "Technological", "In Progress"),
    ctrl("A.8.27", "Secure System Architecture and Engineering Principles",
         "Principles for engineering secure systems shall be established, documented, maintained and applied to any information system development activities.",
         "Technological", "In Progress"),
    ctrl("A.8.28", "Secure Coding",
         "Secure coding principles shall be applied to software development.",
         "Technological", "In Progress"),
    ctrl("A.8.29", "Security Testing in Development and Acceptance",
         "Security testing processes shall be defined and implemented in the development life cycle.",
         "Technological", "Not Implemented"),
    ctrl("A.8.30", "Outsourced Development",
         "The organisation shall supervise and monitor the activity related to outsourced system development.",
         "Technological", "In Progress"),
    ctrl("A.8.31", "Separation of Development, Test and Production Environments",
         "Development, testing and production environments shall be separated and secured.",
         "Technological", "Implemented"),
    ctrl("A.8.32", "Change Management",
         "Changes to information processing facilities and information systems shall be subject to change management procedures.",
         "Technological", "Implemented"),
    ctrl("A.8.33", "Test Information",
         "Test information shall be appropriately selected, protected and managed.",
         "Technological", "In Progress"),
    ctrl("A.8.34", "Protection of Information Systems During Audit Testing",
         "Audit tests and other assurance activities involving assessment of operational systems shall be planned and agreed between the tester and appropriate management.",
         "Technological", "Not Implemented"),
]

# ── SOC 2 – full Trust Services Criteria ─────────────────────────────────────
SOC2_CONTROLS = [
    # CC1 – Control Environment
    ctrl("CC1.1","COSO Principle 1: Integrity and Ethical Values","The entity demonstrates a commitment to integrity and ethical values.","Control Environment","Implemented"),
    ctrl("CC1.2","COSO Principle 2: Board Independence","The board of directors demonstrates independence from management and exercises oversight of the development and performance of internal control.","Control Environment","Implemented"),
    ctrl("CC1.3","COSO Principle 3: Management Structures","Management establishes, with board oversight, structures, reporting lines, and appropriate authorities and responsibilities in pursuit of objectives.","Control Environment","Implemented"),
    ctrl("CC1.4","COSO Principle 4: Competence","The entity demonstrates a commitment to attract, develop, and retain competent individuals in alignment with objectives.","Control Environment","Implemented"),
    ctrl("CC1.5","COSO Principle 5: Accountability","The entity holds individuals accountable for their internal control responsibilities in the pursuit of objectives.","Control Environment","Implemented"),
    # CC2 – Communication and Information
    ctrl("CC2.1","COSO Principle 6: Objectives","The entity specifies objectives with sufficient clarity to enable the identification and assessment of risks relating to objectives.","Communication and Information","Implemented"),
    ctrl("CC2.2","COSO Principle 7: Internal Communication","The entity internally communicates information, including objectives and responsibilities for internal control, necessary to support the functioning of internal control.","Communication and Information","Implemented"),
    ctrl("CC2.3","COSO Principle 8: External Communication","The entity communicates with external parties regarding matters affecting the functioning of internal control.","Communication and Information","In Progress"),
    # CC3 – Risk Assessment
    ctrl("CC3.1","COSO Principle 9: Objectives and Risk Assessment","The entity identifies risks to the achievement of its objectives across the entity and analyzes risks as a basis for determining how the risks should be managed.","Risk Assessment","At Risk"),
    ctrl("CC3.2","COSO Principle 10: Fraud Risk","The entity considers the potential for fraud in assessing risks to the achievement of objectives.","Risk Assessment","In Progress"),
    ctrl("CC3.3","COSO Principle 11: Identify and Assess Change","The entity identifies and assesses changes that could significantly impact the system of internal control.","Risk Assessment","In Progress"),
    # CC4 – Monitoring
    ctrl("CC4.1","COSO Principle 16: Ongoing Evaluations","The entity selects, develops, and performs ongoing and/or separate evaluations to ascertain whether the components of internal control are present and functioning.","Monitoring Activities","Implemented"),
    ctrl("CC4.2","COSO Principle 17: Evaluate and Communicate Deficiencies","The entity evaluates and communicates internal control deficiencies in a timely manner to those parties responsible for taking corrective action.","Monitoring Activities","Implemented"),
    # CC5 – Control Activities
    ctrl("CC5.1","COSO Principle 13: Control Activities","The entity selects and develops control activities that contribute to the mitigation of risks to the achievement of objectives to acceptable levels.","Control Activities","Implemented"),
    ctrl("CC5.2","COSO Principle 14: Technology Controls","The entity also selects and develops general control activities over technology to support the achievement of objectives.","Control Activities","Implemented"),
    ctrl("CC5.3","COSO Principle 15: Policies and Procedures","The entity deploys control activities through policies that establish what is expected and in procedures that put policies into action.","Control Activities","Implemented"),
    # CC6 – Logical and Physical Access
    ctrl("CC6.1","Logical Access Security","The entity implements logical access security software, infrastructure, and architectures over protected information assets to protect them from security events to meet the entity's objectives.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.2","User Registration and Authorization","Prior to issuing system credentials and granting system access, the entity registers and authorizes new internal and external users whose access is administered by the entity.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.3","Access Management","The entity authorizes, modifies, or removes access to data, software, functions, and other protected information assets based on approved requests.","Logical and Physical Access Controls","In Progress"),
    ctrl("CC6.4","Physical Access","The entity restricts physical access to facilities and protected information assets to authorized personnel to meet the entity's objectives.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.5","Discontinued Credentials","The entity discontinues logical and physical protections over physical assets only after the ability to use them to access applicable assets and information has been removed.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.6","External Threats","The entity implements logical access security measures to protect against threats from sources outside its system boundaries.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.7","Transmission Protection","The entity restricts the transmission, movement, and removal of information to authorized internal and external users and processes, and protects it during transmission.","Logical and Physical Access Controls","Implemented"),
    ctrl("CC6.8","Malicious Software Prevention","The entity implements controls to prevent or detect and act upon the introduction of unauthorized or malicious software to meet the entity's objectives.","Logical and Physical Access Controls","Implemented"),
    # CC7 – System Operations
    ctrl("CC7.1","Configuration Management","To meet its objectives, the entity uses detection and monitoring procedures to identify changes to configurations that result in the introduction of new vulnerabilities.","System Operations","In Progress"),
    ctrl("CC7.2","Vulnerability Management","The entity monitors system components and the operation of those components for anomalies that are indicative of malicious acts, natural disasters, and errors affecting the entity's ability to meet its objectives.","System Operations","At Risk"),
    ctrl("CC7.3","Incident Evaluation","The entity evaluates security events to determine whether they could or have resulted in a failure of the entity to meet its objectives and, if so, takes actions to prevent or address such failures.","System Operations","Implemented"),
    ctrl("CC7.4","Incident Response","The entity responds to identified security incidents by executing a defined incident response program to understand, contain, remediate, and communicate security incidents.","System Operations","Implemented"),
    ctrl("CC7.5","Disaster Recovery","The entity identifies, develops, and implements activities to recover from identified security incidents.","System Operations","Not Implemented"),
    # CC8 – Change Management
    ctrl("CC8.1","Change Management","The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements changes to infrastructure, data, software, and procedures to meet its objectives.","Change Management","Implemented"),
    # CC9 – Risk Mitigation
    ctrl("CC9.1","Business Disruption Risk Mitigation","The entity identifies, selects, and develops risk mitigation activities for risks arising from potential business disruptions.","Risk Mitigation","Implemented"),
    ctrl("CC9.2","Vendor and Business Partner Management","The entity assesses and manages risks associated with vendors and business partners.","Risk Mitigation","In Progress"),
    # A – Availability
    ctrl("A1.1","Capacity Management","The entity maintains, monitors, and evaluates current processing capacity and use of system components to manage capacity demand and to enable the implementation of additional capacity to help meet its objectives.","Availability","Implemented"),
    ctrl("A1.2","Environmental and Physical Protection","The entity authorizes, designs, develops or acquires, configures, documents, tests, approves, and implements environmental protections, software, data back-up processes, and recovery infrastructure to meet its availability objectives.","Availability","Implemented"),
    ctrl("A1.3","Recovery","The entity tests recovery plan procedures supporting system recovery to meet its availability objectives.","Availability","In Progress"),
    # C – Confidentiality
    ctrl("C1.1","Confidential Information Identification","The entity identifies and maintains confidential information to meet the entity's objectives related to confidentiality.","Confidentiality","Implemented"),
    ctrl("C1.2","Confidential Information Protection and Disposal","The entity disposes of confidential information to meet the entity's objectives related to confidentiality.","Confidentiality","Implemented"),
    # PI – Processing Integrity
    ctrl("PI1.1","Processing Integrity Procedures","The entity obtains or generates, uses, and communicates relevant, quality information regarding the objectives related to processing, including definitions of data processed and product and service specifications.","Processing Integrity","Implemented"),
    ctrl("PI1.2","System Inputs","The entity implements policies and procedures over system inputs, including controls over completeness and accuracy, to result in products, services, and reporting to meet the entity's objectives.","Processing Integrity","Implemented"),
    ctrl("PI1.3","System Processing","The entity implements policies and procedures over system processing to result in products, services, and reporting to meet the entity's objectives.","Processing Integrity","Implemented"),
    ctrl("PI1.4","System Outputs","The entity implements policies and procedures to make available or deliver output completely, accurately, and timely in accordance with specifications.","Processing Integrity","Implemented"),
    ctrl("PI1.5","Stored Items","The entity implements policies and procedures to store inputs, items in processing, and outputs completely, accurately, and timely in accordance with system specifications.","Processing Integrity","In Progress"),
    # P – Privacy
    ctrl("P1.0","Privacy Notice","The entity provides notice to data subjects about its privacy practices to meet the entity's objectives related to privacy.","Privacy","Implemented"),
    ctrl("P2.0","Choice and Consent","The entity communicates choices available regarding the collection, use, retention, disclosure, and disposal of personal information to the data subjects.","Privacy","Implemented"),
    ctrl("P3.0","Collection","The entity collects personal information to meet its objectives related to privacy.","Privacy","Implemented"),
    ctrl("P4.0","Use, Retention and Disposal","The entity limits the use of personal information to the purposes identified in the notice and manages retention and disposal of personal information.","Privacy","In Progress"),
    ctrl("P5.0","Access","The entity grants identified and authenticated data subjects the ability to access their stored personal information.","Privacy","Implemented"),
    ctrl("P6.0","Disclosure and Notification","The entity discloses personal information, with the consent of the data subjects, to third parties and manages breaches.","Privacy","Implemented"),
    ctrl("P7.0","Quality","The entity collects and maintains accurate, up-to-date, complete, and relevant personal information.","Privacy","In Progress"),
    ctrl("P8.0","Monitoring and Enforcement","The entity monitors compliance to its privacy commitments and provides recourse for data subjects.","Privacy","In Progress"),
]

