"""Compliance framework definitions (part 1): SOC 1/2/3, ISO 27001, PCI DSS, NIST, HIPAA, GDPR, FedRAMP, HITRUST, CMMC, CSA."""

from seed_compliance_controls_a import ISO27001_CONTROLS, SOC2_CONTROLS
from seed_compliance_controls_b import (
    PCI_CONTROLS, NIST_CONTROLS, HIPAA_CONTROLS, GDPR_CONTROLS,
    FEDRAMP_CONTROLS, HITRUST_CONTROLS, CMMC_CONTROLS, CSA_CONTROLS,
)
from seed_compliance_soc_controls import SOC1_CONTROLS, SOC3_CONTROLS, SOC_CYBER_CONTROLS


FRAMEWORKS_PART1 = [
    {
        "id": "soc1_type1",
        "name": "SOC 1 Type I (SSAE 18)",
        "shortName": "SOC 1 Type I",
        "description": "Service Organization Controls for Internal Controls over Financial Reporting – point-in-time assessment of control design and implementation under SSAE 18 / ISAE 3402.",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC1_CONTROLS,
    },
    {
        "id": "soc1_type2",
        "name": "SOC 1 Type II (SSAE 18)",
        "shortName": "SOC 1 Type II",
        "description": "Service Organization Controls for Internal Controls over Financial Reporting – operating effectiveness of controls over a specified period (typically 6–12 months) under SSAE 18 / ISAE 3402.",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC1_CONTROLS,
    },
    {
        "id": "soc2",
        "name": "SOC 2 Type II",
        "shortName": "SOC 2 Type II",
        "description": "Service Organization Control 2 – Trust Services Criteria operating effectiveness over a period (Security, Availability, Confidentiality, Processing Integrity, Privacy)",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC2_CONTROLS,
    },
    {
        "id": "soc2_type1",
        "name": "SOC 2 Type I",
        "shortName": "SOC 2 Type I",
        "description": "Service Organization Control 2 – Trust Services Criteria design and implementation at a specific point in time (Security, Availability, Confidentiality, Processing Integrity, Privacy).",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC2_CONTROLS,
    },
    {
        "id": "soc3",
        "name": "SOC 3",
        "shortName": "SOC 3",
        "description": "General Use Report – public-facing summary of SOC 2 Trust Services Criteria results; provides the same assurance as SOC 2 without restricted distribution requirements.",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC3_CONTROLS,
    },
    {
        "id": "soc_cybersecurity",
        "name": "SOC for Cybersecurity",
        "shortName": "SOC Cyber",
        "description": "AICPA examination of an entity's enterprise-wide cybersecurity risk management program; includes Description Criteria and Trust Services Criteria applied to cybersecurity objectives.",
        "status": "Implemented",
        "progress": 100,
        "controls": SOC_CYBER_CONTROLS,
    },
    {
        "id": "iso27001",
        "name": "ISO/IEC 27001:2022",
        "shortName": "ISO 27001",
        "description": "Information Security Management System – all 93 Annex A controls across Organizational, People, Physical and Technological categories",
        "status": "In Progress",
        "progress": 60,
        "controls": ISO27001_CONTROLS,
    },
    {
        "id": "pci-dss",
        "name": "Payment Card Industry Data Security Standard v4.0",
        "shortName": "PCI DSS",
        "description": "Cardholder data protection standard – 12 requirements",
        "status": "In Progress",
        "progress": 80,
        "controls": PCI_CONTROLS,
    },
    {
        "id": "nistcsf",
        "name": "NIST Cybersecurity Framework v2.0",
        "shortName": "NIST CSF",
        "description": "US NIST Framework – Govern, Identify, Protect, Detect, Respond, Recover",
        "status": "In Progress",
        "progress": 85,
        "nistFunctions": [
            {"id": "govern",   "name": "Govern",   "progress": 90},
            {"id": "identify", "name": "Identify", "progress": 95},
            {"id": "protect",  "name": "Protect",  "progress": 88},
            {"id": "detect",   "name": "Detect",   "progress": 90},
            {"id": "respond",  "name": "Respond",  "progress": 80},
            {"id": "recover",  "name": "Recover",  "progress": 70},
        ],
        "controls": NIST_CONTROLS,
    },
    {
        "id": "hipaa",
        "name": "HIPAA Security Rule",
        "shortName": "HIPAA",
        "description": "Health Insurance Portability and Accountability Act – complete Administrative, Physical and Technical Safeguards",
        "status": "In Progress",
        "progress": 60,
        "controls": HIPAA_CONTROLS,
    },
    {
        "id": "gdpr",
        "name": "General Data Protection Regulation (GDPR)",
        "shortName": "GDPR",
        "description": "EU Regulation 2016/679 – Data Protection and Privacy",
        "status": "In Progress",
        "progress": 40,
        "controls": GDPR_CONTROLS,
    },
    {
        "id": "fedramp_moderate",
        "name": "FedRAMP Moderate",
        "shortName": "FedRAMP",
        "description": "Federal Risk and Authorization Management Program – Moderate Baseline",
        "status": "In Progress",
        "progress": 55,
        "controls": FEDRAMP_CONTROLS,
    },
    {
        "id": "hitrust_csf",
        "name": "HITRUST CSF v11",
        "shortName": "HITRUST",
        "description": "Health Information Trust Alliance Common Security Framework",
        "status": "In Progress",
        "progress": 45,
        "controls": HITRUST_CONTROLS,
    },
    {
        "id": "cmmc_l2",
        "name": "CMMC 2.0 Level 2",
        "shortName": "CMMC",
        "description": "Cybersecurity Maturity Model Certification – Advanced (110 practices aligned to NIST SP 800-171)",
        "status": "In Progress",
        "progress": 40,
        "controls": CMMC_CONTROLS,
    },
    {
        "id": "csa_star",
        "name": "CSA STAR (CCM v4)",
        "shortName": "CSA STAR",
        "description": "Cloud Security Alliance Cloud Controls Matrix – cloud-specific security controls",
        "status": "In Progress",
        "progress": 55,
        "controls": CSA_CONTROLS,
    },
]
