"""Kubernetes security check definitions. Used by cloud_checks_service.py."""
K8S_CHECKS = [
    # ─── RBAC ───────────────────────────────────────────────────────────────
    {"id": "k8s-rbac-001", "name": "No anonymous API server access", "description": "Kubernetes API server must not allow anonymous authentication", "provider": "kubernetes", "service": "rbac", "severity": "critical", "frameworks": ["CIS-K8s-1.2.1", "NIST-AC-3", "NSA-K8s"], "remediation": "Set --anonymous-auth=false on the API server."},
    {"id": "k8s-rbac-002", "name": "RBAC enabled", "description": "Role-Based Access Control must be enabled on the API server", "provider": "kubernetes", "service": "rbac", "severity": "critical", "frameworks": ["CIS-K8s-1.2.7", "NIST-AC-3", "SOC2-CC6.3"], "remediation": "Set --authorization-mode=RBAC (or Node,RBAC) on the API server."},
    {"id": "k8s-rbac-003", "name": "No cluster-admin rolebinding to service accounts", "description": "Service accounts must not be bound to the cluster-admin ClusterRole", "provider": "kubernetes", "service": "rbac", "severity": "critical", "frameworks": ["CIS-K8s-5.1.1", "NIST-AC-6"], "remediation": "Remove cluster-admin ClusterRoleBindings for service accounts; use least-privilege roles."},
    {"id": "k8s-rbac-004", "name": "No wildcard verbs on core resources", "description": "ClusterRoles must not grant wildcard (*) verbs on core API group resources", "provider": "kubernetes", "service": "rbac", "severity": "high", "frameworks": ["CIS-K8s-5.1.3", "NIST-AC-6"], "remediation": "Replace wildcard verb rules in ClusterRoles with explicit allowed verbs."},
    # ─── Network ────────────────────────────────────────────────────────────
    {"id": "k8s-network-001", "name": "Network policies enforced", "description": "All namespaces must have at least one NetworkPolicy to restrict pod traffic", "provider": "kubernetes", "service": "network", "severity": "high", "frameworks": ["CIS-K8s-5.3.2", "NIST-SC-7", "NSA-K8s"], "remediation": "Apply NetworkPolicy objects to restrict pod-to-pod communication."},
    {"id": "k8s-network-002", "name": "API server not exposed on public internet", "description": "Kubernetes API server endpoint must not be publicly accessible", "provider": "kubernetes", "service": "network", "severity": "critical", "frameworks": ["CIS-K8s-1.2.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable authorized IP ranges or private endpoint on managed Kubernetes clusters."},
    # ─── Secrets ────────────────────────────────────────────────────────────
    {"id": "k8s-secrets-001", "name": "Secrets encrypted at rest in etcd", "description": "Kubernetes Secrets must be encrypted at rest in etcd using a KMS provider", "provider": "kubernetes", "service": "secrets", "severity": "critical", "frameworks": ["CIS-K8s-1.2.33", "NIST-SC-28", "PCI-3.4"], "remediation": "Configure EncryptionConfiguration with a KMS provider for Secrets resources."},
    {"id": "k8s-secrets-002", "name": "No plaintext secrets in Pod environment variables", "description": "Container environment variables must not contain sensitive values directly", "provider": "kubernetes", "service": "secrets", "severity": "high", "frameworks": ["CIS-K8s-5.4.1", "NIST-SA-3"], "remediation": "Reference Kubernetes Secrets via secretKeyRef rather than hardcoded env values."},
    # ─── Pods ───────────────────────────────────────────────────────────────
    {"id": "k8s-pods-001", "name": "Pod Security Admission enforced (restricted profile)", "description": "Namespaces must enforce Pod Security Admission with at minimum baseline profile", "provider": "kubernetes", "service": "pods", "severity": "high", "frameworks": ["CIS-K8s-5.2.1", "NIST-SI-3", "NSA-K8s"], "remediation": "Add pod-security.kubernetes.io/enforce labels to namespaces."},
    {"id": "k8s-pods-002", "name": "Containers do not run as root", "description": "All containers must set runAsNonRoot: true or runAsUser != 0", "provider": "kubernetes", "service": "pods", "severity": "high", "frameworks": ["CIS-K8s-5.2.6", "NIST-AC-6", "NSA-K8s"], "remediation": "Set securityContext.runAsNonRoot: true in pod specs."},
    {"id": "k8s-pods-003", "name": "Containers have read-only root filesystem", "description": "Container root filesystems should be read-only to limit persistence", "provider": "kubernetes", "service": "pods", "severity": "medium", "frameworks": ["CIS-K8s-5.2.4", "NIST-SI-7", "NSA-K8s"], "remediation": "Set securityContext.readOnlyRootFilesystem: true in container specs."},
    {"id": "k8s-pods-004", "name": "Privileged containers not allowed", "description": "No containers should run in privileged mode", "provider": "kubernetes", "service": "pods", "severity": "critical", "frameworks": ["CIS-K8s-5.2.1", "NIST-AC-6", "NSA-K8s"], "remediation": "Set securityContext.privileged: false in all container specs."},
    {"id": "k8s-pods-005", "name": "CPU and memory limits set on all containers", "description": "All containers must define CPU and memory resource limits", "provider": "kubernetes", "service": "pods", "severity": "medium", "frameworks": ["CIS-K8s-5.2.5", "NIST-SI-3"], "remediation": "Define resources.limits.cpu and resources.limits.memory for every container."},
    # ─── Audit ──────────────────────────────────────────────────────────────
    {"id": "k8s-audit-001", "name": "Kubernetes audit logging enabled", "description": "API server audit logging must be enabled and configured with an audit policy", "provider": "kubernetes", "service": "audit", "severity": "high", "frameworks": ["CIS-K8s-3.2.1", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Configure --audit-log-path and --audit-policy-file on the API server."},
    {"id": "k8s-audit-002", "name": "Audit logs retained for 30 days minimum", "description": "Kubernetes audit log retention must be at least 30 days", "provider": "kubernetes", "service": "audit", "severity": "medium", "frameworks": ["CIS-K8s-3.2.2", "NIST-AU-11", "PCI-10.7"], "remediation": "Set --audit-log-maxage=30 or ship logs to long-term storage."},
    # ─── etcd ───────────────────────────────────────────────────────────────
    {"id": "k8s-etcd-001", "name": "etcd peer communications encrypted", "description": "etcd must use TLS for peer-to-peer communication", "provider": "kubernetes", "service": "etcd", "severity": "high", "frameworks": ["CIS-K8s-2.1", "NIST-SC-8"], "remediation": "Set --peer-cert-file, --peer-key-file, and --peer-client-cert-auth on etcd."},
    # ─── Images ─────────────────────────────────────────────────────────────
    {"id": "k8s-images-001", "name": "Container images from trusted registries only", "description": "Pods must only pull images from approved container registries", "provider": "kubernetes", "service": "images", "severity": "high", "frameworks": ["CIS-K8s-5.5.1", "NIST-SI-7", "SOC2-CC6.8"], "remediation": "Use OPA/Kyverno admission policy to restrict allowed image registries."},
    {"id": "k8s-images-002", "name": "Image tags pinned (no :latest)", "description": "Container images must use pinned version tags, not :latest", "provider": "kubernetes", "service": "images", "severity": "medium", "frameworks": ["CIS-K8s-5.5.1", "NIST-SA-10"], "remediation": "Replace :latest tags with specific digest or version tags in pod specs."},
    # ─── Admission ──────────────────────────────────────────────────────────
    {"id": "k8s-admission-001", "name": "Admission controllers include NodeRestriction", "description": "NodeRestriction admission plugin must be enabled to limit node API permissions", "provider": "kubernetes", "service": "admission", "severity": "high", "frameworks": ["CIS-K8s-1.2.17", "NIST-AC-6"], "remediation": "Add NodeRestriction to --enable-admission-plugins on the API server."},
    {"id": "k8s-admission-002", "name": "AlwaysPullImages admission controller enabled", "description": "AlwaysPullImages ensures fresh pulls and prevents using cached unauthorized images", "provider": "kubernetes", "service": "admission", "severity": "medium", "frameworks": ["CIS-K8s-1.2.11", "NIST-SI-7"], "remediation": "Add AlwaysPullImages to --enable-admission-plugins on the API server."},
]
