"""BSI C5 — German Cloud Computing Compliance Controls."""
FRAMEWORK_ID = "bsi_c5"; FRAMEWORK_NAME = "BSI C5"; FRAMEWORK_VERSION = "2023"
CONTROLS = [
    {"id":"C5-A-1","theme":"Asset Management","check_type":"inventory","title":"Asset inventory","description":"Maintain cloud asset inventory."},
    {"id":"C5-A-2","theme":"Asset Management","check_type":"baseline_config","title":"Secure baseline","description":"Secure baseline configurations."},
    {"id":"C5-AC-1","theme":"Access Control","check_type":"rbac_configured","title":"Identity management","description":"Manage cloud identities."},
    {"id":"C5-AC-2","theme":"Access Control","check_type":"mfa_configured","title":"MFA","description":"Multi-factor authentication required."},
    {"id":"C5-AC-3","theme":"Access Control","check_type":"least_privilege","title":"Least privilege","description":"Least privilege access."},
    {"id":"C5-AC-4","theme":"Access Control","check_type":"separation_of_duties","title":"Separation of duties","description":"Segregation of duties."},
    {"id":"C5-CR-1","theme":"Cryptography","check_type":"kms_configured","title":"Key management","description":"Manage encryption keys."},
    {"id":"C5-CR-2","theme":"Cryptography","check_type":"disk_encrypted","title":"Encryption at rest","description":"Encrypt data at rest."},
    {"id":"C5-CR-3","theme":"Cryptography","check_type":"tls_enabled","title":"Encryption in transit","description":"Encrypt data in transit."},
    {"id":"C5-NET-1","theme":"Network","check_type":"fw_blocked","title":"Network security","description":"Firewalls and network segmentation."},
    {"id":"C5-NET-2","theme":"Network","check_type":"ids_ips_enabled","title":"IDS/IPS","description":"Intrusion detection systems."},
    {"id":"C5-NET-3","theme":"Network","check_type":"ddos_protection","title":"DDoS protection","description":"Protection against DDoS."},
    {"id":"C5-IR-1","theme":"Incident Response","check_type":"incident_handling","title":"Incident management","description":"Incident response procedures."},
    {"id":"C5-IR-2","theme":"Incident Response","check_type":"incident_reporting","title":"Incident notification","description":"Notify customers of incidents."},
    {"id":"C5-AUD-1","theme":"Audit","check_type":"audit_log_volume","title":"Audit logging","description":"Comprehensive audit logging."},
    {"id":"C5-AUD-2","theme":"Audit","check_type":"log_retention","title":"Log retention","description":"Log retention at least 1 year."},
    {"id":"C5-AUD-3","theme":"Audit","check_type":"continuous_monitoring","title":"Continuous monitoring","description":"Continuous security monitoring."},
    {"id":"C5-BCP-1","theme":"Continuity","check_type":"backup_dr","title":"Business continuity","description":"BCM and disaster recovery."},
    {"id":"C5-BCP-2","theme":"Continuity","check_type":"backup_completed","title":"Backup","description":"Regular data backups."},
    {"id":"C5-BCP-3","theme":"Continuity","check_type":"tests_performed","title":"BCP testing","description":"Regular BCP tests."},
    {"id":"C5-COMP-1","theme":"Compliance","check_type":"assessments_performed","title":"Compliance monitoring","description":"Monitor compliance with regulatory requirements."},
    {"id":"C5-COMP-2","theme":"Compliance","check_type":"pen_testing","title":"Audits","description":"Regular audits by independent parties."},
    {"id":"C5-SUP-1","theme":"Supply Chain","check_type":"supplier_assessment","title":"Vendor assessment","description":"Assess sub-processors."},
    {"id":"C5-SUP-2","theme":"Supply Chain","check_type":"supplier_contracts","title":"Vendor contracts","description":"SLAs with vendors."},
    {"id":"C5-DP-1","theme":"Data Protection","check_type":"privacy_policy","title":"Data protection","description":"Data protection compliance."},
    {"id":"C5-DP-2","theme":"Data Protection","check_type":"media_sanitization","title":"Data deletion","description":"Secure data deletion."},
    {"id":"C5-PER-1","theme":"Personnel","check_type":"background_checks","title":"Personnel screening","description":"Security checks for staff."},
    {"id":"C5-PER-2","theme":"Personnel","check_type":"training_present","title":"Security training","description":"Regular security training."},
    {"id":"C5-PHY-1","theme":"Physical","check_type":"access_control_system","title":"Physical security","description":"Data center physical security."},
    {"id":"C5-PHY-2","theme":"Physical","check_type":"cctv_present","title":"Physical monitoring","description":"Physical access monitoring."},
]
