"""AWS cloud security check definitions. Used by cloud_checks_service.py."""
AWS_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "aws-iam-001", "name": "Root account MFA enabled", "description": "AWS root account must have MFA enabled", "provider": "aws", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.1", "NIST-IA-2", "PCI-8.3", "SOC2-CC6.1"], "remediation": "Enable MFA for the root account via IAM console."},
    {"id": "aws-iam-002", "name": "No root account access keys", "description": "Root account should not have active access keys", "provider": "aws", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.4", "NIST-IA-5", "PCI-8.2"], "remediation": "Delete root account access keys in IAM console."},
    {"id": "aws-iam-003", "name": "MFA enabled for all IAM users", "description": "All IAM users with console access should have MFA", "provider": "aws", "service": "iam", "severity": "high", "frameworks": ["CIS-1.5", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enable MFA for all IAM users via console or policy."},
    {"id": "aws-iam-004", "name": "IAM password policy minimum length 14", "description": "Password policy must require at least 14 characters", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.8", "NIST-IA-5", "PCI-8.3.6"], "remediation": "Update account password policy to require minimum 14 characters."},
    {"id": "aws-iam-005", "name": "IAM password policy requires symbols", "description": "Password policy must require at least one symbol", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.9", "NIST-IA-5"], "remediation": "Enable symbol requirement in account password policy."},
    {"id": "aws-iam-006", "name": "Access keys rotated every 90 days", "description": "IAM user access keys must be rotated every 90 days", "provider": "aws", "service": "iam", "severity": "high", "frameworks": ["CIS-1.14", "NIST-IA-5", "PCI-8.3.9"], "remediation": "Rotate access keys that are older than 90 days."},
    {"id": "aws-iam-007", "name": "No inline IAM policies on users", "description": "Use managed policies instead of inline policies on IAM users", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.16", "NIST-AC-6"], "remediation": "Replace inline policies with managed policies."},
    {"id": "aws-iam-008", "name": "IAM roles used instead of IAM users for services", "description": "EC2 instances should use IAM roles, not long-term keys", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.18", "NIST-AC-6"], "remediation": "Attach IAM role to EC2 instances; remove hardcoded credentials."},
    {"id": "aws-iam-009", "name": "Unused IAM access keys removed", "description": "IAM access keys unused for 90 days should be removed", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.15", "NIST-IA-5"], "remediation": "Delete or rotate access keys that have not been used in 90 days."},
    {"id": "aws-iam-010", "name": "IAM user groups with least privilege", "description": "IAM groups should follow least privilege principle", "provider": "aws", "service": "iam", "severity": "medium", "frameworks": ["NIST-AC-6", "SOC2-CC6.3"], "remediation": "Review and restrict IAM group policies to minimum required permissions."},
    {"id": "aws-iam-011", "name": "IAM policies not overly permissive", "description": "IAM policies should not allow * actions or * resources", "provider": "aws", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.22", "NIST-AC-6", "PCI-7.1", "SOC2-CC6.3"], "remediation": "Replace wildcard IAM policies with scoped permissions."},
    {"id": "aws-iam-012", "name": "IAM roles not shared across accounts without trust", "description": "Cross-account IAM roles require explicit trust policy", "provider": "aws", "service": "iam", "severity": "high", "frameworks": ["NIST-AC-3", "SOC2-CC6.1"], "remediation": "Ensure cross-account IAM roles have explicit trust policies with external IDs."},
    # ─── S3 ─────────────────────────────────────────────────────────────────
    {"id": "aws-s3-001", "name": "S3 bucket public access blocked", "description": "All S3 buckets should have public access blocked", "provider": "aws", "service": "s3", "severity": "critical", "frameworks": ["CIS-2.1.5", "NIST-SC-7", "PCI-1.3", "SOC2-CC6.6"], "remediation": "Enable S3 Block Public Access settings at account and bucket level."},
    {"id": "aws-s3-002", "name": "S3 bucket server-side encryption enabled", "description": "S3 buckets must have default encryption enabled", "provider": "aws", "service": "s3", "severity": "high", "frameworks": ["CIS-2.1.1", "NIST-SC-28", "PCI-3.4", "SOC2-CC6.7"], "remediation": "Enable S3 bucket default encryption using SSE-S3 or SSE-KMS."},
    {"id": "aws-s3-003", "name": "S3 bucket versioning enabled", "description": "S3 buckets storing critical data should have versioning enabled", "provider": "aws", "service": "s3", "severity": "medium", "frameworks": ["CIS-2.1.3", "NIST-CP-10"], "remediation": "Enable versioning on S3 buckets storing important data."},
    {"id": "aws-s3-004", "name": "S3 bucket logging enabled", "description": "S3 server access logging should be enabled", "provider": "aws", "service": "s3", "severity": "medium", "frameworks": ["CIS-2.1.2", "NIST-AU-2"], "remediation": "Enable server access logging on all S3 buckets."},
    {"id": "aws-s3-005", "name": "S3 bucket policy does not allow * principal", "description": "S3 bucket policies must not allow access to all principals", "provider": "aws", "service": "s3", "severity": "critical", "frameworks": ["CIS-2.1.5", "NIST-AC-3", "PCI-1.3"], "remediation": "Review and restrict bucket policies that use Principal: *."},
    {"id": "aws-s3-006", "name": "S3 cross-region replication enabled", "description": "S3 buckets should have cross-region replication for DR", "provider": "aws", "service": "s3", "severity": "medium", "frameworks": ["NIST-CP-9", "SOC2-A1.2"], "remediation": "Configure S3 cross-region replication for critical data buckets."},
    {"id": "aws-s3-007", "name": "S3 Object Lock enabled for immutable storage", "description": "S3 buckets with compliance data should enable Object Lock", "provider": "aws", "service": "s3", "severity": "medium", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Enable S3 Object Lock with Governance or Compliance retention mode."},
    {"id": "aws-s3-008", "name": "S3 MFA Delete enabled on versioned buckets", "description": "S3 versioned buckets should have MFA Delete enabled", "provider": "aws", "service": "s3", "severity": "high", "frameworks": ["NIST-AC-2"], "remediation": "Enable MFA Delete on S3 buckets with versioning enabled."},
    {"id": "aws-s3-009", "name": "S3 lifecycle policy configured", "description": "S3 buckets should have lifecycle policy for cost and compliance", "provider": "aws", "service": "s3", "severity": "low", "frameworks": ["NIST-CM-2"], "remediation": "Configure S3 lifecycle policies to transition or expire objects."},
    {"id": "aws-s3-010", "name": "S3 bucket does not allow HTTP access", "description": "S3 bucket policies must deny HTTP requests", "provider": "aws", "service": "s3", "severity": "high", "frameworks": ["CIS-2.1.5", "NIST-SC-8", "PCI-4.1"], "remediation": "Add bucket policy condition that denies requests with aws:SecureTransport=false."},
    # ─── EC2 ────────────────────────────────────────────────────────────────
    {"id": "aws-ec2-001", "name": "Security groups do not allow unrestricted SSH (port 22)", "description": "Security groups should not allow inbound 0.0.0.0/0 on port 22", "provider": "aws", "service": "ec2", "severity": "critical", "frameworks": ["CIS-5.2", "NIST-SC-7", "PCI-1.2.1", "SOC2-CC6.6"], "remediation": "Restrict SSH access to known IP ranges in security groups."},
    {"id": "aws-ec2-002", "name": "Security groups do not allow unrestricted RDP (port 3389)", "description": "Security groups should not allow inbound 0.0.0.0/0 on port 3389", "provider": "aws", "service": "ec2", "severity": "critical", "frameworks": ["CIS-5.3", "NIST-SC-7", "PCI-1.2.1"], "remediation": "Restrict RDP access to known IP ranges in security groups."},
    {"id": "aws-ec2-003", "name": "EBS volumes encrypted at rest", "description": "All EBS volumes must be encrypted", "provider": "aws", "service": "ec2", "severity": "high", "frameworks": ["CIS-2.2.1", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable EBS encryption by default or encrypt existing volumes."},
    {"id": "aws-ec2-004", "name": "VPC flow logs enabled", "description": "VPC flow logs must be enabled for all VPCs", "provider": "aws", "service": "ec2", "severity": "medium", "frameworks": ["CIS-3.9", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable VPC flow logs and send to CloudWatch or S3."},
    {"id": "aws-ec2-005", "name": "No default security group allows inbound traffic", "description": "Default VPC security group should have no inbound rules", "provider": "aws", "service": "ec2", "severity": "medium", "frameworks": ["CIS-5.4", "NIST-SC-7"], "remediation": "Remove all inbound rules from the default security group."},
    {"id": "aws-ec2-006", "name": "EC2 instances use IMDSv2", "description": "EC2 instance metadata service version 2 should be required", "provider": "aws", "service": "ec2", "severity": "high", "frameworks": ["CIS-4.1", "NIST-AC-3"], "remediation": "Set MetadataOptions HttpTokens=required on EC2 instances."},
    {"id": "aws-ec2-007", "name": "Unused EC2 security groups removed", "description": "Security groups not associated with resources should be removed", "provider": "aws", "service": "ec2", "severity": "low", "frameworks": ["NIST-CM-2"], "remediation": "Delete unused security groups."},
    {"id": "aws-ec2-008", "name": "EC2 detailed monitoring enabled", "description": "EC2 instances should have detailed monitoring enabled", "provider": "aws", "service": "ec2", "severity": "medium", "frameworks": ["CIS-3.6", "NIST-CA-7"], "remediation": "Enable detailed CloudWatch monitoring on EC2 instances."},
    {"id": "aws-ec2-009", "name": "EC2 termination protection enabled", "description": "EC2 instances should have termination protection enabled", "provider": "aws", "service": "ec2", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable termination protection on production EC2 instances."},
    {"id": "aws-ec2-010", "name": "EC2 AMI not shared publicly", "description": "EC2 AMIs must not be shared publicly", "provider": "aws", "service": "ec2", "severity": "critical", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Modify AMI permissions to remove public launch permissions."},
    {"id": "aws-ec2-011", "name": "EC2 placement groups used for critical workloads", "description": "Critical EC2 workloads should use placement groups for low latency", "provider": "aws", "service": "ec2", "severity": "low", "frameworks": ["NIST-CP-10"], "remediation": "Deploy critical EC2 instances in a placement group."},
    # ─── CloudTrail ─────────────────────────────────────────────────────────
    {"id": "aws-cloudtrail-001", "name": "CloudTrail enabled in all regions", "description": "CloudTrail must be enabled and logging in all regions", "provider": "aws", "service": "cloudtrail", "severity": "critical", "frameworks": ["CIS-3.1", "NIST-AU-2", "PCI-10.1", "SOC2-CC7.2"], "remediation": "Enable a multi-region CloudTrail trail."},
    {"id": "aws-cloudtrail-002", "name": "CloudTrail log file validation enabled", "description": "Log file integrity validation must be enabled", "provider": "aws", "service": "cloudtrail", "severity": "high", "frameworks": ["CIS-3.2", "NIST-AU-9"], "remediation": "Enable log file integrity validation on all CloudTrail trails."},
    {"id": "aws-cloudtrail-003", "name": "CloudTrail logs encrypted with KMS", "description": "CloudTrail logs must be encrypted using KMS CMK", "provider": "aws", "service": "cloudtrail", "severity": "medium", "frameworks": ["CIS-3.7", "NIST-SC-28", "PCI-10.5"], "remediation": "Configure KMS encryption for CloudTrail log files."},
    {"id": "aws-cloudtrail-004", "name": "CloudTrail sends logs to CloudWatch", "description": "CloudTrail trails should send logs to CloudWatch Logs", "provider": "aws", "service": "cloudtrail", "severity": "medium", "frameworks": ["CIS-3.4", "NIST-AU-6", "SOC2-CC7.3"], "remediation": "Configure CloudTrail to send logs to CloudWatch Logs group."},
    {"id": "aws-cloudtrail-005", "name": "CloudTrail bucket not publicly accessible", "description": "CloudTrail S3 bucket must not be publicly accessible", "provider": "aws", "service": "cloudtrail", "severity": "critical", "frameworks": ["CIS-3.3", "NIST-SC-7", "PCI-1.3"], "remediation": "Block public access on CloudTrail S3 bucket."},
    {"id": "aws-cloudtrail-006", "name": "CloudTrail data events captured", "description": "CloudTrail should capture S3 data events and Lambda invocations", "provider": "aws", "service": "cloudtrail", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable data events on CloudTrail trail for S3 and Lambda."},
    # ─── RDS ─────────────────────────────────────────────────────────────────
    {"id": "aws-rds-001", "name": "RDS instances not publicly accessible", "description": "RDS instances must not be publicly accessible", "provider": "aws", "service": "rds", "severity": "critical", "frameworks": ["CIS-2.3.2", "NIST-SC-7", "PCI-1.3"], "remediation": "Set PubliclyAccessible to false on all RDS instances."},
    {"id": "aws-rds-002", "name": "RDS storage encrypted at rest", "description": "All RDS instances must have storage encryption enabled", "provider": "aws", "service": "rds", "severity": "high", "frameworks": ["CIS-2.3.1", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable storage encryption when creating RDS instances."},
    {"id": "aws-rds-003", "name": "RDS automated backups enabled", "description": "RDS instances must have automated backups enabled", "provider": "aws", "service": "rds", "severity": "medium", "frameworks": ["NIST-CP-9", "SOC2-A1.2"], "remediation": "Enable automated backups with retention period of at least 7 days."},
    {"id": "aws-rds-004", "name": "RDS multi-AZ enabled for production", "description": "Production RDS instances should use multi-AZ deployment", "provider": "aws", "service": "rds", "severity": "medium", "frameworks": ["NIST-CP-10", "SOC2-A1.1"], "remediation": "Enable Multi-AZ for RDS instances in production environments."},
    {"id": "aws-rds-005", "name": "RDS deletion protection enabled", "description": "RDS instances should have deletion protection enabled", "provider": "aws", "service": "rds", "severity": "high", "frameworks": ["NIST-CP-10"], "remediation": "Enable deletion protection on all production RDS instances."},
    {"id": "aws-rds-006", "name": "RDS minor version upgrade enabled", "description": "RDS instances should auto-update minor versions", "provider": "aws", "service": "rds", "severity": "medium", "frameworks": ["NIST-SI-2"], "remediation": "Enable auto minor version upgrade on all RDS instances."},
    {"id": "aws-rds-007", "name": "RDS IAM authentication enabled", "description": "RDS should use IAM authentication over password auth", "provider": "aws", "service": "rds", "severity": "medium", "frameworks": ["NIST-IA-5", "SOC2-CC6.1"], "remediation": "Enable IAM database authentication on RDS instances."},
    # ─── Lambda ──────────────────────────────────────────────────────────────
    {"id": "aws-lambda-001", "name": "Lambda functions have resource-based policies reviewed", "description": "Lambda resource policies should not allow public access", "provider": "aws", "service": "lambda", "severity": "high", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Review and restrict Lambda resource-based policies."},
    {"id": "aws-lambda-002", "name": "Lambda functions use latest runtime", "description": "Lambda functions must not use deprecated runtime versions", "provider": "aws", "service": "lambda", "severity": "medium", "frameworks": ["CIS-2.8", "NIST-SA-22"], "remediation": "Update Lambda functions to use current supported runtimes."},
    {"id": "aws-lambda-003", "name": "Lambda environment variables encrypted", "description": "Lambda environment variables should be encrypted with KMS", "provider": "aws", "service": "lambda", "severity": "high", "frameworks": ["NIST-SC-28", "SOC2-CC6.7"], "remediation": "Enable KMS encryption for Lambda environment variables."},
    {"id": "aws-lambda-004", "name": "Lambda functions attached to VPC", "description": "Lambda functions should run inside a VPC for network isolation", "provider": "aws", "service": "lambda", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Configure Lambda functions to run inside a VPC."},
    {"id": "aws-lambda-005", "name": "Lambda functions have X-Ray tracing enabled", "description": "Lambda functions should enable active X-Ray tracing", "provider": "aws", "service": "lambda", "severity": "medium", "frameworks": ["NIST-CA-7"], "remediation": "Enable active X-Ray tracing on Lambda functions."},
    {"id": "aws-lambda-006", "name": "Lambda dead-letter queue configured", "description": "Lambda functions should have a DLQ for async invocation failures", "provider": "aws", "service": "lambda", "severity": "medium", "frameworks": ["NIST-CP-2"], "remediation": "Configure a dead-letter queue on Lambda functions."},
    {"id": "aws-lambda-007", "name": "Lambda function URL requires IAM auth", "description": "Lambda function URLs must use IAM auth, not NONE", "provider": "aws", "service": "lambda", "severity": "high", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Set AuthType to AWS_IAM on Lambda function URLs."},
    {"id": "aws-lambda-008", "name": "Lambda reserved concurrency configured", "description": "Lambda functions should have reserved concurrency set", "provider": "aws", "service": "lambda", "severity": "low", "frameworks": ["NIST-CP-2"], "remediation": "Set reserved concurrency on critical Lambda functions."},
    # ─── EKS ─────────────────────────────────────────────────────────────────
    {"id": "aws-eks-001", "name": "EKS cluster endpoint not publicly accessible", "description": "EKS cluster API endpoint should be private", "provider": "aws", "service": "eks", "severity": "high", "frameworks": ["CIS-EKS-1.1.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Disable public endpoint on EKS cluster; enable private endpoint."},
    {"id": "aws-eks-002", "name": "EKS node groups use IMDSv2", "description": "EKS node groups should require IMDSv2", "provider": "aws", "service": "eks", "severity": "high", "frameworks": ["CIS-EKS-4.1", "NIST-AC-3"], "remediation": "Set metadata_options.http_tokens=required on EKS node group launch templates."},
    {"id": "aws-eks-003", "name": "EKS control plane logging enabled", "description": "EKS cluster control plane logs should be sent to CloudWatch", "provider": "aws", "service": "eks", "severity": "medium", "frameworks": ["CIS-EKS-3.1", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable all EKS control plane log types (api, audit, authenticator, controllerManager, scheduler)."},
    {"id": "aws-eks-004", "name": "EKS cluster secrets encrypted with KMS", "description": "EKS secrets should be encrypted with KMS", "provider": "aws", "service": "eks", "severity": "critical", "frameworks": ["CIS-EKS-2.1.1", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable KMS envelope encryption for Kubernetes secrets on EKS cluster."},
    # ─── CloudFront ─────────────────────────────────────────────────────────
    {"id": "aws-cf-001", "name": "CloudFront distributions redirect HTTP to HTTPS", "description": "CloudFront distributions should enforce HTTPS", "provider": "aws", "service": "cloudfront", "severity": "critical", "frameworks": ["CIS-3.12", "NIST-SC-8", "PCI-4.1"], "remediation": "Set ViewerProtocolPolicy to redirect-to-https on CloudFront origins."},
    {"id": "aws-cf-002", "name": "CloudFront distributions have WAF WebACL attached", "description": "CloudFront distributions should be protected by WAF", "provider": "aws", "service": "cloudfront", "severity": "high", "frameworks": ["CIS-3.13", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Attach a WAF WebACL to all CloudFront distributions."},
    {"id": "aws-cf-003", "name": "CloudFront distributions have access logging enabled", "description": "CloudFront access logs should be enabled", "provider": "aws", "service": "cloudfront", "severity": "medium", "frameworks": ["CIS-3.11", "NIST-AU-2"], "remediation": "Enable CloudFront access logging with S3 bucket destination."},
    {"id": "aws-cf-004", "name": "CloudFront geo restrictions configured", "description": "CloudFront should restrict content delivery by geography", "provider": "aws", "service": "cloudfront", "severity": "medium", "frameworks": ["NIST-AC-3"], "remediation": "Configure CloudFront geo restriction to block unwanted countries."},
    {"id": "aws-cf-005", "name": "CloudFront field-level encryption enabled", "description": "CloudFront should use field-level encryption for sensitive data", "provider": "aws", "service": "cloudfront", "severity": "high", "frameworks": ["PCI-3.4", "NIST-SC-28"], "remediation": "Configure CloudFront field-level encryption for POST requests with PII."},
    # ─── WAF ─────────────────────────────────────────────────────────────────
    {"id": "aws-waf-001", "name": "WAF WebACL has managed rule group attached", "description": "WAF WebACL should use AWS managed rule groups", "provider": "aws", "service": "waf", "severity": "high", "frameworks": ["CIS-3.14", "NIST-SC-7", "PCI-6.5"], "remediation": "Attach AWS managed Core Rule Set (CRS) and other managed rule groups to WAF WebACL."},
    {"id": "aws-waf-002", "name": "WAF rate-based rule configured", "description": "WAF should have rate-based rule to prevent DDoS", "provider": "aws", "service": "waf", "severity": "high", "frameworks": ["NIST-SC-5", "SOC2-A1.1"], "remediation": "Add rate-based rule to WAF WebACL limiting requests per IP per 5 minutes."},
    {"id": "aws-waf-003", "name": "WAF logging enabled", "description": "WAF WebACL should have logging configured", "provider": "aws", "service": "waf", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable logging on WAF WebACL to S3 or CloudWatch."},
    # ─── SNS ─────────────────────────────────────────────────────────────────
    {"id": "aws-sns-001", "name": "SNS topics have server-side encryption enabled", "description": "SNS topics should use SSE-KMS encryption", "provider": "aws", "service": "sns", "severity": "high", "frameworks": ["NIST-SC-28", "SOC2-CC6.7"], "remediation": "Enable KMS encryption on all SNS topics."},
    {"id": "aws-sns-002", "name": "SNS topics do not allow cross-account publish", "description": "SNS topics should restrict publish to trusted accounts", "provider": "aws", "service": "sns", "severity": "high", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Restrict SNS topic policy to allow publish only from trusted AWS accounts."},
    {"id": "aws-sns-003", "name": "SNS topics have delivery policy configured", "description": "SNS topics should have retry and dead-letter policies", "provider": "aws", "service": "sns", "severity": "low", "frameworks": ["NIST-CP-2"], "remediation": "Configure SNS delivery retry policy and DLQ for failed deliveries."},
    # ─── SQS ─────────────────────────────────────────────────────────────────
    {"id": "aws-sqs-001", "name": "SQS queues have server-side encryption enabled", "description": "SQS queues should use SSE-KMS encryption", "provider": "aws", "service": "sqs", "severity": "high", "frameworks": ["NIST-SC-28", "SOC2-CC6.7"], "remediation": "Enable KMS encryption on all SQS queues."},
    {"id": "aws-sqs-002", "name": "SQS queue policies do not grant public access", "description": "SQS queue policies must not allow public access", "provider": "aws", "service": "sqs", "severity": "critical", "frameworks": ["NIST-AC-3", "SOC2-CC6.6"], "remediation": "Remove Allow * Principal from SQS queue policy."},
    {"id": "aws-sqs-003", "name": "SQS dead-letter queue configured", "description": "SQS queues should have DLQ for failed messages", "provider": "aws", "service": "sqs", "severity": "medium", "frameworks": ["NIST-CP-2"], "remediation": "Configure a dead-letter queue for all SQS queues."},
    # ─── ElasticSearch/OpenSearch ────────────────────────────────────────────
    {"id": "aws-es-001", "name": "ES domains deployed within VPC", "description": "Elasticsearch domains should be VPC-only", "provider": "aws", "service": "es", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Deploy ES domains within a VPC; disable public endpoint."},
    {"id": "aws-es-002", "name": "ES domains have encryption at rest enabled", "description": "Elasticsearch domains should encrypt data at rest", "provider": "aws", "service": "es", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4", "SOC2-CC6.7"], "remediation": "Enable encryption at rest on all ES domains."},
    {"id": "aws-es-003", "name": "ES domains have fine-grained access control", "description": "Elasticsearch domains should use fine-grained access control", "provider": "aws", "service": "es", "severity": "medium", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Enable fine-grained access control on ES domains with IAM integration."},
    {"id": "aws-es-004", "name": "ES domains log to CloudWatch", "description": "Elasticsearch domains should publish error and index slow logs", "provider": "aws", "service": "es", "severity": "medium", "frameworks": ["NIST-AU-2"], "remediation": "Enable CloudWatch log publishing for ES domains."},
    {"id": "aws-es-005", "name": "ES domains require HTTPS", "description": "Elasticsearch domains must enforce HTTPS", "provider": "aws", "service": "es", "severity": "high", "frameworks": ["CIS-2.7", "NIST-SC-8", "PCI-4.1"], "remediation": "Enforce HTTPS on all ES domain endpoints."},
    # ─── Route53 ─────────────────────────────────────────────────────────────
    {"id": "aws-r53-001", "name": "Route53 DNSSEC enabled for hosted zones", "description": "DNS Sec should be enabled on Route53 hosted zones", "provider": "aws", "service": "route53", "severity": "medium", "frameworks": ["NIST-SC-20"], "remediation": "Enable DNSSEC signing on Route53 hosted zones."},
    {"id": "aws-r53-002", "name": "Route53 query logging enabled", "description": "Route53 DNS query logging should be enabled", "provider": "aws", "service": "route53", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable Route53 query logging to CloudWatch Logs."},
    # ─── ACM ─────────────────────────────────────────────────────────────────
    {"id": "aws-acm-001", "name": "No ACM certificates expiring within 30 days", "description": "ACM certificates expiring soon should be renewed", "provider": "aws", "service": "acm", "severity": "high", "frameworks": ["NIST-SC-12"], "remediation": "Renew ACM certificates or create renewal alerts."},
    # ─── Inspector ───────────────────────────────────────────────────────────
    {"id": "aws-inspector-001", "name": "Amazon Inspector v2 activated for EC2", "description": "Inspector vulnerability scanning should be enabled for EC2", "provider": "aws", "service": "inspector", "severity": "high", "frameworks": ["CIS-4.6", "NIST-RA-5", "SOC2-CC7.1"], "remediation": "Enable Amazon Inspector v2 for EC2 scanning."},
    {"id": "aws-inspector-002", "name": "Amazon Inspector v2 activated for Lambda", "description": "Inspector vulnerability scanning should be enabled for Lambda code", "provider": "aws", "service": "inspector", "severity": "high", "frameworks": ["NIST-RA-5"], "remediation": "Enable Amazon Inspector v2 for Lambda code scanning."},
    # ─── SSM ─────────────────────────────────────────────────────────────────
    {"id": "aws-ssm-001", "name": "EC2 instances managed by SSM", "description": "EC2 instances should be managed by Systems Manager", "provider": "aws", "service": "ssm", "severity": "high", "frameworks": ["NIST-CM-2", "SOC2-CC7.2"], "remediation": "Install SSM Agent on all EC2 instances and attach SSM IAM role."},
    {"id": "aws-ssm-002", "name": "SSM documents not publicly shared", "description": "SSM documents must not be shared as public", "provider": "aws", "service": "ssm", "severity": "high", "frameworks": ["NIST-AC-3"], "remediation": "Set SSM document permissions to Private."},
    {"id": "aws-ssm-003", "name": "SSM session manager enabled", "description": "Use SSM Session Manager instead of SSH for EC2 access", "provider": "aws", "service": "ssm", "severity": "medium", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Enable SSM Session Manager and disable SSH inbound rules."},
    # ─── Backup ──────────────────────────────────────────────────────────────
    {"id": "aws-backup-001", "name": "AWS Backup plan exists with at least one rule", "description": "An AWS Backup plan must exist for automated backups", "provider": "aws", "service": "backup", "severity": "high", "frameworks": ["NIST-CP-9", "SOC2-A1.2"], "remediation": "Create an AWS Backup plan with retention rules and assign resources."},
    {"id": "aws-backup-002", "name": "AWS Backup vault has recovery point protection", "description": "Backup vaults should prevent manual deletion of recovery points", "provider": "aws", "service": "backup", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable backup vault lock to prevent deletion of recovery points."},
    # ─── CloudWatch ──────────────────────────────────────────────────────────
    {"id": "aws-cw-001", "name": "CloudWatch log retention period set", "description": "CloudWatch log groups should have retention period configured", "provider": "aws", "service": "cloudwatch", "severity": "medium", "frameworks": ["CIS-3.8", "NIST-AU-11", "PCI-10.7"], "remediation": "Set log retention period to at least 365 days on all CloudWatch log groups."},
    {"id": "aws-cw-002", "name": "CloudWatch alarm for unauthorized API calls", "description": "Alarm must exist for IAM authentication failures", "provider": "aws", "service": "cloudwatch", "severity": "high", "frameworks": ["CIS-4.1", "NIST-AC-2"], "remediation": "Create CloudWatch alarm for ConsoleLogin Failures via CloudTrail."},
    {"id": "aws-cw-003", "name": "CloudWatch alarm for IAM policy changes", "description": "Alarm must exist for IAM policy modifications", "provider": "aws", "service": "cloudwatch", "severity": "high", "frameworks": ["CIS-4.4", "NIST-AC-6"], "remediation": "Create CloudWatch alarm for IAM policy change events."},
    {"id": "aws-cw-004", "name": "CloudWatch alarm for security group changes", "description": "Alarm must exist for security group changes", "provider": "aws", "service": "cloudwatch", "severity": "medium", "frameworks": ["CIS-4.5", "NIST-SC-7"], "remediation": "Create CloudWatch alarm for security group and NACL change events."},
    {"id": "aws-cw-005", "name": "CloudWatch alarm for network ACL changes", "description": "Alarm must exist for VPC network ACL changes", "provider": "aws", "service": "cloudwatch", "severity": "medium", "frameworks": ["CIS-4.6", "NIST-SC-7"], "remediation": "Create CloudWatch alarm for network ACL change events."},
    {"id": "aws-cw-006", "name": "CloudWatch alarm for route table changes", "description": "Alarm must exist for VPC route table changes", "provider": "aws", "service": "cloudwatch", "severity": "medium", "frameworks": ["CIS-4.7", "NIST-SC-7"], "remediation": "Create CloudWatch alarm for route table change events."},
    {"id": "aws-cw-007", "name": "CloudWatch alarm for S3 bucket policy changes", "description": "Alarm must exist for S3 policy changes", "provider": "aws", "service": "cloudwatch", "severity": "medium", "frameworks": ["CIS-4.8", "NIST-AC-3"], "remediation": "Create CloudWatch alarm for S3 bucket policy change events."},
    # ─── ELB ─────────────────────────────────────────────────────────────────
    {"id": "aws-elb-001", "name": "ALB access logging enabled", "description": "ALB must have access logging enabled", "provider": "aws", "service": "elb", "severity": "medium", "frameworks": ["CIS-3.14", "NIST-AU-2"], "remediation": "Enable access logging on all application load balancers."},
    {"id": "aws-elb-002", "name": "ALB uses HTTPS listener", "description": "ALB should redirect HTTP to HTTPS", "provider": "aws", "service": "elb", "severity": "critical", "frameworks": ["NIST-SC-8", "PCI-4.1", "SOC2-CC6.7"], "remediation": "Add HTTPS listener and configure redirect or switch to HTTPS."},
    {"id": "aws-elb-003", "name": "ALB WAF WebACL attached", "description": "ALB in front of web applications should have WAF attached", "provider": "aws", "service": "elb", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Attach WAF WebACL to ALB for web applications."},
    {"id": "aws-elb-004", "name": "ALB deletion protection enabled", "description": "ALB should have deletion protection enabled", "provider": "aws", "service": "elb", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable deletion protection on ALB."},
    {"id": "aws-elb-005", "name": "ALB TLS cipher security policy latest", "description": "ALB should use modern TLS cipher security policy", "provider": "aws", "service": "elb", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set ALB SSL policy to ELBSecurityPolicy-TLS13-1-2-Res-2021-06."},
    # ─── DynamoDB ────────────────────────────────────────────────────────────
    {"id": "aws-ddb-001", "name": "DynamoDB table encryption enabled", "description": "DynamoDB tables should have default encryption enabled", "provider": "aws", "service": "dynamodb", "severity": "high", "frameworks": ["NIST-SC-28", "SOC2-CC6.7"], "remediation": "Enable DynamoDB encryption with AWS owned or KMS key."},
    {"id": "aws-ddb-002", "name": "DynamoDB point-in-time recovery enabled", "description": "DynamoDB tables should have PITR enabled", "provider": "aws", "service": "dynamodb", "severity": "high", "frameworks": ["NIST-CP-9", "SOC2-A1.2"], "remediation": "Enable point-in-time recovery on DynamoDB tables."},
    {"id": "aws-ddb-003", "name": "DynamoDB auto scaling enabled", "description": "DynamoDB should have auto scaling configured", "provider": "aws", "service": "dynamodb", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Configure DynamoDB auto scaling for read/write capacity."},
    {"id": "aws-ddb-004", "name": "DynamoDB table policies not overly permissive", "description": "DynamoDB table policies should not allow public access", "provider": "aws", "service": "dynamodb", "severity": "critical", "frameworks": ["NIST-AC-3", "SOC2-CC6.3"], "remediation": "Remove public IAM policies from DynamoDB tables."},
    # ─── ECS ─────────────────────────────────────────────────────────────────
    {"id": "aws-ecs-001", "name": "ECS tasks use task execution role", "description": "ECS task definitions should have execution role", "provider": "aws", "service": "ecs", "severity": "high", "frameworks": ["NIST-AC-6", "SOC2-CC6.3"], "remediation": "Add task execution role to ECS task definitions."},
    {"id": "aws-ecs-002", "name": "ECS secrets referenced from Secrets Manager", "description": "ECS container secrets must use Secrets Manager references", "provider": "aws", "service": "ecs", "severity": "high", "frameworks": ["NIST-SA-3", "PCI-3.2"], "remediation": "Configure ECS task definition to reference secrets from Secrets Manager."},
    {"id": "aws-ecs-003", "name": "ECS containers not running as privileged", "description": "ECS task containers must not have privileged access", "provider": "aws", "service": "ecs", "severity": "critical", "frameworks": ["NIST-AC-6"], "remediation": "Set privileged=false in ECS task definition container definitions."},
    {"id": "aws-ecs-004", "name": "ECS execute command logging enabled", "description": "ECS execute command sessions should be logged", "provider": "aws", "service": "ecs", "severity": "medium", "frameworks": ["NIST-AU-2"], "remediation": "Enable audit logging for ECS execute command sessions."},
    # ─── API Gateway ─────────────────────────────────────────────────────────
    {"id": "aws-apigw-001", "name": "API Gateway enforces TLS 1.2", "description": "API Gateway custom domains should enforce TLS 1.2", "provider": "aws", "service": "apigateway", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set security policy to TLS 1.2 on API Gateway custom domain names."},
    {"id": "aws-apigw-002", "name": "API Gateway logging enabled", "description": "API Gateway should have CloudWatch logging enabled", "provider": "aws", "service": "apigateway", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable CloudWatch access logging and execution logging on API Gateway stages."},
    {"id": "aws-apigw-003", "name": "API Gateway throttling configured", "description": "API Gateway should have rate and burst limits configured", "provider": "aws", "service": "apigateway", "severity": "medium", "frameworks": ["NIST-SC-5"], "remediation": "Configure usage plans and API rate limits on API Gateway."},
    {"id": "aws-apigw-004", "name": "API Gateway WAF attached", "description": "API Gateway APIs should be protected by WAF", "provider": "aws", "service": "apigateway", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Attach WAF WebACL to API Gateway REST or HTTP APIs."},
    # ─── ECR ─────────────────────────────────────────────────────────────────
    {"id": "aws-ecr-001", "name": "ECR private repositories not publicly accessible", "description": "ECR repository policies must not allow public access", "provider": "aws", "service": "ecr", "severity": "critical", "frameworks": ["NIST-AC-3", "SOC2-CC6.6"], "remediation": "Remove public access from ECR repository policies."},
    {"id": "aws-ecr-002", "name": "ECR image scanning on push", "description": "ECR should scan images on push for vulnerabilities", "provider": "aws", "service": "ecr", "severity": "high", "frameworks": ["NIST-RA-5", "SOC2-CC7.1"], "remediation": "Enable scan on push for all ECR repositories."},
    {"id": "aws-ecr-003", "name": "ECR lifecycle policy configured", "description": "ECR repositories should have lifecycle policies to expire old images", "provider": "aws", "service": "ecr", "severity": "medium", "frameworks": ["NIST-CM-2"], "remediation": "Add lifecycle policy to ECR to expire untagged and old images."},
    {"id": "aws-ecr-004", "name": "ECR immutable tags enforced", "description": "ECR repositories should enforce immutable image tags", "provider": "aws", "service": "ecr", "severity": "medium", "frameworks": ["NIST-SA-10"], "remediation": "Set tag mutability to IMMUTABLE on ECR repositories."},
    # ─── KMS ─────────────────────────────────────────────────────────────────
    {"id": "aws-kms-001", "name": "KMS CMK rotation enabled", "description": "Customer managed KMS keys must have automatic rotation enabled", "provider": "aws", "service": "kms", "severity": "medium", "frameworks": ["CIS-3.8", "NIST-SC-12", "PCI-3.6"], "remediation": "Enable automatic key rotation for all KMS CMKs."},
    {"id": "aws-kms-002", "name": "KMS keys not scheduled for deletion", "description": "KMS CMKs should not be pending deletion", "provider": "aws", "service": "kms", "severity": "high", "frameworks": ["NIST-CP-10"], "remediation": "Cancel pending KMS key deletion unless intentional."},
    {"id": "aws-kms-003", "name": "KMS multi-region keys replicated", "description": "Multi-region KMS keys should be replicated across regions", "provider": "aws", "service": "kms", "severity": "low", "frameworks": ["NIST-CP-10"], "remediation": "Create replica KMS keys in additional regions for DR."},
    # ─── Config ──────────────────────────────────────────────────────────────
    {"id": "aws-config-001", "name": "AWS Config enabled in all regions", "description": "AWS Config must be enabled in all regions for compliance recording", "provider": "aws", "service": "config", "severity": "high", "frameworks": ["CIS-3.5", "NIST-CA-7", "SOC2-CC7.2"], "remediation": "Enable AWS Config recording in all regions."},
    {"id": "aws-config-002", "name": "AWS Config records all resource types", "description": "AWS Config recorder should record all resource types", "provider": "aws", "service": "config", "severity": "medium", "frameworks": ["NIST-CA-7"], "remediation": "Set Config recorder to record all supported resource types."},
    # ─── GuardDuty ───────────────────────────────────────────────────────────
    {"id": "aws-guardduty-001", "name": "GuardDuty enabled in all regions", "description": "GuardDuty threat detection must be active in all regions", "provider": "aws", "service": "guardduty", "severity": "high", "frameworks": ["CIS-3.10", "NIST-IR-4", "SOC2-CC7.4"], "remediation": "Enable GuardDuty in all AWS regions."},
    {"id": "aws-guardduty-002", "name": "GuardDuty has S3 protection enabled", "description": "GuardDuty S3 protection should be enabled", "provider": "aws", "service": "guardduty", "severity": "medium", "frameworks": ["NIST-IR-4"], "remediation": "Enable GuardDuty S3 protection in all regions."},
    {"id": "aws-guardduty-003", "name": "GuardDuty findings exported to Security Hub", "description": "GuardDuty findings should be sent to Security Hub", "provider": "aws", "service": "guardduty", "severity": "medium", "frameworks": ["NIST-CA-7", "SOC2-CC7.2"], "remediation": "Enable GuardDuty integration with Security Hub."},
    # ─── SecurityHub ─────────────────────────────────────────────────────────
    {"id": "aws-securityhub-001", "name": "Security Hub enabled", "description": "AWS Security Hub must be enabled for centralised findings", "provider": "aws", "service": "securityhub", "severity": "medium", "frameworks": ["NIST-CA-7", "SOC2-CC7.2"], "remediation": "Enable Security Hub and subscribe to CIS and PCI standards."},
    {"id": "aws-securityhub-002", "name": "Security Hub CIS standard enabled", "description": "Security Hub should have CIS benchmark enabled", "provider": "aws", "service": "securityhub", "severity": "medium", "frameworks": ["CIS-1.1"], "remediation": "Enable CIS AWS Foundations Benchmark in Security Hub."},
    # ─── Secrets Manager ─────────────────────────────────────────────────────
    {"id": "aws-sm-001", "name": "Secrets Manager secrets have automatic rotation", "description": "Secrets Manager secrets should be automatically rotated", "provider": "aws", "service": "secretsmanager", "severity": "high", "frameworks": ["NIST-IA-5", "PCI-8.3.9", "SOC2-CC6.3"], "remediation": "Enable automatic rotation on Secrets Manager secrets."},
    {"id": "aws-sm-002", "name": "Secrets Manager rotation period within 90 days", "description": "Secrets Manager rotation period should be at most 90 days", "provider": "aws", "service": "secretsmanager", "severity": "medium", "frameworks": ["NIST-IA-5", "PCI-8.3.9"], "remediation": "Set rotation interval to 90 days or less on Secrets Manager secrets."},
    # ─── EventBridge ─────────────────────────────────────────────────────────
    {"id": "aws-ev-001", "name": "EventBridge schema registry enabled", "description": "EventBridge schema discovery should be enabled", "provider": "aws", "service": "eventbridge", "severity": "low", "frameworks": [], "remediation": "Enable schema discovery on EventBridge event buses."},
    # ─── Step Functions ──────────────────────────────────────────────────────
    {"id": "aws-sfn-001", "name": "Step Functions X-Ray tracing enabled", "description": "Step Functions state machines should have X-Ray tracing enabled", "provider": "aws", "service": "stepfunctions", "severity": "medium", "frameworks": ["NIST-CA-7"], "remediation": "Enable X-Ray tracing on Step Functions state machines."},
    {"id": "aws-sfn-002", "name": "Step Functions logging enabled", "description": "Step Functions should have execution logging configured", "provider": "aws", "service": "stepfunctions", "severity": "medium", "frameworks": ["NIST-AU-2"], "remediation": "Enable CloudWatch logging on Step Functions state machines."},
    # ─── ElastiCache ─────────────────────────────────────────────────────────
    {"id": "aws-ecache-001", "name": "ElastiCache encryption at rest enabled", "description": "ElastiCache clusters should have encryption at rest enabled", "provider": "aws", "service": "elastiCache", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Enable encryption at rest on ElastiCache replication groups."},
    {"id": "aws-ecache-002", "name": "ElastiCache encryption in transit enabled", "description": "ElastiCache clusters should have encryption in transit enabled", "provider": "aws", "service": "elastiCache", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Enable encryption in transit on ElastiCache clusters."},
    {"id": "aws-ecache-003", "name": "ElastiCache not in default VPC", "description": "ElastiCache clusters should not be deployed in default VPC", "provider": "aws", "service": "elastiCache", "severity": "medium", "frameworks": ["NIST-SC-7"], "remediation": "Deploy ElastiCache clusters in a custom VPC."},
    # ─── Redshift ────────────────────────────────────────────────────────────
    {"id": "aws-redshift-001", "name": "Redshift clusters encrypted at rest", "description": "Redshift clusters must have encryption enabled", "provider": "aws", "service": "redshift", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Enable KMS encryption on Redshift clusters."},
    {"id": "aws-redshift-002", "name": "Redshift publicly accessible disabled", "description": "Redshift clusters must not be publicly accessible", "provider": "aws", "service": "redshift", "severity": "critical", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set PubliclyAccessible to false on Redshift clusters."},
    {"id": "aws-redshift-003", "name": "Redshift automated snapshots enabled", "description": "Redshift clusters should have automated snapshot retention configured", "provider": "aws", "service": "redshift", "severity": "medium", "frameworks": ["NIST-CP-9"], "remediation": "Set automated snapshot retention period to at least 7 days."},
    {"id": "aws-redshift-004", "name": "Redshift database audit logging enabled", "description": "Redshift audit logging should be enabled", "provider": "aws", "service": "redshift", "severity": "medium", "frameworks": ["NIST-AU-2", "PCI-10.1"], "remediation": "Enable audit logging for Redshift database connections."},
    {"id": "aws-redshift-005", "name": "Redshift enhanced VPC routing enabled", "description": "Redshift should use enhanced VPC routing", "provider": "aws", "service": "redshift", "severity": "medium", "frameworks": ["NIST-SC-7"], "remediation": "Enable enhanced VPC routing for Redshift clusters."},
    # ─── EMR ─────────────────────────────────────────────────────────────────
    {"id": "aws-emr-001", "name": "EMR cluster encryption at rest enabled", "description": "EMR should use local disk encryption at rest", "provider": "aws", "service": "emr", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Enable EMR encryption at rest with KMS or EBS encryption."},
    {"id": "aws-emr-002", "name": "EMR cluster encryption in transit enabled", "description": "EMR should have encryption in transit enabled", "provider": "aws", "service": "emr", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Enable EMR in-transit encryption between nodes."},
    {"id": "aws-emr-003", "name": "EMR block public access enabled", "description": "EMR block public access should be enabled at account level", "provider": "aws", "service": "emr", "severity": "critical", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable EMR block public access at the AWS account level."},
    # ─── Kinesis ─────────────────────────────────────────────────────────────
    {"id": "aws-kinesis-001", "name": "Kinesis stream encryption at rest enabled", "description": "Kinesis data streams should use SSE-KMS", "provider": "aws", "service": "kinesis", "severity": "high", "frameworks": ["NIST-SC-28", "SOC2-CC6.7"], "remediation": "Enable Kinesis data stream server-side encryption with KMS."},
    # ─── VPC ─────────────────────────────────────────────────────────────────
    {"id": "aws-vpc-001", "name": "VPC NACLs not overly permissive", "description": "VPC NACLs should not allow SSH/RDP from all sources", "provider": "aws", "service": "vpc", "severity": "high", "frameworks": ["CIS-5.1", "NIST-SC-7"], "remediation": "Review NACL rules to restrict SSH/RDP to known source ranges."},
    {"id": "aws-vpc-002", "name": "VPC subnets not automatically assigning public IP", "description": "Subnets should not auto-assign public IP addresses by default", "provider": "aws", "service": "vpc", "severity": "medium", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Disable auto-assign public IP attribute on subnets."},
    {"id": "aws-vpc-003", "name": "VPC flow logs sent to CloudWatch", "description": "VPC flow logs should be sent to CloudWatch Logs for monitoring", "provider": "aws", "service": "vpc", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Configure VPC flow log to CloudWatch Logs destination."},
]
