"""GCP cloud security check definitions. Used by cloud_checks_service.py."""
GCP_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "gcp-iam-001", "name": "No service accounts with project owner role", "description": "Service accounts must not be assigned project Owner role", "provider": "gcp", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.5", "NIST-AC-6", "SOC2-CC6.3"], "remediation": "Remove Owner role from service accounts; use least privilege roles."},
    {"id": "gcp-iam-002", "name": "Service account keys rotated every 90 days", "description": "User-managed service account keys must be rotated every 90 days", "provider": "gcp", "service": "iam", "severity": "high", "frameworks": ["CIS-1.7", "NIST-IA-5"], "remediation": "Rotate service account keys and delete keys older than 90 days."},
    {"id": "gcp-iam-003", "name": "No user-managed service account keys", "description": "Prefer Workload Identity over user-managed service account keys", "provider": "gcp", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.6", "NIST-IA-5"], "remediation": "Use Workload Identity Federation instead of service account key files."},
    {"id": "gcp-iam-004", "name": "MFA enforced for all users", "description": "2-Step Verification must be enforced for all Google accounts", "provider": "gcp", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.2", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enforce 2-Step Verification in Google Admin console."},
    {"id": "gcp-iam-005", "name": "IAM roles granted to Google Groups instead of users", "description": "Prefer granting roles to Google Groups rather than individual users", "provider": "gcp", "service": "iam", "severity": "medium", "frameworks": ["CIS-1.11", "NIST-AC-6"], "remediation": "Group IAM role assignments to Google Groups and manage membership centrally."},
    {"id": "gcp-iam-006", "name": "No primitive roles assigned to any principal", "description": "Owner/Editor/Viewer roles should not be used", "provider": "gcp", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.4", "NIST-AC-6", "SOC2-CC6.3"], "remediation": "Replace primitive roles with predefined roles that follow least privilege."},
    {"id": "gcp-iam-007", "name": "Service account impersonation limited", "description": "IAM roles allowing service account impersonation should be restricted", "provider": "gcp", "service": "iam", "severity": "high", "frameworks": ["NIST-AC-6"], "remediation": "Limit roles like iam.serviceAccountUser and iam.serviceAccountTokenCreator."},
    {"id": "gcp-iam-008", "name": "Domain restricted sharing enforced", "description": "Organization policy should restrict IAM members to your domain", "provider": "gcp", "service": "iam", "severity": "high", "frameworks": ["CIS-1.16", "NIST-AC-3"], "remediation": "Set domain restricted sharing constraint on organization policy."},
    # ─── Storage ────────────────────────────────────────────────────────────
    {"id": "gcp-storage-001", "name": "GCS buckets not publicly accessible", "description": "GCS buckets must not allow public access (allUsers or allAuthenticatedUsers)", "provider": "gcp", "service": "storage", "severity": "critical", "frameworks": ["CIS-5.1", "NIST-SC-7", "PCI-1.3", "SOC2-CC6.6"], "remediation": "Remove allUsers and allAuthenticatedUsers from GCS bucket IAM policies."},
    {"id": "gcp-storage-002", "name": "GCS bucket uniform access control enabled", "description": "Uniform bucket-level access should be enabled on all GCS buckets", "provider": "gcp", "service": "storage", "severity": "medium", "frameworks": ["CIS-5.2", "NIST-AC-3"], "remediation": "Enable uniform bucket-level access on all GCS buckets."},
    {"id": "gcp-storage-003", "name": "GCS bucket logging enabled", "description": "GCS data access logging must be enabled", "provider": "gcp", "service": "storage", "severity": "medium", "frameworks": ["CIS-5.3", "NIST-AU-2"], "remediation": "Enable data access audit logs for Google Cloud Storage."},
    {"id": "gcp-storage-004", "name": "GCS retention policy configured", "description": "GCS buckets with critical data should have retention policy", "provider": "gcp", "service": "storage", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Configure retention policy on GCS buckets for compliance data."},
    {"id": "gcp-storage-005", "name": "GCS bucket versioning enabled", "description": "GCS buckets should have object versioning enabled", "provider": "gcp", "service": "storage", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable object versioning on GCS buckets to protect against accidental deletion."},
    {"id": "gcp-storage-006", "name": "GCS CMEK encryption enabled", "description": "GCS buckets should use CMEK for data encryption", "provider": "gcp", "service": "storage", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Create and assign KMS CMEK key to GCS buckets."},
    {"id": "gcp-storage-007", "name": "GCS bucket CORS not overly permissive", "description": "GCS CORS configuration should not allow all origins", "provider": "gcp", "service": "storage", "severity": "medium", "frameworks": ["NIST-AC-3"], "remediation": "Restrict GCS CORS to specific trusted origins."},
    # ─── Compute ────────────────────────────────────────────────────────────
    {"id": "gcp-compute-001", "name": "VM instances have no public IP", "description": "Compute Engine instances should not have public IP addresses", "provider": "gcp", "service": "compute", "severity": "high", "frameworks": ["CIS-4.9", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Remove external IPs from VM instances; use Cloud NAT for outbound access."},
    {"id": "gcp-compute-002", "name": "OS login enabled on VM instances", "description": "OS Login must be enabled for centralized SSH key management", "provider": "gcp", "service": "compute", "severity": "medium", "frameworks": ["CIS-4.4", "NIST-IA-3"], "remediation": "Set enable-oslogin metadata key to TRUE on project or instance."},
    {"id": "gcp-compute-003", "name": "VM instances use shielded VM features", "description": "Secure Boot and vTPM must be enabled on VM instances", "provider": "gcp", "service": "compute", "severity": "medium", "frameworks": ["CIS-4.8", "NIST-SI-7"], "remediation": "Enable Secure Boot, vTPM, and Integrity Monitoring on VM instances."},
    {"id": "gcp-compute-004", "name": "Firewall rules do not allow unrestricted SSH/RDP", "description": "VPC firewall rules must not allow 0.0.0.0/0 on port 22 or 3389", "provider": "gcp", "service": "compute", "severity": "critical", "frameworks": ["CIS-3.6", "NIST-SC-7", "PCI-1.2.1"], "remediation": "Restrict firewall rules to known source IP ranges for SSH and RDP."},
    {"id": "gcp-compute-005", "name": "VM serial port access disabled", "description": "Serial port access to VM instances should be disabled", "provider": "gcp", "service": "compute", "severity": "medium", "frameworks": ["CIS-4.3", "NIST-AC-3"], "remediation": "Disable interactive serial port access on VM instances."},
    {"id": "gcp-compute-006", "name": "VM confidential computing enabled", "description": "Sensitive workload VMs should use confidential computing", "provider": "gcp", "service": "compute", "severity": "medium", "frameworks": ["NIST-SC-28"], "remediation": "Enable Confidential VM service on sensitive workload instances."},
    {"id": "gcp-compute-007", "name": "VM instance deletion protection enabled", "description": "VM instances should have deletion protection enabled", "provider": "gcp", "service": "compute", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Set deletionProtection flag to true on production VM instances."},
    {"id": "gcp-compute-008", "name": "VM disks encrypted with CMEK", "description": "VM boot and data disks should use CMEK encryption", "provider": "gcp", "service": "compute", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Create VM instances with CMEK-encrypted boot and data disks."},
    # ─── SQL ─────────────────────────────────────────────────────────────────
    {"id": "gcp-sql-001", "name": "Cloud SQL instances not publicly accessible", "description": "Cloud SQL instances must not have authorised network 0.0.0.0/0", "provider": "gcp", "service": "sql", "severity": "critical", "frameworks": ["CIS-6.2", "NIST-SC-7", "PCI-1.3"], "remediation": "Remove 0.0.0.0/0 from Cloud SQL authorised networks; use Cloud SQL Auth Proxy."},
    {"id": "gcp-sql-002", "name": "Cloud SQL backups enabled", "description": "Automated backups must be enabled for all Cloud SQL instances", "provider": "gcp", "service": "sql", "severity": "medium", "frameworks": ["CIS-6.7", "NIST-CP-9"], "remediation": "Enable automated backups and point-in-time recovery on Cloud SQL instances."},
    {"id": "gcp-sql-003", "name": "Cloud SQL SSL required for connections", "description": "Cloud SQL must require SSL for all connections", "provider": "gcp", "service": "sql", "severity": "high", "frameworks": ["CIS-6.4", "NIST-SC-8", "PCI-4.1"], "remediation": "Enable Require SSL in Cloud SQL instance settings."},
    {"id": "gcp-sql-004", "name": "Cloud SQL high availability enabled", "description": "Production Cloud SQL should have HA configured", "provider": "gcp", "service": "sql", "severity": "medium", "frameworks": ["NIST-CP-10", "SOC2-A1.1"], "remediation": "Enable high availability on Cloud SQL for production instances."},
    {"id": "gcp-sql-005", "name": "Cloud SQL deletion protection enabled", "description": "Cloud SQL instances should have deletion protection enabled", "provider": "gcp", "service": "sql", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable deletion protection on Cloud SQL instances."},
    # ─── Logging ─────────────────────────────────────────────────────────────
    {"id": "gcp-logging-001", "name": "Cloud Audit Logs enabled for all services", "description": "Data Access audit logs must be enabled for all Google Cloud services", "provider": "gcp", "service": "logging", "severity": "high", "frameworks": ["CIS-2.1", "NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable Data Access audit logs at the organisation or project level."},
    {"id": "gcp-logging-002", "name": "Log metric filter for project IAM changes", "description": "Alerts must exist for IAM policy changes", "provider": "gcp", "service": "logging", "severity": "medium", "frameworks": ["CIS-2.4", "NIST-AU-6"], "remediation": "Create log metric and alert for IAM policy change events."},
    {"id": "gcp-logging-003", "name": "Log metric filter for network route changes", "description": "Alerts must exist for VPC network route changes", "provider": "gcp", "service": "logging", "severity": "medium", "frameworks": ["CIS-2.8", "NIST-SC-7"], "remediation": "Create log metric and alert for VPC network route change events."},
    {"id": "gcp-logging-004", "name": "Log sink configured for long-term retention", "description": "Log sink should export logs to BigQuery or Cloud Storage", "provider": "gcp", "service": "logging", "severity": "medium", "frameworks": ["CIS-2.3", "NIST-AU-11", "PCI-10.7"], "remediation": "Create log sink to export logs to BigQuery or Cloud Storage with retention."},
    {"id": "gcp-logging-005", "name": "Log metric filter for firewall rule changes", "description": "Alerts should exist for VPC firewall rule changes", "provider": "gcp", "service": "logging", "severity": "medium", "frameworks": ["CIS-2.6", "NIST-SC-7"], "remediation": "Create log metric and alert for firewall rule change events."},
    {"id": "gcp-logging-006", "name": "Log metric filter for bucket IAM changes", "description": "Alerts should exist for GCS bucket IAM changes", "provider": "gcp", "service": "logging", "severity": "medium", "frameworks": ["CIS-2.7", "NIST-AC-3"], "remediation": "Create log metric and alert for Cloud Storage IAM change events."},
    # ─── KMS ─────────────────────────────────────────────────────────────────
    {"id": "gcp-kms-001", "name": "KMS cryptokeys have rotation period", "description": "Cloud KMS cryptographic keys must have rotation period set", "provider": "gcp", "service": "kms", "severity": "medium", "frameworks": ["CIS-1.9", "NIST-SC-12"], "remediation": "Set rotation period of 90 days or less on all KMS cryptokeys."},
    {"id": "gcp-kms-002", "name": "KMS keys not publicly accessible", "description": "Cloud KMS keys must not be accessible by allUsers or allAuthenticatedUsers", "provider": "gcp", "service": "kms", "severity": "critical", "frameworks": ["CIS-1.10", "NIST-SC-12", "SOC2-CC6.7"], "remediation": "Remove public IAM bindings from Cloud KMS keyring and key resources."},
    {"id": "gcp-kms-003", "name": "KMS key destruction scheduled", "description": "KMS keys pending destruction should be reviewed", "provider": "gcp", "service": "kms", "severity": "medium", "frameworks": ["NIST-SC-12"], "remediation": "Cancel KMS key destruction if not intended."},
    # ─── BigQuery ────────────────────────────────────────────────────────────
    {"id": "gcp-bq-001", "name": "BigQuery datasets not publicly accessible", "description": "BigQuery datasets must not allow public access", "provider": "gcp", "service": "bigquery", "severity": "critical", "frameworks": ["CIS-7.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Remove allUsers and allAuthenticatedUsers from BigQuery dataset IAM."},
    {"id": "gcp-bq-002", "name": "BigQuery datasets use CMEK encryption", "description": "BigQuery datasets should use CMEK for data at rest", "provider": "gcp", "service": "bigquery", "severity": "high", "frameworks": ["CIS-7.2", "NIST-SC-28", "PCI-3.4"], "remediation": "Configure BigQuery dataset default encryption with CMEK."},
    {"id": "gcp-bq-003", "name": "BigQuery authorized views properly controlled", "description": "BigQuery authorized views should be reviewed for data access", "provider": "gcp", "service": "bigquery", "severity": "medium", "frameworks": ["NIST-AC-3"], "remediation": "Review BigQuery authorized views to ensure least privilege access."},
    {"id": "gcp-bq-004", "name": "BigQuery cross-project access limited", "description": "BigQuery jobs should not access datasets across projects", "provider": "gcp", "service": "bigquery", "severity": "medium", "frameworks": ["NIST-AC-3"], "remediation": "Restrict BigQuery job cross-project query execution."},
    {"id": "gcp-bq-005", "name": "BigQuery table expiry configured", "description": "BigQuery tables should have default table expiration set", "provider": "gcp", "service": "bigquery", "severity": "low", "frameworks": ["NIST-CM-2"], "remediation": "Set default table expiration on BigQuery datasets."},
    # ─── GKE ─────────────────────────────────────────────────────────────────
    {"id": "gcp-gke-001", "name": "GKE clusters use workload identity", "description": "GKE clusters should use workload identity for GCP access", "provider": "gcp", "service": "gke", "severity": "high", "frameworks": ["CIS-GKE-3.1", "NIST-IA-5", "SOC2-CC6.3"], "remediation": "Enable workload identity on GKE node pools and configure service accounts."},
    {"id": "gcp-gke-002", "name": "GKE clusters use shielded nodes", "description": "GKE nodes should have shielded node features enabled", "provider": "gcp", "service": "gke", "severity": "high", "frameworks": ["CIS-GKE-2.1", "NIST-SI-7"], "remediation": "Enable shielded nodes on GKE cluster."},
    {"id": "gcp-gke-003", "name": "GKE clusters have network policy enabled", "description": "GKE clusters should enforce network policies", "provider": "gcp", "service": "gke", "severity": "high", "frameworks": ["CIS-GKE-4.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable network policy on GKE clusters."},
    {"id": "gcp-gke-004", "name": "GKE clusters have authorized networks configured", "description": "GKE master endpoint should be restricted to authorized networks", "provider": "gcp", "service": "gke", "severity": "medium", "frameworks": ["CIS-GKE-5.1", "NIST-SC-7"], "remediation": "Configure authorized networks on GKE cluster master endpoint."},
    {"id": "gcp-gke-005", "name": "GKE clusters are private clusters", "description": "GKE clusters should use private endpoint", "provider": "gcp", "service": "gke", "severity": "high", "frameworks": ["CIS-GKE-5.2", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable private cluster and disable public endpoint on GKE."},
    {"id": "gcp-gke-006", "name": "GKE cluster logging enabled", "description": "GKE clusters should have Cloud Logging enabled", "provider": "gcp", "service": "gke", "severity": "medium", "frameworks": ["CIS-GKE-6.1", "NIST-AU-2"], "remediation": "Enable Cloud Logging in GKE cluster configuration."},
    {"id": "gcp-gke-007", "name": "GKE cluster monitoring enabled", "description": "GKE clusters should have Cloud Monitoring enabled", "provider": "gcp", "service": "gke", "severity": "medium", "frameworks": ["CIS-GKE-6.2", "NIST-CA-7"], "remediation": "Enable Cloud Monitoring in GKE cluster configuration."},
    {"id": "gcp-gke-008", "name": "GKE clusters auto-upgrade enabled", "description": "GKE node pools should have auto-upgrade enabled", "provider": "gcp", "service": "gke", "severity": "medium", "frameworks": ["CIS-GKE-1.1", "NIST-SI-2"], "remediation": "Enable auto-upgrade on all GKE node pools."},
    {"id": "gcp-gke-009", "name": "GKE clusters release channel configured", "description": "GKE clusters should use a release channel for managed upgrades", "provider": "gcp", "service": "gke", "severity": "low", "frameworks": ["NIST-SI-2"], "remediation": "Assign GKE cluster to a release channel (stable or regular)."},
    # ─── VPC ─────────────────────────────────────────────────────────────────
    {"id": "gcp-vpc-001", "name": "VPC default network removed", "description": "Default VPC network should not be used for production", "provider": "gcp", "service": "vpc", "severity": "medium", "frameworks": ["CIS-3.1", "NIST-SC-7"], "remediation": "Delete the default VPC network or do not deploy resources in it."},
    {"id": "gcp-vpc-002", "name": "VPC Flow Logs enabled", "description": "VPC subnet flow logs should be enabled", "provider": "gcp", "service": "vpc", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable VPC flow logs on all subnets."},
    {"id": "gcp-vpc-003", "name": "VPC peering does not use default VPC", "description": "VPC peering should use custom VPC networks", "provider": "gcp", "service": "vpc", "severity": "low", "frameworks": ["NIST-SC-7"], "remediation": "Create custom VPCs and peer them, avoiding default VPC peering."},
    {"id": "gcp-vpc-004", "name": "VPC service perimeter configured", "description": "VPC Service Controls should be used for sensitive data", "provider": "gcp", "service": "vpc", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Configure VPC Service Controls perimeter to protect sensitive services."},
    # ─── Cloud Functions ─────────────────────────────────────────────────────
    {"id": "gcp-cfn-001", "name": "Cloud Function ingress limited to internal", "description": "Cloud Functions should not allow public internet access", "provider": "gcp", "service": "cloudfunction", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set ingress settings to Allow internal traffic only on Cloud Functions."},
    {"id": "gcp-cfn-002", "name": "Cloud Function requires HTTPS", "description": "Cloud Functions should be triggerable only via HTTPS", "provider": "gcp", "service": "cloudfunction", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Use HTTPS trigger with security level set at least TLS 1.2."},
    # ─── Cloud Run ───────────────────────────────────────────────────────────
    {"id": "gcp-cr-001", "name": "Cloud Run requires HTTPS", "description": "Cloud Run services should only accept HTTPS traffic", "provider": "gcp", "service": "cloudrun", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set Cloud Run ingress to require HTTPS."},
    {"id": "gcp-cr-002", "name": "Cloud Run ingress limited to internal", "description": "Cloud Run services should not be publicly accessible", "provider": "gcp", "service": "cloudrun", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set Cloud Run ingress to internal-only where possible."},
    {"id": "gcp-cr-003", "name": "Cloud Run VPC access configured", "description": "Cloud Run should use VPC connector for private network access", "provider": "gcp", "service": "cloudrun", "severity": "medium", "frameworks": ["NIST-SC-7"], "remediation": "Attach Serverless VPC Access connector to Cloud Run services."},
    # ─── Pub/Sub ─────────────────────────────────────────────────────────────
    {"id": "gcp-ps-001", "name": "Pub/Sub topics encrypted with CMEK", "description": "Pub/Sub topics should use CMEK for message encryption", "provider": "gcp", "service": "pubsub", "severity": "high", "frameworks": ["NIST-SC-28"], "remediation": "Configure CMEK on Pub/Sub topics."},
    {"id": "gcp-ps-002", "name": "Pub/Sub subscriptions have retention configured", "description": "Pub/Sub subscriptions should have message retention period set", "provider": "gcp", "service": "pubsub", "severity": "low", "frameworks": ["NIST-CP-2"], "remediation": "Set message retention duration on Pub/Sub subscriptions."},
    # ─── Cloud DNS ───────────────────────────────────────────────────────────
    {"id": "gcp-dns-001", "name": "Cloud DNS DNSSEC enabled", "description": "Cloud DNS managed zones should have DNSSEC enabled", "provider": "gcp", "service": "dns", "severity": "medium", "frameworks": ["CIS-3.7", "NIST-SC-20"], "remediation": "Enable DNSSEC on Cloud DNS managed zones."},
    {"id": "gcp-dns-002", "name": "Cloud DNS logging enabled", "description": "Cloud DNS queries should be logged", "provider": "gcp", "service": "dns", "severity": "low", "frameworks": ["NIST-AU-2"], "remediation": "Enable Cloud DNS query logging."},
    # ─── Spanner ─────────────────────────────────────────────────────────────
    {"id": "gcp-spanner-001", "name": "Spanner database encryption enabled", "description": "Cloud Spanner databases should have encryption configured", "provider": "gcp", "service": "spanner", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Use CMEK or Google-managed encryption for Spanner databases."},
    {"id": "gcp-spanner-002", "name": "Spanner backup retention configured", "description": "Cloud Spanner backups should be created and retained", "provider": "gcp", "service": "spanner", "severity": "medium", "frameworks": ["NIST-CP-9"], "remediation": "Schedule automated backups for Spanner databases."},
    # ─── Memcache/Redis ──────────────────────────────────────────────────────
    {"id": "gcp-mem-001", "name": "Memorystore Redis auth enabled", "description": "Memorystore Redis instances should have AUTH enabled", "provider": "gcp", "service": "memorystore", "severity": "high", "frameworks": ["NIST-AC-3"], "remediation": "Enable Redis AUTH on Memorystore Redis instances."},
    {"id": "gcp-mem-002", "name": "Memorystore in-transit encryption enabled", "description": "Memorystore should have in-transit encryption", "provider": "gcp", "service": "memorystore", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Enable in-transit encryption on Memorystore instances."},
    # ─── Dataflow ────────────────────────────────────────────────────────────
    {"id": "gcp-df-001", "name": "Dataflow jobs use customer-managed keys", "description": "Dataflow pipelines should use CMEK for encryption", "provider": "gcp", "service": "dataflow", "severity": "high", "frameworks": ["NIST-SC-28"], "remediation": "Specify CMEK KMS key on Dataflow pipeline options."},
]
