"""Azure cloud security check definitions. Used by cloud_checks_service.py."""
AZURE_CHECKS = [
    # ─── IAM ────────────────────────────────────────────────────────────────
    {"id": "azure-iam-001", "name": "Azure MFA enabled for all users", "description": "Multi-factor authentication must be enabled for all Azure AD users", "provider": "azure", "service": "iam", "severity": "critical", "frameworks": ["CIS-1.1.2", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enable MFA via Conditional Access or per-user MFA in Azure AD."},
    {"id": "azure-iam-002", "name": "No guest users with administrative roles", "description": "Guest users should not be assigned administrative directory roles", "provider": "azure", "service": "iam", "severity": "high", "frameworks": ["CIS-1.2.2", "NIST-AC-6"], "remediation": "Remove administrative role assignments from guest users."},
    {"id": "azure-iam-003", "name": "Privileged Identity Management (PIM) enabled", "description": "PIM should be used for privileged role management", "provider": "azure", "service": "iam", "severity": "high", "frameworks": ["CIS-1.2.3", "NIST-AC-6", "SOC2-CC6.3"], "remediation": "Enable Azure AD PIM for just-in-time privileged access."},
    {"id": "azure-iam-004", "name": "Conditional access policy for admin roles", "description": "Conditional Access policies must protect administrative accounts", "provider": "azure", "service": "iam", "severity": "high", "frameworks": ["CIS-1.2.1", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Create Conditional Access policy requiring MFA for all admin sign-ins."},
    {"id": "azure-iam-005", "name": "No legacy authentication allowed", "description": "Legacy authentication protocols should be blocked", "provider": "azure", "service": "iam", "severity": "critical", "frameworks": ["CIS-2.1.3", "NIST-IA-2", "SOC2-CC6.1"], "remediation": "Create Conditional Access policy to block legacy auth."},
    {"id": "azure-iam-006", "name": "Self-service password reset enabled", "description": "Self-service password reset should be enabled for all users", "provider": "azure", "service": "iam", "severity": "medium", "frameworks": ["NIST-IA-5"], "remediation": "Enable SSPR in Azure AD."},
    {"id": "azure-iam-007", "name": "External identities limited to trusted domains", "description": "B2B collaboration should be restricted to approved domains", "provider": "azure", "service": "iam", "severity": "high", "frameworks": ["NIST-AC-3", "SOC2-CC6.1"], "remediation": "Configure Azure AD cross-tenant access settings to allow only approved domains."},
    {"id": "azure-iam-008", "name": "Security defaults enabled", "description": "Azure AD security defaults should be enabled for basic MFA protection", "provider": "azure", "service": "iam", "severity": "medium", "frameworks": ["NIST-IA-2"], "remediation": "Enable Azure AD security defaults."},
    {"id": "azure-iam-009", "name": "Password hash sync enabled", "description": "Azure AD Connect password hash sync should be enabled", "provider": "azure", "service": "iam", "severity": "low", "frameworks": ["NIST-IA-5"], "remediation": "Enable password hash synchronisation in Azure AD Connect."},
    # ─── Storage ─────────────────────────────────────────────────────────────
    {"id": "azure-storage-001", "name": "Storage accounts require HTTPS only", "description": "Azure storage accounts must enforce HTTPS connections only", "provider": "azure", "service": "storage", "severity": "high", "frameworks": ["CIS-3.1", "NIST-SC-8", "PCI-4.1"], "remediation": "Enable Secure transfer required on all storage accounts."},
    {"id": "azure-storage-002", "name": "Storage accounts not publicly accessible", "description": "Public blob access must be disabled on storage accounts", "provider": "azure", "service": "storage", "severity": "critical", "frameworks": ["CIS-3.5", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Disable Allow Blob Public Access on all storage accounts."},
    {"id": "azure-storage-003", "name": "Storage account encryption with CMK", "description": "Storage accounts should use customer-managed keys for encryption", "provider": "azure", "service": "storage", "severity": "medium", "frameworks": ["CIS-3.2", "NIST-SC-28", "PCI-3.4"], "remediation": "Configure storage account encryption to use CMK stored in Key Vault."},
    {"id": "azure-storage-004", "name": "Storage account network access restricted", "description": "Storage account firewalls should restrict access to trusted networks", "provider": "azure", "service": "storage", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Configure storage account firewall to allow only trusted IPs and VNets."},
    {"id": "azure-storage-005", "name": "Storage account soft delete enabled", "description": "Blob soft delete should be enabled on storage accounts", "provider": "azure", "service": "storage", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable blob soft delete with retention period of at least 7 days."},
    {"id": "azure-storage-006", "name": "Storage account minimum TLS version 1.2", "description": "Storage accounts should require TLS 1.2 minimum", "provider": "azure", "service": "storage", "severity": "high", "frameworks": ["CIS-3.3", "NIST-SC-8", "PCI-4.1"], "remediation": "Set minimum TLS version to 1.2 on storage accounts."},
    # ─── Network ─────────────────────────────────────────────────────────────
    {"id": "azure-network-001", "name": "NSG restricts SSH/RDP from internet", "description": "Network Security Groups must not allow SSH/RDP from any source", "provider": "azure", "service": "network", "severity": "critical", "frameworks": ["CIS-6.1", "NIST-SC-7", "PCI-1.2.1", "SOC2-CC6.6"], "remediation": "Remove inbound NSG rules allowing port 22 or 3389 from 0.0.0.0/0."},
    {"id": "azure-network-002", "name": "Azure DDoS Protection Standard enabled", "description": "DDoS Protection Standard should be enabled on virtual networks", "provider": "azure", "service": "network", "severity": "medium", "frameworks": ["NIST-SC-5", "SOC2-A1.1"], "remediation": "Enable Azure DDoS Protection Standard on all production VNets."},
    {"id": "azure-network-003", "name": "Azure Firewall or WAF deployed", "description": "Web-facing resources should be protected by WAF or Azure Firewall", "provider": "azure", "service": "network", "severity": "high", "frameworks": ["CIS-6.5", "NIST-SC-7", "PCI-6.4"], "remediation": "Deploy Azure WAF or Azure Firewall in front of internet-facing resources."},
    {"id": "azure-network-004", "name": "NSG flow logs enabled", "description": "NSG flow logs should be enabled for traffic monitoring", "provider": "azure", "service": "network", "severity": "medium", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Enable NSG flow logs with Log Analytics workspace destination."},
    {"id": "azure-network-005", "name": "VNet peering connection encrypted", "description": "VNet peering connections should use VPN Gateway for encryption", "provider": "azure", "service": "network", "severity": "low", "frameworks": ["NIST-SC-8"], "remediation": "Route traffic through VPN Gateway for encrypted cross-region peering."},
    {"id": "azure-network-006", "name": "Subnet with NSG attached", "description": "All subnets should have a network security group associated", "provider": "azure", "service": "network", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Associate an NSG to every subnet."},
    {"id": "azure-network-007", "name": "Azure Bastion deployed for VM access", "description": "Azure Bastion should be used instead of public IPs on VMs", "provider": "azure", "service": "network", "severity": "medium", "frameworks": ["NIST-AC-3"], "remediation": "Deploy Azure Bastion and remove public IP addresses from VMs."},
    # ─── SQL ─────────────────────────────────────────────────────────────────
    {"id": "azure-sql-001", "name": "Azure SQL transparent data encryption enabled", "description": "TDE must be enabled on all Azure SQL databases", "provider": "azure", "service": "sql", "severity": "high", "frameworks": ["CIS-4.1.2", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable Transparent Data Encryption on all SQL databases."},
    {"id": "azure-sql-002", "name": "Azure SQL Advanced Threat Protection enabled", "description": "Advanced Threat Protection must be enabled on SQL servers", "provider": "azure", "service": "sql", "severity": "high", "frameworks": ["CIS-4.2.1", "NIST-IR-4", "SOC2-CC7.3"], "remediation": "Enable Microsoft Defender for SQL on all SQL servers."},
    {"id": "azure-sql-003", "name": "SQL server auditing enabled", "description": "Azure SQL server auditing must be enabled", "provider": "azure", "service": "sql", "severity": "medium", "frameworks": ["CIS-4.1.3", "NIST-AU-2", "PCI-10.1"], "remediation": "Enable auditing at the SQL server level to Log Analytics or Storage."},
    {"id": "azure-sql-004", "name": "SQL server firewall restricts public access", "description": "Azure SQL server firewall should not allow all Azure services", "provider": "azure", "service": "sql", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Restrict SQL server firewall rules to specific IPs and disable Azure Services access."},
    {"id": "azure-sql-005", "name": "SQL databases have backup retention configured", "description": "Azure SQL long-term backup retention should be configured", "provider": "azure", "service": "sql", "severity": "medium", "frameworks": ["NIST-CP-9"], "remediation": "Configure long-term backup retention policy for Azure SQL databases."},
    {"id": "azure-sql-006", "name": "SQL database minimal TLS version 1.2", "description": "Azure SQL should enforce TLS 1.2", "provider": "azure", "service": "sql", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set minimal TLS version to 1.2 for SQL server."},
    # ─── Key Vault ───────────────────────────────────────────────────────────
    {"id": "azure-kv-001", "name": "Key Vault soft delete enabled", "description": "Azure Key Vault soft-delete must be enabled to prevent accidental deletion", "provider": "azure", "service": "keyvault", "severity": "high", "frameworks": ["CIS-8.1", "NIST-CP-10"], "remediation": "Enable soft-delete and purge protection on all Key Vaults."},
    {"id": "azure-kv-002", "name": "Key Vault key expiry date set", "description": "All Key Vault keys must have an expiry date configured", "provider": "azure", "service": "keyvault", "severity": "medium", "frameworks": ["CIS-8.2", "NIST-SC-12"], "remediation": "Set expiry dates on all Key Vault keys and certificates."},
    {"id": "azure-kv-003", "name": "Key Vault firewall enabled", "description": "Key Vault should restrict public network access via firewall", "provider": "azure", "service": "keyvault", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable Key Vault firewall and restrict to trusted IPs and services."},
    {"id": "azure-kv-004", "name": "Key Vault RBAC used instead of access policies", "description": "Key Vault should use Azure RBAC for authorization", "provider": "azure", "service": "keyvault", "severity": "medium", "frameworks": ["NIST-AC-6", "SOC2-CC6.3"], "remediation": "Migrate Key Vault access policies to Azure RBAC."},
    {"id": "azure-kv-005", "name": "Key Vault key rotation reminder configured", "description": "Key Vault keys should have rotation notification configured", "provider": "azure", "service": "keyvault", "severity": "low", "frameworks": ["NIST-SC-12"], "remediation": "Configure key rotation notification for Key Vault keys."},
    # ─── Monitoring ──────────────────────────────────────────────────────────
    {"id": "azure-monitor-001", "name": "Azure Defender for Cloud enabled", "description": "Microsoft Defender for Cloud must be enabled on all subscriptions", "provider": "azure", "service": "monitor", "severity": "high", "frameworks": ["CIS-2.1.15", "NIST-CA-7", "SOC2-CC7.2"], "remediation": "Enable Microsoft Defender for Cloud on all Azure subscriptions."},
    {"id": "azure-monitor-002", "name": "Activity log alerts for critical operations", "description": "Alerts must exist for create/update/delete of critical resources", "provider": "azure", "service": "monitor", "severity": "medium", "frameworks": ["CIS-5.2.1", "NIST-AU-6"], "remediation": "Create activity log alerts for key administrative operations."},
    {"id": "azure-monitor-003", "name": "Diagnostic settings configured for all resources", "description": "All Azure resources should have diagnostic settings streaming logs", "provider": "azure", "service": "monitor", "severity": "high", "frameworks": ["NIST-AU-2", "SOC2-CC7.2"], "remediation": "Configure diagnostic settings to send logs to Log Analytics workspace."},
    {"id": "azure-monitor-004", "name": "Log Analytics workspace retention at least 365 days", "description": "Log Analytics should have retention set to at least 365 days", "provider": "azure", "service": "monitor", "severity": "medium", "frameworks": ["CIS-5.2.6", "NIST-AU-11", "PCI-10.7"], "remediation": "Set Log Analytics workspace retention to at least 365 days."},
    {"id": "azure-monitor-005", "name": "Security contact details configured", "description": "Azure security contact information should be configured", "provider": "azure", "service": "monitor", "severity": "medium", "frameworks": ["NIST-IR-6"], "remediation": "Configure security contact email and phone in Microsoft Defender for Cloud."},
    # ─── App Service ─────────────────────────────────────────────────────────
    {"id": "azure-appsvc-001", "name": "App Service enforces HTTPS only", "description": "App Service should redirect HTTP to HTTPS", "provider": "azure", "service": "appservice", "severity": "critical", "frameworks": ["CIS-9.2", "NIST-SC-8", "PCI-4.1"], "remediation": "Set HTTPS Only to On in App Service TLS/SSL settings."},
    {"id": "azure-appsvc-002", "name": "App Service uses managed identity", "description": "App Service should use managed identity not key-based auth", "provider": "azure", "service": "appservice", "severity": "high", "frameworks": ["NIST-IA-5", "SOC2-CC6.3"], "remediation": "Enable managed identity on App Service and replace connection strings with identity-based access."},
    {"id": "azure-appsvc-003", "name": "App Service uses TLS 1.2", "description": "App Service should enforce TLS 1.2 minimum version", "provider": "azure", "service": "appservice", "severity": "high", "frameworks": ["CIS-9.4", "NIST-SC-8", "PCI-4.1"], "remediation": "Set minimum TLS version to 1.2 in App Service TLS/SSL settings."},
    {"id": "azure-appsvc-004", "name": "App Service remote debugging disabled", "description": "App Service remote debugging should be disabled in production", "provider": "azure", "service": "appservice", "severity": "medium", "frameworks": ["NIST-CM-2"], "remediation": "Disable remote debugging on App Service in production slots."},
    {"id": "azure-appsvc-005", "name": "App Service client certificates enabled", "description": "App Service should require incoming client certificates", "provider": "azure", "service": "appservice", "severity": "medium", "frameworks": ["NIST-IA-2"], "remediation": "Set client certificate mode to Required in App Service configuration."},
    {"id": "azure-appsvc-006", "name": "App Service logging enabled", "description": "App Service application logging should be enabled", "provider": "azure", "service": "appservice", "severity": "medium", "frameworks": ["NIST-AU-2"], "remediation": "Enable App Service application logging to file system or blob."},
    {"id": "azure-appsvc-007", "name": "App Service authentication enabled", "description": "App Service should have authentication configured", "provider": "azure", "service": "appservice", "severity": "high", "frameworks": ["NIST-IA-2", "SOC2-CC6.1"], "remediation": "Enable App Service Authentication with Azure AD provider."},
    # ─── Container Registry ──────────────────────────────────────────────────
    {"id": "azure-acr-001", "name": "ACR admin user disabled", "description": "ACR admin account should be disabled for security", "provider": "azure", "service": "containerregistry", "severity": "high", "frameworks": ["CIS-7.2", "NIST-AC-6"], "remediation": "Disable the admin user on ACR registries; use managed identity instead."},
    {"id": "azure-acr-002", "name": "ACR geo-replication enabled", "description": "ACR should have geo-replication for DR", "provider": "azure", "service": "containerregistry", "severity": "medium", "frameworks": ["NIST-CP-10"], "remediation": "Enable geo-replication on ACR registries for disaster recovery."},
    {"id": "azure-acr-003", "name": "ACR content trust enabled", "description": "ACR should have content trust for image signing", "provider": "azure", "service": "containerregistry", "severity": "medium", "frameworks": ["NIST-SA-10", "SOC2-CC6.8"], "remediation": "Enable content trust in ACR to enforce signed images."},
    {"id": "azure-acr-004", "name": "ACR image vulnerability scanning enabled", "description": "ACR should scan images for vulnerabilities", "provider": "azure", "service": "containerregistry", "severity": "high", "frameworks": ["NIST-RA-5", "SOC2-CC7.1"], "remediation": "Enable Microsoft Defender for Container Registry image scanning."},
    {"id": "azure-acr-005", "name": "ACR restricted public network access", "description": "ACR should limit public network access via firewall", "provider": "azure", "service": "containerregistry", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set ACR public network access to Disabled or restrict to trusted IPs."},
    # ─── AKS ─────────────────────────────────────────────────────────────────
    {"id": "azure-aks-001", "name": "AKS RBAC enabled", "description": "AKS clusters must have RBAC enabled", "provider": "azure", "service": "aks", "severity": "critical", "frameworks": ["CIS-AKS-1.1", "NIST-AC-3", "SOC2-CC6.3"], "remediation": "Enable RBAC on AKS cluster with Azure AD integration."},
    {"id": "azure-aks-002", "name": "AKS authorized IP ranges for API server", "description": "AKS API server should restrict access to authorized IPs", "provider": "azure", "service": "aks", "severity": "high", "frameworks": ["CIS-AKS-2.1", "NIST-SC-7", "SOC2-CC6.6"], "remediation": "Set authorized IP ranges on AKS cluster API server."},
    {"id": "azure-aks-003", "name": "AKS uses managed identity", "description": "AKS clusters should use managed identity not service principal", "provider": "azure", "service": "aks", "severity": "high", "frameworks": ["NIST-IA-5"], "remediation": "Use managed identity for AKS clusters."},
    {"id": "azure-aks-004", "name": "AKS Azure Policy add-on enabled", "description": "AKS should have Azure Policy add-on for gatekeeper", "provider": "azure", "service": "aks", "severity": "medium", "frameworks": ["NIST-SI-3"], "remediation": "Enable Azure Policy add-on on AKS clusters."},
    {"id": "azure-aks-005", "name": "AKS private cluster enabled", "description": "AKS clusters should be private with no public endpoint", "provider": "azure", "service": "aks", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable AKS private cluster to restrict API server to VNet."},
    {"id": "azure-aks-006", "name": "AKS HTTP application routing disabled", "description": "AKS HTTP application routing add-on should be disabled", "provider": "azure", "service": "aks", "severity": "medium", "frameworks": ["NIST-CM-2"], "remediation": "Disable HTTP application routing add-on on AKS clusters."},
    {"id": "azure-aks-007", "name": "AKS cluster auto-upgrade enabled", "description": "AKS should have auto-upgrade channel configured", "provider": "azure", "service": "aks", "severity": "medium", "frameworks": ["NIST-SI-2"], "remediation": "Set AKS cluster auto-upgrade channel to stable or rapid."},
    # ─── Compute ─────────────────────────────────────────────────────────────
    {"id": "azure-compute-001", "name": "VM disks encrypted with SSE", "description": "Azure managed disks should have SSE enabled", "provider": "azure", "service": "compute", "severity": "high", "frameworks": ["CIS-7.1", "NIST-SC-28", "PCI-3.4"], "remediation": "Enable server-side encryption on all managed disks."},
    {"id": "azure-compute-002", "name": "VM managed disks used instead of unmanaged", "description": "All VMs should use managed disks", "provider": "azure", "service": "compute", "severity": "medium", "frameworks": ["NIST-CM-2"], "remediation": "Migrate VMs from unmanaged to managed disks."},
    {"id": "azure-compute-003", "name": "VM endpoint protection installed", "description": "VMs should have endpoint protection installed", "provider": "azure", "service": "compute", "severity": "high", "frameworks": ["CIS-7.5", "NIST-SI-3"], "remediation": "Install Microsoft Antimalware or endpoint protection on all VMs."},
    {"id": "azure-compute-004", "name": "VM agent auto-provisioned", "description": "Azure VM agent should be auto-provisioned", "provider": "azure", "service": "compute", "severity": "low", "frameworks": ["NIST-CM-2"], "remediation": "Enable automatic provisioning of Log Analytics agent for VMs."},
    # ─── Cosmos DB ───────────────────────────────────────────────────────────
    {"id": "azure-cosmos-001", "name": "Cosmos DB firewall enabled", "description": "Cosmos DB should have network firewall enabled", "provider": "azure", "service": "cosmosdb", "severity": "high", "frameworks": ["NIST-SC-7", "SOC2-CC6.6"], "remediation": "Enable Cosmos DB IP firewall to restrict access."},
    {"id": "azure-cosmos-002", "name": "Cosmos DB encryption at rest enabled", "description": "Cosmos DB data should be encrypted at rest", "provider": "azure", "service": "cosmosdb", "severity": "high", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Cosmos DB encryption at rest is enabled by default; add CMK if required."},
    # ─── Event Hub ───────────────────────────────────────────────────────────
    {"id": "azure-eh-001", "name": "Event Hub encryption at rest enabled", "description": "Event Hub namespace should have encryption at rest", "provider": "azure", "service": "eventhub", "severity": "medium", "frameworks": ["NIST-SC-28", "PCI-3.4"], "remediation": "Enable KMS encryption for Event Hub namespaces."},
    {"id": "azure-eh-002", "name": "Event Hub auto-inflate enabled", "description": "Event Hub namespace should have auto-inflate for scaling", "provider": "azure", "service": "eventhub", "severity": "low", "frameworks": ["NIST-CP-2"], "remediation": "Enable auto-inflate on Event Hub namespaces."},
    # ─── Service Bus ─────────────────────────────────────────────────────────
    {"id": "azure-sb-001", "name": "Service Bus encryption at rest enabled", "description": "Service Bus namespace should have encryption at rest", "provider": "azure", "service": "servicebus", "severity": "medium", "frameworks": ["NIST-SC-28"], "remediation": "Enable KMS encryption for Service Bus namespaces."},
    # ─── CDN ─────────────────────────────────────────────────────────────────
    {"id": "azure-cdn-001", "name": "CDN enforces HTTPS", "description": "Azure CDN endpoints should enforce HTTPS", "provider": "azure", "service": "cdn", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Enable HTTPS protocol on CDN endpoint."},
    # ─── Redis Cache ─────────────────────────────────────────────────────────
    {"id": "azure-redis-001", "name": "Redis cache SSL access enabled", "description": "Azure Cache for Redis should require SSL", "provider": "azure", "service": "redis", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Enable Non-SSL port disabled in Redis cache settings."},
    {"id": "azure-redis-002", "name": "Redis cache firewall rules restricted", "description": "Azure Redis cache should restrict access via firewall", "provider": "azure", "service": "redis", "severity": "high", "frameworks": ["NIST-SC-7"], "remediation": "Configure Redis cache firewall rules to allow only trusted IPs."},
    # ─── Front Door ──────────────────────────────────────────────────────────
    {"id": "azure-fd-001", "name": "Front Door WAF policy attached", "description": "Front Door should have WAF policy attached", "provider": "azure", "service": "frontdoor", "severity": "high", "frameworks": ["NIST-SC-7", "PCI-6.4"], "remediation": "Attach WAF policy to Front Door endpoints."},
    {"id": "azure-fd-002", "name": "Front Door enforces HTTPS", "description": "Front Door should redirect HTTP to HTTPS", "provider": "azure", "service": "frontdoor", "severity": "critical", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set Front Door to redirect HTTP to HTTPS."},
    # ─── Functions ───────────────────────────────────────────────────────────
    {"id": "azure-func-001", "name": "Function App enforces HTTPS", "description": "Azure Functions should enforce HTTPS only", "provider": "azure", "service": "functionapp", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Set HTTPS Only to On in Function App configuration."},
    {"id": "azure-func-002", "name": "Function App uses managed identity", "description": "Azure Functions should use managed identity", "provider": "azure", "service": "functionapp", "severity": "high", "frameworks": ["NIST-IA-5"], "remediation": "Enable managed identity on Function App."},
    {"id": "azure-func-003", "name": "Function App authentication configured", "description": "Azure Functions should have authentication enabled", "provider": "azure", "service": "functionapp", "severity": "medium", "frameworks": ["NIST-IA-2"], "remediation": "Enable App Service Authentication on Function App."},
    # ─── API Management ──────────────────────────────────────────────────────
    {"id": "azure-apim-001", "name": "API Management enforces HTTPS", "description": "API Management should only accept HTTPS traffic", "provider": "azure", "service": "apim", "severity": "high", "frameworks": ["NIST-SC-8", "PCI-4.1"], "remediation": "Disable HTTP endpoint in API Management."},
    {"id": "azure-apim-002", "name": "API Management minimum TLS 1.2", "description": "API Management should enforce TLS 1.2", "provider": "azure", "service": "apim", "severity": "high", "frameworks": ["NIST-SC-8"], "remediation": "Set API Management TLS version to 1.2."},
    # ─── Automation ──────────────────────────────────────────────────────────
    {"id": "azure-auto-001", "name": "Automation account encrypted variables", "description": "Automation account variables should be encrypted", "provider": "azure", "service": "automation", "severity": "medium", "frameworks": ["NIST-SC-28"], "remediation": "Mark sensitive Automation account variables as encrypted."},
]
