"""KISA ISMS — Korea Information Security Management System."""
FRAMEWORK_ID = "kisa_isms"; FRAMEWORK_NAME = "KISA ISMS"; FRAMEWORK_VERSION = "2023"
CONTROLS = [
    {"id":"ISMS-1.1","theme":"Management","check_type":"policies_present","title":"ISMS policy","description":"Establish information security management policy."},
    {"id":"ISMS-1.2","theme":"Management","check_type":"documents_exist","title":"ISMS scope","description":"Define and document ISMS scope."},
    {"id":"ISMS-2.1","theme":"Governance","check_type":"separation_of_duties","title":"CEO commitment","description":"CEO approves security policy and resources."},
    {"id":"ISMS-2.2","theme":"Governance","check_type":"training_present","title":"Security organization","description":"Organize internal security organization."},
    {"id":"ISMS-3.1","theme":"Risk","check_type":"risk_assessment_completed","title":"Risk assessment","description":"Regular information asset risk assessment."},
    {"id":"ISMS-3.2","theme":"Risk","check_type":"pen_testing","title":"Risk treatment","description":"Implement risk treatment plan."},
    {"id":"ISMS-4.1","theme":"Policy","check_type":"policies_present","title":"Security policies","description":"Document and enforce security policies."},
    {"id":"ISMS-4.2","theme":"Policy","check_type":"training_present","title":"Policy review","description":"Regular policy review and update."},
    {"id":"ISMS-5.1","theme":"Asset","check_type":"inventory","title":"Asset management","description":"Maintain information asset inventory."},
    {"id":"ISMS-5.2","theme":"Asset","check_type":"data_classification","title":"Asset classification","description":"Classify assets by criticality."},
    {"id":"ISMS-6.1","theme":"HR","check_type":"background_checks","title":"Personnel security","description":"Background checks for employees."},
    {"id":"ISMS-6.2","theme":"HR","check_type":"training_present","title":"Security training","description":"Regular security awareness training."},
    {"id":"ISMS-7.1","theme":"Physical","check_type":"access_control_system","title":"Physical security","description":"Physical access controls for facilities."},
    {"id":"ISMS-7.2","theme":"Physical","check_type":"cctv_present","title":"Physical monitoring","description":"Physical security monitoring."},
    {"id":"ISMS-8.1","theme":"Access","check_type":"rbac_configured","title":"Access control","description":"User access management and review."},
    {"id":"ISMS-8.2","theme":"Access","check_type":"mfa_configured","title":"Authentication","description":"Strong authentication for critical systems."},
    {"id":"ISMS-9.1","theme":"Crypto","check_type":"disk_encrypted","title":"Encryption","description":"Encrypt important data at rest and in transit."},
    {"id":"ISMS-9.2","theme":"Crypto","check_type":"kms_configured","title":"Key management","description":"Secure key management."},
    {"id":"ISMS-10.1","theme":"Operations","check_type":"patch_management","title":"Patch management","description":"Systematic patch management."},
    {"id":"ISMS-10.2","theme":"Operations","check_type":"malware_protection","title":"Malware protection","description":"Anti-malware and endpoint protection."},
    {"id":"ISMS-10.3","theme":"Operations","check_type":"backup_completed","title":"Backup","description":"Regular data backup."},
    {"id":"ISMS-11.1","theme":"Network","check_type":"fw_blocked","title":"Network security","description":"Network segmentation and firewalls."},
    {"id":"ISMS-11.2","theme":"Network","check_type":"ids_ips_enabled","title":"IDS/IPS","description":"Intrusion detection and prevention."},
    {"id":"ISMS-11.3","theme":"Network","check_type":"tls_enabled","title":"Secure communications","description":"Use secure protocols for communication."},
    {"id":"ISMS-12.1","theme":"Incident","check_type":"incident_handling","title":"Incident response","description":"Incident response procedure."},
    {"id":"ISMS-12.2","theme":"Incident","check_type":"incident_reporting","title":"Incident reporting","description":"Report security incidents to management."},
    {"id":"ISMS-13.1","theme":"BCP","check_type":"backup_dr","title":"BCP","description":"Business continuity plan."},
    {"id":"ISMS-13.2","theme":"BCP","check_type":"tests_performed","title":"BCP testing","description":"Regular BCP drills."},
    {"id":"ISMS-14.1","theme":"Compliance","check_type":"assessments_performed","title":"Compliance review","description":"Review compliance with ISMS requirements."},
    {"id":"ISMS-14.2","theme":"Compliance","check_type":"pen_testing","title":"Internal audit","description":"Conduct internal ISMS audits."},
    {"id":"ISMS-15.1","theme":"Third-Party","check_type":"supplier_assessment","title":"Vendor security","description":"Assess third-party service providers."},
    {"id":"ISMS-15.2","theme":"Third-Party","check_type":"contracts_signed","title":"Outsourcing security","description":"Security requirements for outsourced services."},
    {"id":"ISMS-16.1","theme":"Review","check_type":"assessments_performed","title":"Management review","description":"Management review of ISMS."},
    {"id":"ISMS-16.2","theme":"Review","check_type":"continuous_monitoring","title":"Corrective actions","description":"Implement corrective actions from findings."},
]
