"""FedRAMP High — NIST 800-53 High baseline (131 of 421 controls implemented; full baseline pending)."""
from __future__ import annotations
from typing import Any, Dict, List

FRAMEWORK_ID = "fedramp_high"
FRAMEWORK_NAME = "FedRAMP High"
FRAMEWORK_VERSION = "Rev 5 (2024)"

CONTROLS: List[Dict[str, Any]] = [
    {"id": "AC-1", "theme": "Access Control", "check_type": "policies_present", "title": "Access Control Policy and Procedures", "description": "Develop and maintain access control policies."},
    {"id": "AC-2", "theme": "Access Control", "check_type": "count_gt_zero", "check_collection": "compliance_policies", "title": "Account Management", "description": "Manage information system accounts."},
    {"id": "AC-3", "theme": "Access Control", "check_type": "rbac_configured", "title": "Access Enforcement", "description": "Enforce approved authorizations for logical access."},
    {"id": "AC-4", "theme": "Access Control", "check_type": "fw_blocked", "title": "Information Flow Enforcement", "description": "Enforce approved information flow controls."},
    {"id": "AC-5", "theme": "Access Control", "check_type": "separation_of_duties", "title": "Separation of Duties", "description": "Separate duties of individuals to reduce risk."},
    {"id": "AC-6", "theme": "Access Control", "check_type": "least_privilege", "title": "Least Privilege", "description": "Employ least privilege for users and processes."},
    {"id": "AC-7", "theme": "Access Control", "check_type": "lockout_policy", "title": "Unsuccessful Logon Attempts", "description": "Enforce limit on consecutive invalid logon attempts."},
    {"id": "AC-8", "theme": "Access Control", "check_type": "banner_present", "title": "System Use Notification", "description": "Display system use notification before access."},
    {"id": "AC-10", "theme": "Access Control", "check_type": "concurrent_sessions", "title": "Concurrent Session Control", "description": "Limit concurrent sessions per user."},
    {"id": "AC-11", "theme": "Access Control", "check_type": "session_lock", "title": "Session Lock", "description": "Initiate session lock after inactivity."},
    {"id": "AC-14", "theme": "Access Control", "check_type": "permitted_actions", "title": "Permitted Actions Without Identification", "description": "Identify permitted user actions without ID."},
    {"id": "AC-17", "theme": "Access Control", "check_type": "remote_access", "title": "Remote Access", "description": "Authorize and control remote access."},
    {"id": "AC-18", "theme": "Access Control", "check_type": "wireless_restricted", "title": "Wireless Access", "description": "Control wireless access."},
    {"id": "AC-19", "theme": "Access Control", "check_type": "mobile_device_policy", "title": "Mobile Devices", "description": "Control mobile device access."},
    {"id": "AC-20", "theme": "Access Control", "check_type": "third_party_access", "title": "Use of External Information Systems", "description": "Limit use of external systems."},
    {"id": "AU-1", "theme": "Audit & Accountability", "check_type": "policies_present", "title": "Audit Policy and Procedures", "description": "Develop audit policies."},
    {"id": "AU-2", "theme": "Audit & Accountability", "check_type": "audit_log_volume", "title": "Audit Events", "description": "Define auditable events."},
    {"id": "AU-3", "theme": "Audit & Accountability", "check_type": "audit_log_content", "title": "Content of Audit Records", "description": "Include event details in audit logs."},
    {"id": "AU-4", "theme": "Audit & Accountability", "check_type": "storage_capacity", "title": "Audit Storage Capacity", "description": "Allocate storage for audit events."},
    {"id": "AU-5", "theme": "Audit & Accountability", "check_type": "alert_configured", "title": "Response to Audit Processing Failures", "description": "Alert on audit processing failures."},
    {"id": "AU-6", "theme": "Audit & Accountability", "check_type": "audit_review", "title": "Audit Review, Analysis, and Reporting", "description": "Review and analyze audit records."},
    {"id": "AU-7", "theme": "Audit & Accountability", "check_type": "audit_reduction", "title": "Audit Reduction and Report Generation", "description": "Provide audit reduction and reporting capability."},
    {"id": "AU-8", "theme": "Audit & Accountability", "check_type": "ntp_configured", "title": "Time Stamps", "description": "Use trusted time sources for audit stamps."},
    {"id": "AU-9", "theme": "Audit & Accountability", "check_type": "audit_protection", "title": "Protection of Audit Information", "description": "Protect audit logs from modification."},
    {"id": "AU-11", "theme": "Audit & Accountability", "check_type": "log_retention", "title": "Audit Record Retention", "description": "Retain audit records as required."},
    {"id": "AU-12", "theme": "Audit & Accountability", "check_type": "audit_generation", "title": "Audit Generation", "description": "Generate audit records for defined events."},
    {"id": "CA-1", "theme": "Security Assessment", "check_type": "policies_present", "title": "Assessment Policy and Procedures", "description": "Develop assessment policies."},
    {"id": "CA-2", "theme": "Security Assessment", "check_type": "assessments_performed", "title": "Security Assessments", "description": "Conduct security assessments."},
    {"id": "CA-3", "theme": "Security Assessment", "check_type": "system_interconnections", "title": "System Interconnections", "description": "Authorize system interconnections."},
    {"id": "CA-5", "theme": "Security Assessment", "check_type": "plan_of_action", "title": "Plan of Action and Milestones", "description": "Track remediation plans."},
    {"id": "CA-7", "theme": "Security Assessment", "check_type": "continuous_monitoring", "title": "Continuous Monitoring", "description": "Monitor security controls continuously."},
    {"id": "CA-8", "theme": "Security Assessment", "check_type": "pen_testing", "title": "Penetration Testing", "description": "Conduct penetration testing."},
    {"id": "CA-9", "theme": "Security Assessment", "check_type": "internal_system_connections", "title": "Internal System Connections", "description": "Document internal system connections."},
    {"id": "CM-1", "theme": "Configuration Management", "check_type": "policies_present", "title": "Configuration Management Policy", "description": "Develop config management policies."},
    {"id": "CM-2", "theme": "Configuration Management", "check_type": "baseline_config", "title": "Baseline Configuration", "description": "Establish baseline configurations."},
    {"id": "CM-3", "theme": "Configuration Management", "check_type": "change_control", "title": "Configuration Change Control", "description": "Control changes to configurations."},
    {"id": "CM-4", "theme": "Configuration Management", "check_type": "impact_analysis", "title": "Impact Analysis", "description": "Analyze change impact."},
    {"id": "CM-5", "theme": "Configuration Management", "check_type": "access_restrictions_for_change", "title": "Access Restrictions for Change", "description": "Restrict access for config changes."},
    {"id": "CM-6", "theme": "Configuration Management", "check_type": "configuration_settings", "title": "Configuration Settings", "description": "Configure secure settings."},
    {"id": "CM-7", "theme": "Configuration Management", "check_type": "least_functionality", "title": "Least Functionality", "description": "Minimize system functionality."},
    {"id": "CM-8", "theme": "Configuration Management", "check_type": "inventory", "title": "System Component Inventory", "description": "Maintain component inventory."},
    {"id": "CM-9", "theme": "Configuration Management", "check_type": "config_plan", "title": "Configuration Management Plan", "description": "Document configuration management plan."},
    {"id": "CM-10", "theme": "Configuration Management", "check_type": "software_usage", "title": "Software Usage Restrictions", "description": "Restrict software usage."},
    {"id": "CM-11", "theme": "Configuration Management", "check_type": "user_installed_software", "title": "User-Installed Software", "description": "Control user-installed software."},
    {"id": "CP-1", "theme": "Contingency Planning", "check_type": "policies_present", "title": "Contingency Planning Policy", "description": "Develop contingency policy."},
    {"id": "CP-2", "theme": "Contingency Planning", "check_type": "backup_present", "title": "Contingency Plan", "description": "Develop contingency plan."},
    {"id": "CP-3", "theme": "Contingency Planning", "check_type": "training_present", "title": "Contingency Training", "description": "Provide contingency training."},
    {"id": "CP-4", "theme": "Contingency Planning", "check_type": "tests_performed", "title": "Contingency Plan Testing", "description": "Test contingency plan."},
    {"id": "CP-6", "theme": "Contingency Planning", "check_type": "backup_present", "title": "Alternate Storage Site", "description": "Use alternate storage site."},
    {"id": "CP-7", "theme": "Contingency Planning", "check_type": "backup_dr", "title": "Alternate Processing Site", "description": "Use alternate processing site."},
    {"id": "CP-8", "theme": "Contingency Planning", "check_type": "communications_redundancy", "title": "Telecommunications Services", "description": "Ensure telecom service continuity."},
    {"id": "CP-9", "theme": "Contingency Planning", "check_type": "backup_completed", "title": "System Backup", "description": "Perform system backups."},
    {"id": "CP-10", "theme": "Contingency Planning", "check_type": "system_recovery", "title": "System Recovery", "description": "Recover system after disruption."},
    {"id": "IA-1", "theme": "Identification & Authentication", "check_type": "policies_present", "title": "IA Policy and Procedures", "description": "Develop IA policies."},
    {"id": "IA-2", "theme": "Identification & Authentication", "check_type": "mfa_configured", "title": "Identification and Authentication", "description": "Identify and authenticate users."},
    {"id": "IA-3", "theme": "Identification & Authentication", "check_type": "device_auth", "title": "Device Identification", "description": "Identify devices before access."},
    {"id": "IA-4", "theme": "Identification & Authentication", "check_type": "identifier_mgmt", "title": "Identifier Management", "description": "Manage user identifiers."},
    {"id": "IA-5", "theme": "Identification & Authentication", "check_type": "password_policy", "title": "Authenticator Management", "description": "Manage authenticators."},
    {"id": "IA-6", "theme": "Identification & Authentication", "check_type": "feedback_disabled", "title": "Authenticator Feedback", "description": "Mask authentication feedback."},
    {"id": "IA-7", "theme": "Identification & Authentication", "check_type": "crypto_module", "title": "Cryptographic Module Auth", "description": "Use FIPS-validated crypto for auth."},
    {"id": "IR-1", "theme": "Incident Response", "check_type": "policies_present", "title": "IR Policy and Procedures", "description": "Develop incident response policy."},
    {"id": "IR-2", "theme": "Incident Response", "check_type": "training_present", "title": "IR Training", "description": "Train incident response team."},
    {"id": "IR-3", "theme": "Incident Response", "check_type": "tests_performed", "title": "IR Testing", "description": "Test incident response capability."},
    {"id": "IR-4", "theme": "Incident Response", "check_type": "incident_handling", "title": "Incident Handling", "description": "Handle incidents according to plan."},
    {"id": "IR-5", "theme": "Incident Response", "check_type": "incident_monitoring", "title": "Incident Monitoring", "description": "Track and document incidents."},
    {"id": "IR-6", "theme": "Incident Response", "check_type": "incident_reporting", "title": "Incident Reporting", "description": "Report incidents to appropriate authorities."},
    {"id": "IR-7", "theme": "Incident Response", "check_type": "ir_resources", "title": "IR Assistance", "description": "Provide incident response resources."},
    {"id": "MA-1", "theme": "Maintenance", "check_type": "policies_present", "title": "Maintenance Policy", "description": "Develop maintenance policy."},
    {"id": "MA-2", "theme": "Maintenance", "check_type": "scheduled_maintenance", "title": "Controlled Maintenance", "description": "Control maintenance activities."},
    {"id": "MA-3", "theme": "Maintenance", "check_type": "maintenance_tools", "title": "Maintenance Tools", "description": "Control maintenance tools."},
    {"id": "MA-4", "theme": "Maintenance", "check_type": "remote_maintenance", "title": "Nonlocal Maintenance", "description": "Control remote maintenance."},
    {"id": "MA-5", "theme": "Maintenance", "check_type": "maintenance_personnel", "title": "Maintenance Personnel", "description": "Authorize maintenance personnel."},
    {"id": "MP-1", "theme": "Media Protection", "check_type": "policies_present", "title": "Media Protection Policy", "description": "Develop media protection policy."},
    {"id": "MP-2", "theme": "Media Protection", "check_type": "media_access", "title": "Media Access", "description": "Restrict media access."},
    {"id": "MP-3", "theme": "Media Protection", "check_type": "media_labeling", "title": "Media Labeling", "description": "Label sensitive media."},
    {"id": "MP-4", "theme": "Media Protection", "check_type": "media_storage", "title": "Media Storage", "description": "Store media securely."},
    {"id": "MP-5", "theme": "Media Protection", "check_type": "media_transport", "title": "Media Transport", "description": "Protect media during transport."},
    {"id": "MP-6", "theme": "Media Protection", "check_type": "media_sanitization", "title": "Media Sanitization", "description": "Sanitize media before disposal."},
    {"id": "MP-7", "theme": "Media Protection", "check_type": "media_usage", "title": "Media Usage", "description": "Restrict media use."},
    {"id": "PE-1", "theme": "Physical Security", "check_type": "policies_present", "title": "Physical Security Policy", "description": "Develop physical security policy."},
    {"id": "PE-2", "theme": "Physical Security", "check_type": "access_control_system", "title": "Physical Access Authorizations", "description": "Authorize physical access."},
    {"id": "PE-3", "theme": "Physical Security", "check_type": "physical_access_control", "title": "Physical Access Control", "description": "Control physical access to facilities."},
    {"id": "PE-4", "theme": "Physical Security", "check_type": "physical_access_monitoring", "title": "Access Control for Transmission", "description": "Control physical access to transmission lines."},
    {"id": "PE-5", "theme": "Physical Security", "check_type": "physical_access_audit", "title": "Access Control for Output Devices", "description": "Control access to output devices."},
    {"id": "PE-6", "theme": "Physical Security", "check_type": "cctv_present", "title": "Monitoring Physical Access", "description": "Monitor physical access."},
    {"id": "PL-1", "theme": "Planning", "check_type": "policies_present", "title": "Security Planning Policy", "description": "Develop security plan policy."},
    {"id": "PL-2", "theme": "Planning", "check_type": "system_security_plan", "title": "System Security Plan", "description": "Develop system security plan."},
    {"id": "PS-1", "theme": "Personnel Security", "check_type": "policies_present", "title": "Personnel Security Policy", "description": "Develop personnel security policy."},
    {"id": "PS-2", "theme": "Personnel Security", "check_type": "background_checks", "title": "Position Risk Designation", "description": "Categorize personnel risk."},
    {"id": "PS-3", "theme": "Personnel Security", "check_type": "background_checks", "title": "Personnel Screening", "description": "Screen personnel before access."},
    {"id": "PS-4", "theme": "Personnel Security", "check_type": "termination_procedures", "title": "Personnel Termination", "description": "Handle personnel termination."},
    {"id": "PS-5", "theme": "Personnel Security", "check_type": "transfer_procedures", "title": "Personnel Transfer", "description": "Handle personnel transfers."},
    {"id": "RA-1", "theme": "Risk Assessment", "check_type": "policies_present", "title": "Risk Assessment Policy", "description": "Develop risk assessment policy."},
    {"id": "RA-2", "theme": "Risk Assessment", "check_type": "categorization", "title": "Security Categorization", "description": "Categorize system by risk."},
    {"id": "RA-3", "theme": "Risk Assessment", "check_type": "risk_assessment_completed", "title": "Risk Assessment", "description": "Conduct risk assessment."},
    {"id": "RA-5", "theme": "Risk Assessment", "check_type": "vuln_scanner", "title": "Vulnerability Scanning", "description": "Scan for vulnerabilities."},
    {"id": "SA-1", "theme": "System Acquisition", "check_type": "policies_present", "title": "System Acquisition Policy", "description": "Develop acquisition policy."},
    {"id": "SA-2", "theme": "System Acquisition", "check_type": "allocation_of_resources", "title": "Allocation of Resources", "description": "Allocate resources for security."},
    {"id": "SA-3", "theme": "System Acquisition", "check_type": "system_development_lifecycle", "title": "System Development Lifecycle", "description": "Integrate security into SDLC."},
    {"id": "SA-4", "theme": "System Acquisition", "check_type": "acquisition_procurement", "title": "Acquisition Process", "description": "Include security requirements in acquisitions."},
    {"id": "SA-5", "theme": "System Acquisition", "check_type": "sysdoc_present", "title": "System Documentation", "description": "Document system security."},
    {"id": "SC-1", "theme": "System & Communications Protection", "check_type": "policies_present", "title": "SC Protection Policy", "description": "Develop system communications policy."},
    {"id": "SC-2", "theme": "System & Communications Protection", "check_type": "application_partitioning", "title": "Application Partitioning", "description": "Separate user functionality from system management."},
    {"id": "SC-4", "theme": "System & Communications Protection", "check_type": "shared_resource_protection", "title": "Information in Shared Resources", "description": "Prevent unauthorized information sharing."},
    {"id": "SC-5", "theme": "System & Communications Protection", "check_type": "ddos_protection", "title": "Denial of Service Protection", "description": "Protect against DoS attacks."},
    {"id": "SC-7", "theme": "System & Communications Protection", "check_type": "fw_blocked", "title": "Boundary Protection", "description": "Monitor and control communications at system boundary."},
    {"id": "SC-8", "theme": "System & Communications Protection", "check_type": "tls_enabled", "title": "Transmission Confidentiality", "description": "Protect transmitted data."},
    {"id": "SC-12", "theme": "System & Communications Protection", "check_type": "kms_configured", "title": "Cryptographic Key Management", "description": "Manage cryptographic keys."},
    {"id": "SC-13", "theme": "System & Communications Protection", "check_type": "fips_crypto", "title": "Cryptographic Protection", "description": "Use FIPS-validated cryptography."},
    {"id": "SC-15", "theme": "System & Communications Protection", "check_type": "collaborative_computing", "title": "Collaborative Computing", "description": "Control collaborative computing devices."},
    {"id": "SC-18", "theme": "System & Communications Protection", "check_type": "mobile_code", "title": "Mobile Code", "description": "Control mobile code."},
    {"id": "SC-20", "theme": "System & Communications Protection", "check_type": "dns_security", "title": "Secure Name/Address Resolution", "description": "Ensure DNS integrity."},
    {"id": "SC-23", "theme": "System & Communications Protection", "check_type": "session_authenticity", "title": "Session Authenticity", "description": "Protect session authenticity."},
    {"id": "SC-28", "theme": "System & Communications Protection", "check_type": "disk_encrypted", "title": "Protection of Information at Rest", "description": "Protect data at rest."},
    {"id": "SC-39", "theme": "System & Communications Protection", "check_type": "process_isolation", "title": "Process Isolation", "description": "Maintain separate execution domains."},
    {"id": "SI-1", "theme": "System Integrity", "check_type": "policies_present", "title": "System Integrity Policy", "description": "Develop integrity policy."},
    {"id": "SI-2", "theme": "System Integrity", "check_type": "patch_management", "title": "Flaw Remediation", "description": "Remediate system flaws."},
    {"id": "SI-3", "theme": "System Integrity", "check_type": "malware_protection", "title": "Malicious Code Protection", "description": "Deploy malicious code protection."},
    {"id": "SI-4", "theme": "System Integrity", "check_type": "ids_ips_enabled", "title": "System Monitoring", "description": "Monitor system for intrusions."},
    {"id": "SI-5", "theme": "System Integrity", "check_type": "security_alerts", "title": "Security Alerts and Advisories", "description": "Receive and act on security alerts."},
    {"id": "SI-6", "theme": "System Integrity", "check_type": "security_function_verification", "title": "Security Function Verification", "description": "Verify security functions."},
    {"id": "SI-7", "theme": "System Integrity", "check_type": "integrity_monitoring", "title": "Software Integrity", "description": "Verify software integrity."},
    {"id": "SI-8", "theme": "System Integrity", "check_type": "spam_protection", "title": "Spam Protection", "description": "Deploy spam protection."},
    {"id": "SI-10", "theme": "System Integrity", "check_type": "input_validation", "title": "Information Input Validation", "description": "Validate input."},
    {"id": "SI-11", "theme": "System Integrity", "check_type": "error_handling", "title": "Error Handling", "description": "Handle errors without revealing information."},
    {"id": "SI-12", "theme": "System Integrity", "check_type": "information_handling", "title": "Information Handling and Retention", "description": "Handle and retain info per policy."},
    {"id": "SI-16", "theme": "System Integrity", "check_type": "memory_protection", "title": "Memory Protection", "description": "Protect memory from unauthorized execution."},
    {"id": "SR-1", "theme": "Supply Chain Risk", "check_type": "policies_present", "title": "Supply Chain Risk Policy", "description": "Develop SCRM policy."},
    {"id": "SR-2", "theme": "Supply Chain Risk", "check_type": "supplier_assessment", "title": "Supply Chain Risk Management", "description": "Assess supply chain risks."},
    {"id": "SR-3", "theme": "Supply Chain Risk", "check_type": "supplier_contracts", "title": "Supply Chain Controls", "description": "Implement supply chain controls."},
    {"id": "SR-4", "theme": "Supply Chain Risk", "check_type": "supplier_monitoring", "title": "Provenance", "description": "Track component provenance."},
]


from ._common_checks import run_check as _run_check, now as _now


async def evaluate_controls(db) -> List[Dict[str, Any]]:
    """Run all checks for this framework's controls. See _common_checks.py."""
    results = []
    for ctrl in CONTROLS:
        status, evidence = await _run_check(db, ctrl)
        results.append({**ctrl, "status": status, "evidence": evidence, "evaluated_at": _now()})
    return results
