# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['dist\\python-agent\\agent.py'],
    pathex=['dist\\python-agent'],
    binaries=[],
    datas=[
        ('dist\\python-agent\\capabilities', 'capabilities'),
    ],
    hiddenimports=[
        'win32serviceutil', 'win32service', 'win32event',
        'servicemanager', 'win32timezone', 'pywintypes',
        'scapy.layers.all', 'scapy.route',
        'capabilities',
        'capabilities.base',
        'capabilities.metrics',
        'capabilities.logs',
        'capabilities.fim',
        'capabilities.real_scan',
        'capabilities.vuln_scan',
        'capabilities.compliance',
        'capabilities.runtime_security',
        'capabilities.predictive_health',
        'capabilities.ueba',
        'capabilities.sbom',
        'capabilities.ebpf',
        'capabilities.system_patching',
        'capabilities.software_management',
        'capabilities.remote_access',
        'capabilities.network_discovery',
        'capabilities.update_capability',
        'sqlite3',
        'yaml',
        'psutil',
        'requests',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='omni-agent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
